### ISSUE TITLE
A few doubts after reading and googling a lot

### ISSUE THREAD

**Issue by fiferrari** [InstaPy/InstaPy#1040]
Hello everyone,

I started with instapy about 3 days ago and have finally something running. Sorry if my doubts are too basic but I'd really appreciate if someone took a couple of minutes to guide me in the right directions. What I can't understand so far is:

- How do I change the order of the activities? In my current quickstart I have comments coming first, then interaction with someone else's followers and lastly the likes. However, when I run my file, it will always start with the interaction with someone else's followers.

- How do I randomize tags? I even found articles here about this but my difficulty is to read all the codes and where to put them. At the moment whenever my tags start to be likes, they will always go in the same order.

- How do I change the speed of the tasks? I've seen other "apps" that u enter the interval in between likes, let's say 30 seconds. I know that instapy works differently but is there a way at all to like / comment / follow faster?

Thank you so much,

F

**Comment by timgrossmann** [comment]
@fiferrari Sure, no worries.

- The way InstaPy works right now is, that you define the behavior by first setting the way it should interact. This is done with al the `.set_....` methods. These methods won't do anything in terms of interacting on Instagram, their purpose is to tell InstaPy what you want to do. E.g. comment with a specific percentage and with specified comments. This means that you can only switch the `.like_by...`, `.follow_....`  or `.interact_...`   
So what you always have to do is:
```python
session = InstaPy(.....)
session.login()

# now all the setters
session.set_do_follow(....)
session.set_....
...
...
...

# actual interactions, these are .follow_..., .like_by_.... or .interact_....
.like_by_tag(....)
```

- Check out the random library of python. You can simply do:
```python
from random import sample

tags = ['tag1', 'tag2', 'tg3', ..., 'tagN']

# now use this list in the e.g .like_by_tag method, the second parameter in the sample method is the number of entries you want to get from the tags list
session.like_by_tags(sample(tags, 2), amount=50)
# this one gets 2 random tags from the list and likes 50 posts each
```

- There are some methods that already have that feature but it's really prototypical... It does not work really good and mostly not as expected, there are some improvements in development, but as of now, the tool is setup so it definitely won't get you banned because of the speed. (You still can get banned if you do too much)

Hope that helps

**Comment by fiferrari** [comment]
@timgrossmann Hi Tim! thanks for replying and congrats on all the work, kind of feeling starstruck right now hehe. I will try to work with my setup later and see how it works. Another question: If the setup is defined by the .set methods. What happens if all the actions are completed? does the script repeats itself automatically?

Thanks again

**Comment by converge** [comment]
hey @fiferrari , after all actions are completed, the bot stops. you can schedule it using cron (check out the readme).

**Comment by fiferrari** [comment]
Thanks guys...where can I find details of what the codes mean? I'd really like to understand them but I can't seem to find an explanation for dummies...I'm not a programmer so it's been difficult. For example, the false and true words. Let's take "session.set_do_follow" as an example. It's used with both false and true in front of it depending on what you try to accomplish. 

Also, if I use a command as part of one "task", do I need to repeat it if it's used in another task?

Thanks again.

**Comment by converge** [comment]
@fiferrari we have it documented here with detailed informations, check it out:
https://github.com/timgrossmann/InstaPy
