### ISSUE TITLE
Post link validity check

### ISSUE THREAD

**Issue by harmanpreet93** [InstaPy/InstaPy#111]
Post might get deleted, hence raising 'Page Not Found' issue. 

Scripts stops at that point with ValueError: Need more than two values to unpack

**Comment by eduardocalazansjr** [comment]
This was fixed in the past.

You have the full tracelog?

**Comment by harmanpreet93** [comment]
Adding screenshot! @vlntdds 

![trace](https://cloud.githubusercontent.com/assets/9989122/25066481/3e12b8c0-2244-11e7-970c-3340920e62f0.png)

**Comment by pekapa** [comment]
Just created a PR to fix that.

**Comment by eduardocalazansjr** [comment]
@pekapa it fixes, but now i get "Invalid Like Element!'" after the "Unavailable Page" and it stucks in the same page. Could you check, please?

![image](https://cloud.githubusercontent.com/assets/5658870/25066818/d1fbb358-2207-11e7-9376-8c81b4d21b80.png)

Thanks.

Edit: it seems to reload the page, since i've forced an bad url on the link attr, but the history doesn't show, nevermind.

But, could you check the Invalid Like Element, please?

**Comment by pekapa** [comment]
Done.
I changed the behaviour to it's now considered as "inappropriate" and don't try to like it.

I think the term "inappropriate" is starting to be used for other things and should probably be changed (also, to reverse the boolean logic so it's more friendly as suggested in another issue).

**Comment by eduardocalazansjr** [comment]
Thanks, i've merged it.
@harmanpreet93 could you test now?

**Comment by harmanpreet93** [comment]
Yeah! its working fine now! @vlntdds
