### ISSUE TITLE
Direct Messaging via iOS or Android build?

### ISSUE THREAD

**Issue by charliecode** [InstaPy/InstaPy#1129]
## Expected Behavior

Auto Direct Messaging?

## Current Behavior

Doesn't look possible via desktop because the feature doesn't seem to be implemented via the web.

## Possible Solution (optional)

Would it be possible to implement via iOS or Android build? Since the features are available there. I'm an iOS developer but haven't messed with IG. Looking for possible suggestions on moving forward.

**Comment by sionking** [comment]
chromedriver have android emulator so should be

**Comment by joshuachinemezu** [comment]
@charliecode, using this approach https://github.com/timgrossmann/InstaPy/issues/4496#issuecomment-497947408, you can run the web driver in an android web browser because I noticed that you can send DMs from the mobile version of the web app unlike in the desktop web version. I plan on creating a pull request for my solution to this issue.
