### ISSUE TITLE
is there still someone with the suspicious login attempt issue ?

### ISSUE THREAD

**Issue by converge** [InstaPy/InstaPy#1162]

**Comment by Naramsim** [comment]
Mine is gone and I'm on Azure! And I have to delete the cookie every time a new Instapy session starts. (I'm using Schedule)

**Comment by victor-falcon** [comment]
When I run it on DigitalOcean I get this error. On local it's works 🤔 

```INFO - Session started - 2017-12-30 12:34:31
Traceback (most recent call last):
  File "./opn_unfollow.py", line 10, in <module>
    session.login()
  File "/root/InstaPy/instapy/instapy.py", line 227, in login
    self.bypass_suspicious_attempt):
  File "/root/InstaPy/instapy/login_util.py", line 93, in login_user
    browser.get('https://www.instagram.com')
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 323, in get
    self.execute(Command.GET, {'url': url})
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 311, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 237, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from tab crashed
  (Session info: headless chrome=63.0.3239.108)
  (Driver info: chromedriver=2.34.522913 (36222509aa6e819815938cbf2709b4849735537c),platform=Linux 4.4.0-87-generic x86_64)```

**Comment by converge** [comment]
@Victoor what's your hardware droplet setup ?

**Comment by victor-falcon** [comment]
@converge it's an 1 GB Memory / 30 GB Disk / LON1 - Ubuntu Wordpress on 16.04

**Comment by converge** [comment]
@Victoor could you try it ?
```sudo killall Xvfb xvfb chrome```
and try again.

**Comment by victor-falcon** [comment]
@converge that works! thanks! 👍👍👍👍

**Comment by ghost** [comment]
I still get this endless "unusual login attempt"-loop with some accounts. Here are some details about the accounts:

- Active for over 12 month
- Used a java instagram library since 3 month for getting infos about my accounts

Since 3 days now I have to click the "It was me"-button for every login attempt. At issue #1074 the solution has been to type in the security code. But instead of getting the message "Instagram detected an unusual login attempt" I get the error "CRITICAL Wrong login data!".

Is there any solution for instagram's spam detection improvement from December '17?
