### ISSUE TITLE
ImportError: No module named selenium

### ISSUE THREAD

**Issue by Amber-Williams** [InstaPy/InstaPy#1178]
I googled this issue and can't seem to find any resolution. I've installed selenium but the selenium module can't be found. 

See the terminal messages below i'm getting:

Neriums-Mini:~ nerium$ pip3 install selenium
Requirement already satisfied: selenium in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages
Neriums-Mini:~ nerium$ cd InstaPy
Neriums-Mini:InstaPy nerium$ python quickstart.py
Traceback (most recent call last):
  File "quickstart.py", line 1, in <module>
    from instapy import InstaPy
  File "/Users/nerium/InstaPy/instapy/__init__.py", line 1, in <module>
    from .instapy import InstaPy
  File "/Users/nerium/InstaPy/instapy/instapy.py", line 12, in <module>
    from selenium import webdriver
ImportError: No module named selenium

![screen shot 2018-01-02 at 8 55 38 pm]
(https://user-images.githubusercontent.com/27780374/34507813-6018b224-efff-11e7-804d-fe0965d05e73.png)

**Comment by gitpatrickhub** [comment]
Did you try;
```
python3 quickstart.py

**Comment by ptkdev** [comment]
If you use debian/ubuntu try:
`apt-get install python-selenium`

**Comment by ghost** [comment]
Both didn't work. I would like to add I got this to work on my laptop with "sudo python setup.py install" because "python setup.py install" wouldn't work. 

But on my desktop  the sudo command is followed by "(Mycomputername) is not in the sudoers file.  This incident will be reported." I did have 2 admin accounts and the one i'm using wasn't the original
  

> Neriums-Mini:~ margee$ cd InstaPy
Neriums-Mini:InstaPy margee$ python3 quickstart.py
Traceback (most recent call last):
  File "quickstart.py", line 1, in <module>
    from instapy import InstaPy
  File "/Users/margee/InstaPy/instapy/__init__.py", line 1, in <module>
    from .instapy import InstaPy
  File "/Users/margee/InstaPy/instapy/instapy.py", line 11, in <module>
    from pyvirtualdisplay import Display
  File "/Users/margee/InstaPy/pyvirtualdisplay/__init__.py", line 3, in <module>
    from pyvirtualdisplay.display import Display
  File "/Users/margee/InstaPy/pyvirtualdisplay/display.py", line 1, in <module>
    from pyvirtualdisplay.abstractdisplay import AbstractDisplay
  File "/Users/margee/InstaPy/pyvirtualdisplay/abstractdisplay.py", line 1, in <module>
    from easyprocess import EasyProcess
  File "/Users/margee/InstaPy/easyprocess/__init__.py", line 227
    except OSError, oserror:
                  ^
SyntaxError: invalid syntax
Neriums-Mini:InstaPy margee$ apt-get install python-selenium
-bash: apt-get: command not found
Neriums-Mini:InstaPy margee$ cd
Neriums-Mini:~ margee$ apt-get install python-selenium
-bash: apt-get: command not found

**Comment by Amber-Williams** [comment]
I figured it out...for some reason there was an issue with having multiple admin user accounts on my MacOS so I removed the other admin. 
Then redownloaded and used "sudo python setup.py install" to install as the "python setup.py install" wouldn't work.

**Comment by waseem312** [comment]
I am having the same issue.I am using ubuntu OS.Please help me.

**Comment by Amber-Williams** [comment]
@waseem312 do you have multiple users on your computer and you're on a MacOS?

**Comment by waseem312** [comment]
I am using Ubuntu 16 that have 2 users one : root second : ubuntu.These are the default users of Ubuntu.

**Comment by Amber-Williams** [comment]
I'm not familiar with running Ubuntu...though my issue stemmed from having
more then one user for what ever reason. I deleted the other and it worked
okay. Would recommend trying that or if you can't remove the other user
posting a new help post as I did.

Best of luck!

**Comment by frankpitale** [comment]
on MacOS is still not working, also after chromedriver download in the asset folder....damn, please help me.
on youtube videos seems so stupid and easy!
