### ISSUE TITLE
Not letting me run windows powershell file.

### ISSUE THREAD

**Issue by BlaneWins** [InstaPy/InstaPy#1181]
<img alt="" src="https://s13.postimg.org/wxmxvb7lz/piss.png" />

Getting all kinds of errors. Already tried changing the permissions of the files and running as admin. When I run as admin it says it can not locate cmdlet.

I tried running the gui without doing this and it says im missing a module called 'request'

I have no clue what to do. I'm a complete noob at any type of programming and messed around with this for a good four hours straight.

**Comment by patrickdundas** [comment]
The issue isn’t with running that powershell file. You can ignore those errors. All they are saying is that the chrome driver and GUI tool are already installed. If something isn’t working then it isn’t because of that powershell file, as it is doing what it is supposed to

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BlaneWins** [comment]
You overlooked the errors. Error number 2: No such file or directory and Error number 13: Permission denied.
