### ISSUE TITLE
Question - set_do_follow

### ISSUE THREAD

**Issue by 0xkvai** [InstaPy/InstaPy#1305]
## Expected Behavior
# default enabled=False, follows ~ 10% of the users from the images, times=1
# (only follows a user once (if unfollowed again))

session.set_do_follow(enabled=True, percentage=10, times=2)

## Current Behavior
What does the (times=2) parameter mean?
If the script will follow 10 percent of users, what does times=2 mean?

Thank you,
just need clarification.

**Comment by lucanello** [comment]
That means that InstaPy will follow one single user twice. If you set it to 1 it would only follow each user one single time.
This feature was added because @timgrossmann got messages asking him why he always follows and unfollows them.

times=2 -> follow, unfollow, follow, (unfollow optionally)
times=1 -> follow, (unfollow optionally)

**Comment by luigifaticoso** [comment]
To be more clear, if you follow and then unfollow someone and the bot will find him again, the bot won't follow him if you have put times=1

**Comment by 0xkvai** [comment]
Thank you,
this clears it up for me!
