### ISSUE TITLE
maximum number of pictures liked

### ISSUE THREAD

**Issue by riccardorighettiphoto** [InstaPy/InstaPy#1382]
Hello,
I am new here as InstaPy user on a Windows 7 machine. I installed InstaPy along with the third-party InstaGUI.
If I select a number of pictures to like from tags (e.g. 30 or more), the program loops within a maximum number of 26 or 27 pictures.

**Comment by voskresla** [comment]
Approve. 
like_by_tags / like_by_locations - only 27 pictures since today.

**Comment by uluQulu** [comment]
Is not an InstaGUI issue, recently Instagram changed scrolling pic link scope
It is fixed [here](https://github.com/timgrossmann/InstaPy/issues/1365#issuecomment-363586896)
@riccardorighettiphoto @voskresla

**Comment by riccardorighettiphoto** [comment]
@uluQulu 
Sorry, but the fix in the post you suggested does not work. When I run the script it crashes.

**Comment by uluQulu** [comment]
@riccardorighettiphoto first of all, you did not apply the fix correctly (there were indentation errors in the `like_util` you shared)
but also yes, there might be some changes happened lately, too.. but my accaunts are not affected by it, that's why it's very hard to try to determine the possible newest changes and how it behaves in your side, but can be solved if you can provide more details...

**Comment by riccardorighettiphoto** [comment]
@uluQulu 
Hi, I re-checked once again the code and It had indentation errors indeed. I could not imagine that indentation would be so important and to-managed-carefully...
Anyway, now it looks like working. I hope that fix will be add in the next project update.

Thanks for now.
