### ISSUE TITLE
More information on multiple accounts?

### ISSUE THREAD

**Issue by quintendewilde** [InstaPy/InstaPy#1469]
Could there be more information on how to run multiple accounts? Is this multiple files that run with python? The only thing being set is the `multi_logs=True` but it's not clear to me on how you get multiple accounts to work. 

Do you just copy the quickstart and use another profile?

**Comment by lucanello** [comment]
The easiest method is to copy the `quickstart.py`, fill it with new data and run them in a screen. That's how I am using InstaPy. But be careful and don't use the same IP for too many accounts at the same time. If you're running it from a local machine you probably don't have to worry since your IP usually reconnects after 24 hours.

**Comment by leoch20** [comment]
@lucanello I have copied quickstart.py and filled the new account info. When I tried to run the new account my execution dies before the accounts logs into instagram. I'm running it in my windows machine. Is there anything else that needs to be done?

**Comment by lucanello** [comment]
@leoch20 Can you please share the error message or the log? It's really hard to understand errors when there is no additional information.

**Comment by leoch20** [comment]
@lucanello I actually got it working by running each `quickstart.py` at a time. I would like to run more than one at the same time. Do you know if that is possible?

**Comment by lucanello** [comment]
@leoch20 This works totally fine for me. Can you share your quickstart.py scripts? Please make sure to remove your login information.
Unfortunately I can't help you with operating system specific topics, since I am not running my scripts on a Windows machine.

**Comment by octavius-1** [comment]
@lucanello So, is there a problem running multiple accounts using the same IP but not the same network? I have some raspberries connected and I personalized some static IPs to each device, am I doing this wrong?

**Comment by Tr1pke** [comment]
@leoch20 , I have copied quickstart.py and filled the new account info. When I tried to run the new account my execution dies before the accounts logs into instagram. I'm running it in my windows machine. Is there anything else that needs to be done?

my answer: yes remove windows and install linux

**Comment by lucanello** [comment]
Hello @octavius-1, sorry for the late response. You should not use too many accounts with only one IP. Instagram can only detect your IP and not your network, so it doesn't matter where and how your network is set up when it's using the same IP.

@Tr1pke can you provide more information like an error code or logs? It's difficult to identify the problem without any further informations.

**Comment by Tr1pke** [comment]
@lucanllo i use virtual machines with multiple network cards. I run Ubuntu and Debian

**Comment by Madgeniusblink** [comment]
@lucanello 

Hi Luca, 

So what you are saying is in the same folder as INSTA-MASTER (root directory) where the main quickstart.py is located,   to just duplicate quickstart.py and keep it named the same? And then add the new account credentials in it and run the command "python quickstart.py"?

Or would I have to duplicate quickstart.py and call it a different name (for example: quickstartnew.py) then run the command "python" in order to run both?

The other way I thought would work is by creating a new folder called "accounts" and then replacing the quickstart.py for a script to execute each file in the folder "accounts".

Let me know what you think, thank you.

**Comment by Tr1pke** [comment]
The name doesn’t need to be QuickStart.py
I have insta-accountname1.py insta-accountname2.py etc

**Comment by lucanello** [comment]
Hi @Madgeniusblink, you should duplicate the quickstart.py and call it like @Tr1pke mentioned. My quickstart.py's are just named with the username.
To start these bots just execute them with python. So for each individual account just execute `python <username>/quickstart.py`. If you want to execute them all at the same time you can write a small bash-script which:

```
#!/bin/sh
python3 quickstart-1.py
python3 quickstart-2.py
```

By executing this bash-script `bash <scriptname>.sh`, all included bots will begin to run. Please note that using screen is very handy.
Install this tool with `apt-get install screen` and change your bash-script to this:

```
#!/bin/sh
screen -dmS bot-1 python3 quickstart-1.py
screen -dmS bot-2 python3 quickstart-2.py
```

I hope I could help.

**Comment by Tr1pke** [comment]
This command is a bitt more useful, then you can see the end process also, if you use -dmS, screen quits when its done. With this command it doesn't quit and you can see the end results

screen -dmS instagramname sh -c 'python3 InstaPy/instagramname-follow-unfollow.py; exec bash'

**Comment by rastislavuhrin** [comment]
@lucanello  @Tr1pke 
Hi guys,
how could you please run more quickstarst at the same time with different accounts when browsers doesn't allow you to sign in with different account on different tabs/windows, unless you log in to incognito mode.
As soon as i run second quickstart i trows me this error

Traceback (most recent call last):
  File "insta-rasto.py", line 28, in <module>
    session = InstaPy(username=insta_username,
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python38-32\lib\site-packages\instapy\instapy.py", line 312, in __init__
    self.browser, err_msg = set_selenium_local_session(
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python38-32\lib\site-packages\instapy\browser.py", line 128, in set_selenium_local_session
    browser.install_addon(create_firefox_extension(), temporary=True)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python38-32\lib\site-packages\instapy\browser.py", line 46, in create_firefox_extension
    with zipfile.ZipFile(zip_file, "w", zipfile.ZIP_DEFLATED, False) as zipf:
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python38-32\lib\zipfile.py", line 1251, in __init__
    self.fp = io.open(file, filemode)
OSError: [Errno 22] Invalid argument: 'C:\\Users\\Acer\\InstaPy\\assets\\extension.xpi'

and i found out, that its because my firefox window from first account is still opened - when i close it, than on the first account appears error because of that but the second account run without this error.
But if i leave the old window which was opened by first account, does not matter if there's instagram page or not, the error occurs.
When i opened firefox window and not instapy, than i can run without this error.
I searched for solution and i only found one, to delete extension.xpi but it does not help since it's automatically created every time.

Also my .bat/.sh (i'm using windows) file did't work properly because it would only run first command, and run the second command only when the first is done, not at the same time.

@ECHO OFF
py insta-endricho.py
py insta-rasto.py
PAUSE

Thank you very much in forward
