### ISSUE TITLE
How to loop a section of code?

### ISSUE THREAD

**Issue by RenegadeHD** [InstaPy/InstaPy#1496]
So in my program I want my bot to complete one action and then after it's done, perform another action. What I mean by this is to have it interact with people, then unfollow, then interact, then unfollow and so on. This is what I have so far

 instapy import InstaPy
import os
session = InstaPy(username='123', password='123')
session.login()

**session.set_user_interact(amount=1, randomize=True, percentage=100, media='Photo')
session.set_do_follow(enabled=True, percentage=100)
session.set_do_like(enabled=True, percentage=100)
session.set_comments(["Cool", "Nice!"])
session.set_do_comment(enabled=True, percentage=80)
session.interact_user_followers(['tech_insider', 'pcgaming', 'pcmagofficial'], amount=99999999, randomize=True)**

_session.unfollow_users(amount=500, onlyInstapyFollowed = False, onlyInstapyMethod = 'FIFO', sleep_delay=60 )_

session.end()

So what I need it to do is to complete the first half(in bold), then do the last half (in italics) then go back to the first and keep going. Any help??

**Comment by uluQulu** [comment]
Hi @RenegadeHD 

```python
instapy import InstaPy
import os

##START
session = InstaPy(username='123', password='123')

##LOGIN
session.login()

##SETTINGS
session.set_user_interact(amount=1, randomize=True, percentage=100, media='Photo')
session.set_do_follow(enabled=True, percentage=100)
session.set_do_like(enabled=True, percentage=100)
session.set_comments(["Cool", "Nice!"])
session.set_do_comment(enabled=True, percentage=80)

##ACTIONS
for cycle in range(7):
    print("\n\nLOOP {}\n".format(cycle+1))
    session.interact_user_followers(['tech_insider', 'pcgaming', 'pcmagofficial'], amount=9999999, randomize=True)
    sleep(50)   #take a 50 seconds of break after finishing the feature above
    session.unfollow_users(amount=500, onlyInstapyFollowed = False, onlyInstapyMethod = 'FIFO', sleep_delay=60 )
    sleep(30)   #take some more break after finishing unfollows

##END
session.end()
```
It will loop those actions 7 times and if you wanna loop one hundred times, write there `for cycle in range(100)`

**Comment by RenegadeHD** [comment]
@uluQulu Hey man, tried running the code but for some reason it won't get past even the login code before shutting down. I don't know why it wouldn't work, the code seems fine to me and I've even messed around by switching settings and features.. IDK if you can help still but thanks

**Comment by uluQulu** [comment]
@RenegadeHD traceback traceback how is traceback?
provide error and details to troubleshoot, we can get it work!

**Comment by imbarismustafa** [comment]
Hello. I have modified the code little bit and for me it WORKS GREAT! I have not changed the cycles but i will try it in the next 24 hours. Thank you for submitting the code! The changes i made was to import time and os and change the structure of  the beginning. Also instead of sleep(seconds) i changed to time.sleep(seconds). Hope this helps.

I am new here and if possible can someone explain to me how the structure of the code works so i can modify it in a way that i want. How the ordering system works and the numbers and percentages. How each code is related to each other and etc.

Otherwise you can use the code to have fun. For 12 hours i got 20 followers. Which i think is great. It would be even better as i said if i knew the true meaning of the code so i can modify further. 

.......................................................................................................................................................................................

from instapy import InstaPy
import time
import os 

insta_username = 'username'
insta_password = 'password'

session = InsyaPy(username=insta_username, password=insta_password, headless_browser=True)
session.login()

session.set_user_interact(amount=1, randomize=True, percentage=100, media='Photo')
session.set_do_follow(enabled=True, percentage=100)
session.set_do_like(enabled=True, percentage=100)
session.set_comments(["Cool", "Nice!"])
session.set_do_comment(enabled=True, percentage=80)

for cycle in range(7):
    print("\n\nLOOP {}\n".format(cycle+1))
    session.interact_user_followers(['tech_insider', 'pcgaming', 'pcmagofficial'], amount=9999999, randomize=True)
    time.sleep(50)   #take a 50 seconds of break after finishing the feature above
    session.unfollow_users(amount=500, onlyInstapyFollowed = False, onlyInstapyMethod = 'FIFO', sleep_delay=60 )
    time.sleep(30)   #take some more break after finishing unfollows

session.end()

**Comment by imbarismustafa** [comment]
@uluQulu @RenegadeHD Please check me previous comment and also:

I am having this issue but it is not a huge problem:

-->Now following
log_followed_pool error [Errno 13] Permission denied: './logs/my ig username_followedPool.csv'
log__record_all_followed_pool error [Errno 13] Permission denied: './logs/my ig username_record_all_followed.csv

That is after each following. Not sure why but overall the code works and i can see that follows and unfollows people.

Also as i mentioned previously would be great if someone explains how structuring the code of instructions works, how and why should some code be before other lines of code and what is their relationship between the settings and action.

Thanks!
