### ISSUE TITLE
Skipping image because deemed innapropriate

### ISSUE THREAD

**Issue by maxinedotdev** [InstaPy/InstaPy#153]
Would it not be more logical to not increment the number of pictures liked in a sequence if one of the pictures hit one of the conditions of session.set_dont_like?

For example, if picture [1/100] includes the tag 'mumbo', a tag that is deemed inappropriate by session.set_dont_like, and it goes forth to the next picture, the amount of pictures still in sequence would be not incremented and the next picture will thus be picture [1/100] until the condition for liking that picture is true, and so forth.

The same would go for pictures that are already liked. I reckon that this would improve how predictable the script may be over a longer period of time.

**Comment by pekapa** [comment]
Just to be sure, if you say to like 100 images, 100 ones should actually be liked, right?

Maybe we should stop collecting links than and just go clicking them on the search page (like a human would do and aligned with the "anti-bot" features)

**Comment by timgrossmann** [comment]
@pekapa The only problem would be how to extract all the information you get from the separate page of each post...

**Comment by maxinedotdev** [comment]
@pekapa Yes, that was my intention.
@timgrossmann We would still be needing the information for each post, so I agree that would still be required.

Another idea could be to optimise the rendering of each page by disabling rendering of images to the browser. While for one user the differences would be miniscule, if one is automating several users on the same machine (especially low-performance devices such as the RPi3), that could increase performance. That is something that I experimented with during automation scripts.

I guess the code itself is not dependent on if there is an image or not, but does the clarifai API care?

**Comment by timgrossmann** [comment]
@hillockink You just send the link to the image to the clarifai API endpoint, so I don't think they care 😉

**Comment by eduardocalazansjr** [comment]
@hillockink since we use chromedriver
1 - We can't disable image rendering, since it's chrome related and it run w/o sandbox
2 - Item 1 wouldn't impact on performance, since the hog on instagram page is JS rendering, pure CPU bound, the problems with RAM are from the development of chrome.
3 - Raspberry PI doesn't work with chromedriver and chrome, they compiled for ARM run pretty slow and google has abandoned the support for this platform

**Comment by maxinedotdev** [comment]
@vlntdds Thanks, I did not know that. Apart from the RAM hog Chrome; that one I am painfully experienced in. Aren't we all.

**Comment by SamuelMTDavies** [comment]
@timgrossmann if we are using the basic quickstart.py code is the Image deemed inappropriate error due to the set_dont_like tags? 

Does the program only have to find part of the tag in the image text to deem it inappropriate? e.g dont_like = ['#porn'] will deem an image tagged #architectureporn unsuitable?

**Comment by pekapa** [comment]
@SamuelMTDavies if you set it to `["porn"]` than it will deem the tag `#architectureporn` to be unsuitable, but its current a work in progress via #211

**Comment by timgrossmann** [comment]
should be fixed by #211 now.
