### ISSUE TITLE
Interacting with a maximum of 27 photos per tag

### ISSUE THREAD

**Issue by balakedev** [InstaPy/InstaPy#1590]
I've seen this issue before but I couldn't find a solution that worked for the account. 

Anyone else experiencing this?

**Comment by imbarismustafa** [comment]
Check this our. https://gist.github.com/uluQulu/35ac02e9ef58e4a6263346e13aa0e7f2/revisions

**Comment by CodeMaster1** [comment]
Yes, I am experiencing this too.

**Comment by balakedev** [comment]
@imbarismustafa no go :/

**Comment by joanroig** [comment]
Same issue here, sometimes are 25, sometimes 27, using this:

` session.like_by_tags(tags, amount=40, media='Photo')`

**Comment by david-vendel** [comment]
It is because how InstaPy is scrapping the Instagram - it is first scrolling through it, they once a lot of posts are loaded, InstaPy gets the posts information.
Instagram is now hovewer only displaying 30 posts at once in it's code. 
So the solution is to be getting posts info (links) while scrolling.
I will try to imlement this now.

**Comment by nocomment-bln** [comment]
@justdvl that would be nice! 

@joanroig I've the same problem :(

**Comment by joanroig** [comment]
@nocomment-bln for now I've set amount=20 and I've increased the number of tags. I need the most accurate amount matching and this seems to do the trick :)

**Comment by david-vendel** [comment]
The solution exists already at discussion #1365
Lets hope it will be merged to master version soon.

**Comment by timgrossmann** [comment]
Should be fixed by #1844
