### ISSUE TITLE
Automate Tests and Continuous Integration

### ISSUE THREAD

**Issue by pekapa** [InstaPy/InstaPy#162]
I was thinking on how we can improve our builds.
Currently we have to manually test for the changes but I believe we could use Travis CI + BrowserStack in order to automate some of that.

Travis CI is free - https://travis-ci.org/
BrowserStack is free for open source projects but they request some additional info -
 https://www.browserstack.com/

**Comment by AlainPilon** [comment]
I thought about it too, but would'nt it be too noticeable if a bunch of IG browser calls came to IG ever X minutes? And I dont see how we can stub (in a reliable way) IG website.

**Comment by pekapa** [comment]
Maybe we can try to stub the critical bits, not the whole of IG

**Comment by eduardocalazansjr** [comment]
The cons:

We depend of Chromedriver and Chrome, binaries of those guys differs from OS to OS, **Travis C**I is useless on this aspect.
We must assert that ALL instagram accounts possibilities are tested, some of users that constantly does PR doesn't test or doesn't have how to test this possibilities, **both** are irrelevant.

A simple checklist would help, since basic functions are not getting tested before doing PR.

**Comment by pekapa** [comment]
>We depend of Chromedriver and Chrome, binaries of those guys differs from OS to OS, Travis CI is useless on this aspect.

That's why we use BrowserStack

>A simple checklist would help, since basic functions are not getting tested before doing PR.

Indeed, a checklist would already be of great help!


>ALL instagram accounts

Do we have access to all the options? I don't.

**Comment by AlainPilon** [comment]
I think that an elegant solution to this issue will be available to us once we extract the browsing commands into the page object pattern. From that point, we will be able to test everything, but the browsing using an integration server. And the browsing could be tested easily on the dev side, since most actions will have no side effects.

**Comment by pekapa** [comment]
@AlainPilon,
Not sure if you're doing any work on that line but I started some rewriting on that line. I shall push to the develop branch later today or tomorrow at the latest.

**Comment by AlainPilon** [comment]
@pekapa go for it, I am sick and can't code for 💩  today and I guess it will be the same tomorrow... But if you follow the page object pattern, it should be pretty easy to follow. Basically the goal is to have a class per page, each possible action the user can perform would be an action and the page instance keeps track of the state of each element on it. 

If you dont want to push your stuff to the main project `dev` branch, push it to your repo and I will check it out there.
