### ISSUE TITLE
Is there a way to only follow post commenters?

### ISSUE THREAD

**Issue by LinasKa** [InstaPy/InstaPy#1659]
Hey,

Maybe someone in this community already made InstaPy to only follow post commenters of the exact username and could share the code?

Thanks!

**Comment by david-vendel** [comment]
Hello, I have some free time so I am writing this now, I will finish soon.

**Comment by david-vendel** [comment]
Hey LinasKa, so far I can get usernames of all the userswho ever commented on given profile:
https://github.com/justdvl/instagram-profilecrawl/commit/5f91dbe7f5ffef12a38abbd727c740a51e7bf192

**Comment by LinasKa** [comment]
Hi justdvl. Thank you for your effort. I checked out your fork and it's great for what I needed it for! Although this could be somehow implemented on InstaPy as a method like follow_user_commenters.

**Comment by david-vendel** [comment]
Hello, I am almost finished with doing exactly that - so far I can follow all the users that commented on my own posts. But if I want to follow users from somebody's esle profile, it keeps crashing or it doesn't work, and I am struggling to find where is the problem.
Let's hope I'll be lucky to figure it out, then I'll fork it here and do pull request too :)

**Comment by david-vendel** [comment]
Actually it works good on my new account and doesnt work well on an old account (maybe I was following too much and Instagram is slowing me down). You can try it how it goes for you.

Add to quickstart.py:
 session.fc('nicknametoget') 

to InstaPy class in file instapy.py copy this code:

    def fc(self, nicknameget):
        print ("running fc")
        self.nicknameget = nicknameget
        user_commented_list = extract_information(self.browser, self.nicknameget)
        print (user_commented_list)
        self.follow_by_list(user_commented_list)
        return self

and at the beginning of this file include:

from .follow_commenters import extract_post_info     
from .follow_commenters import extract_information

and finally to InstaPy/instapy folder add follow_commenters.py, which I attached.
Tell me if it works and maybe someone will be able to help me why sometimes it does and sometimes doesnt. The problem is specifically in scrapping photos, they just wont load at all sometimes.

[follow_commenters.zip](https://github.com/timgrossmann/InstaPy/files/1823162/follow_commenters.zip)

**Comment by david-vendel** [comment]
Actually it seems to be working on 90% of the profiles, only on my new profile ofcoursedavid it doesnt work.
