### ISSUE TITLE
ERROR:upload_data_presenter.cc(73)] NOT IMPLEMENTED

### ISSUE THREAD

**Issue by RafNadler** [InstaPy/InstaPy#1773]
## Expected Behavior
Like images in my feed
## Current Behavior
Error due to chrome version or chrome driver on Win 10.
Chrome version: Version 65.0.3325.181 (Official Build) (64-bit)
Chromedrive: 2.37
Windows 10 64bit

Here is what I get:

DevTools listening on ws://127.0.0.1:12263/devtools/browser/63484a6c-0426-42b6-9cd4-447c756f950d
INFO [2018-03-23 18:03:52] [xxx] Session started - 2018-03-23 18:03:52
WARNING [2018-03-23 18:03:52] [xxxx] Sorry, Record Activity is not working on Windows. We're working to fix this soon!
[12092:14344:0323/180356.558:ERROR:upload_data_presenter.cc(73)] NOT IMPLEMENTED
INFO [2018-03-23 18:04:23] [xxx] Logged in successfully!
[12092:14344:0323/180423.544:ERROR:upload_data_presenter.cc(73)] NOT IMPLEMENTED
INFO [2018-03-23 18:04:26] [xxx] Session ended - 2018-03-23 18:04:26
INFO [2018-03-23 18:04:26] [xxxx] --------------------
## Possible Solution (optional)
Ru it with Firefox ?
## InstaPy configuration
The only action I try to run is like_by_feed at the moment. follow_user_followers works though.

**Comment by SkylimiTY** [comment]
I have the same issue..

**Comment by animetrk** [comment]
Yes it doesn't like feed for the last 2-3 update.

Also don't unfollow active users is not working. It still unfollows people that liked my last pictures.

**Comment by RafNadler** [comment]
Any word on how to fix this ?

**Comment by SkylimiTY** [comment]
@uluQulu any ideas on this one?

**Comment by uluQulu** [comment]
hello @SkylimiTY
_regarding_ the misbehaviour at `like_by_feed` feature, **try** out the working fix by @douwevandermeij at #1782?
in **instapy.py** file
you will **replace**
```python
self.like_by_feed_generator(**kwargs)
```
**with**
```python
for i in self.like_by_feed_generator(**kwargs): 
   pass
```

**Comment by apolo-damasco** [comment]
The issue persist after modifing the file :(

**Comment by mdavis184** [comment]
i have the same problem

**Comment by ortegafernando** [comment]
HI, after last update (today) since 1 month I get lots of NOT IMPLEMENTED messages.
I dont do nothing about like_by_feed , so I don't what is it.

Only follow ONE user: session.follow_by_list(who, times = 1) !!!!

`C:\Users\XXXXX\Downloads\InstaPy-master>python 180328.py
DevTools listening on ws://127.0.0.1:12318/devtools/browser/57b0225e-2981-49e0-9d67-b1acd51b444c
INFO [2018-04-22 19:46:58] [xxxx]  Session started - 2018-04-22 19:46:58
WARNING [2018-04-22 19:46:58] [xxxx]  Sorry, Record Activity is not working on Windows. We're working to fix this soon!
[7584:6388:0422/194700.002:ERROR:upload_data_presenter.cc(73)] NOT IMPLEMENTED
[7584:6388:0422/194700.013:ERROR:upload_data_presenter.cc(73)] NOT IMPLEMENTED
[7584:6388:0422/194701.208:ERROR:upload_data_presenter.cc(73)] NOT IMPLEMENTED
[7584:3904:0422/194729.042:ERROR:connection.cc(1945)] Cookie sqlite error 1555, errno 0: UNIQUE constraint failed: cookies.creation_utc, sql: INSERT INTO cookies (creation_utc, host_key, name, value, encrypted_value, path, expires_utc, secure, httponly, firstpartyonly, last_access_utc, has_expires, persistent, priority) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?)
INFO [2018-04-22 19:47:30] [xxxx]  Logged in successfully!
[7584:6388:0422/194730.968:ERROR:upload_data_presenter.cc(73)] NOT IMPLEMENTED
INFO [2018-04-22 19:47:36] [xxxx]  --> luismasevi
 instagram account is opened...
[7584:6388:0422/194736.666:ERROR:upload_data_presenter.cc(73)] NOT IMPLEMENTED
[7584:6388:0422/194736.696:ERROR:upload_data_presenter.cc(73)] NOT IMPLEMENTED
INFO [2018-04-22 19:47:46] [xxxx]  ---> Now following: luismasevi`

**Comment by uluQulu** [comment]
hi @ortegafernando,
as far as I know, **NOT IMPLEMENTED** errors do no harm, it just points out that some Chrome browser activity is not supported (_not yet implemented_) by chromedriver.
So until you get a crash or a real misbehaviour, just skip worrying those error messages and always try to keep your web browser and it's webdriver at an up-to-date & compatible state

**Comment by ortegafernando** [comment]
Ok, thanks. But what about ?

`[7584:3904:0422/194729.042:ERROR:connection.cc(1945)] Cookie sqlite error 1555, errno 0: UNIQUE constraint failed: cookies.creation_utc, sql: INSERT INTO cookies (creation_utc, host_key, name, value, encrypted_value, path, expires_utc, secure, httponly, firstpartyonly, last_access_utc, has_expires, persistent, priority) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?)`

Thanks

**Comment by uluQulu** [comment]
Welcome, @ortegafernando ,
maybe your cookie is expired. try removing that pickled cookie (_in **logs** folder_), it will rewrite a new one
