### ISSUE TITLE
from selenium.common.exceptions import NoSuchElementException error on GCP Ubuntu 16.04 vm

### ISSUE THREAD

**Issue by nicobts** [InstaPy/InstaPy#1794]
Hi! I'm trying to make Instapy run on an Ubuntu Server. Everything seems to work properly excpet selenium.. I keep on having this error : "from selenium.common.exceptions import NoSuchElementException"

**Comment by wizarduk** [comment]
i have had issues for a while now nothing works use to work but not anymore....

**Comment by liamcloss** [comment]
Please provide the full error messsage.

**Comment by puremilkorwhite** [comment]
Traceback (most recent call last):
  File "quickstart.py", line 5, in <module>
    from selenium.common.exceptions import NoSuchElementException
ImportError: No module named selenium.common.exceptions

**Comment by aymericwp3** [comment]
Hi same trouble here with OS X

Traceback (most recent call last):
  File "quickstart.py", line 5, in <module>
    from selenium.common.exceptions import NoSuchElementException
ImportError: No module named selenium.common.exceptions

And i've already try this pip3 install selenium

Requirement already satisfied: selenium in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/selenium-2.53.6-py3.6.egg

I'm lost

**Comment by puremilkorwhite** [comment]
Somebody made a cleaner instruction but I can't seem to find it as easily. Look for it and try it. If it doesn't work try:

1. Go to folder
~/Projects/InstaPy/instapy/
with file explorer and edit the last line of:  settings.py    to
    chromedriver_min_version = 2.33

2. Make sure your internet connection is stable before you type
echo "deb http://security.debian.org/debian-security stretch/updates main" >> /etc/apt/sources.list

3. Instead of
mv /usr/bin/chromedriver /path/to/InstaPy/assets/chromedriver
try
mv /usr/bin/chromedriver ~Projects/InstaPy/assets/chromedriver
If you get an error, copy the file manually with file explorer.

**Comment by Nicholas0350** [comment]
Getting same error Selenium installed: 

Requirement already satisfied: selenium in /usr/local/lib/python2.7/site-packages/selenium-3.12.0-py2.7.egg (3.12.0)

Traceback (most recent call last):
  File "quickstart.py", line 5, in <module>
    from selenium.common.exceptions import NoSuchElementException
ImportError: No module named selenium.common.exceptions

**Comment by waseem312** [comment]
Getting same error 
ImportError: No module named selenium.common.exceptions

Anyone Please help me on this.
