### ISSUE TITLE
TypeError: sequence item 1: expected str instance, bytes found

### ISSUE THREAD

**Issue by gannicus4431** [InstaPy/InstaPy#1814]
anyone getting this error after a few successful tries?

Traceback (most recent call last):
  File "/Users/Jimmy/InstaPy/quickstart.py", line 35, in <module>
    session.like_by_tags(['natgeo', 'world'], amount=100)
  File "/Users/Jimmy/InstaPy/instapy/instapy.py", line 892, in like_by_tags
    self.logger)
  File "/Users/Jimmy/InstaPy/instapy/like_util.py", line 564, in check_link
    '" in "'.join([iffy, quashed]))
TypeError: sequence item 1: expected str instance, bytes found

**Comment by leon-h-a** [comment]
Yes! Does anyone know how to solve this?

**Comment by rohrz4nge** [comment]
The error occures on my build as well. Tried redownloading the repository but that didn't help.

**Comment by d7laungani** [comment]
I have this issue as well and it seems to occur when foreign keys that trigger it to be represented as hex values instead of being parsed as a string. Examples include emoticons and other languages(like russian) and letters that have accents to it.  

Example Bad Parse: 
`Description: b'\xd0\x9b\xd0\xb5\xd0\xb2 \xd0\xa2\xd0\xbe\xd0\xbb\xd1\x81\xd1\x82\xd0\xbe\xd0\xb9 "\xd0\xa3\xd0\xb1\xd0\xb8\xd0\xb9\xd1\x81\xd1\x82\xd0\xb2\xd0\xbe \xd0\xb8 \xd0\xbf\xd0\xbe\xd0\xb5\xd0\x`

**Comment by nicobts** [comment]
I'm having the same issue too.. I tried to download de repo and reinstall it..  But the problem persists..

**Comment by MrBeardedGuy** [comment]
Might be UTF-8 encoding issue? 
Try adding this code at the very top of both `quickstart.py` and `instapy.py`
```
import sys
reload(sys)
sys.setdefaultencoding('utf-8')
```

**Comment by forgottensword** [comment]
@MrBeardedGuy will this work? I'm having the same issue. Please reply. I'm going to try it out.

**Comment by forgottensword** [comment]
@MrBeardedGuy After applying the above code it says

>   File "E:\Temp\instabot\InstaPy-master\quickstart.py", line 2, in <module>
    reload(sys)
NameError: name 'reload' is not defined

**Comment by gannicus4431** [comment]
I managed to fix it by converting the btye to string in .join:

line 572 of like_util.py

 inapp_unit = 'Inappropriate! ~ contains "{}"'.format(
                quashed if iffy == quashed else
                '" in "'.join([str(iffy), str(quashed)]))

let me know if this works.

**Comment by forgottensword** [comment]
@gannicus4431 .. lemme try that. I'll let you in about 10 minutes

**Comment by forgottensword** [comment]
@gannicus4431 now this error shows up:

> name 'iffy' is not defined

**Comment by craigricker** [comment]
Changing line 564 to the code below will allow the program to continue as normal. This is a hacky workaround, and the root problem should still be fixed. Ensure the indent matches what it was previously. 

`                '" in "'.join([str(iffy), str(quashed)]))`


@forgottensword this is @gannicus4431 's suggested change, just making it clearer that all you do is add two calls to str() conversion. I am guessing your issue is from not making the changes properly.

**Comment by GitNees** [comment]
Same problem :) Was still running an old version, just updated and this started.

PS: Above line fixed it.

**Comment by forgottensword** [comment]
@craigricker I think this is working as of now... Let me get back to you as soon as i finish a test run. BTW your help is very much appreciated. Thank you @craigricker

**Comment by ghost** [comment]
I also have this new error. As everybody get this issue, it's a bug.
It should be fixed ASAP. @timgrossmann

**Comment by GitNees** [comment]
@valentinMebarki pls don't be in the demanding side. This is a community effort. People will look at it. There is a fix ,read and apply it.

**Comment by craigricker** [comment]
@ValentinMebarki a solution to your problem has been posted, and as @GitNees said this is a community effort. You could have taken the time to submit a pull request, in the same time it took you to post that comment. I have submitted [a pull request with this simple change included.
](https://github.com/timgrossmann/InstaPy/pull/1827)

**Comment by ghost** [comment]
@GitNees @craigricker Alright.
I didn't know I could submit a pull request. That's great ! I'll investigate this for future issues.

**Comment by craigricker** [comment]
@ValentinMebarki not a problem, we all have to learn sometime! Since this is a community lead project, it is important for us all to work together, and that includes educating one another.

General workflow if you see an issue/something you want to fix on a community driven/public repo:
1. Fork the repo to your git
2. Go through coding cycle to produce changes.
3. Make sure you document changes well!
4. Once local changes are complete, push to GitHub
5. Submit a pull request to the original public repo. This will then give the project owner/contributors the chance to give feed back, and ultimately accept/reject the changes.

**Comment by ghost** [comment]
@craigricker Thanks for this detailed answer. I'll do that.
