### ISSUE TITLE
Intermittently Works

### ISSUE THREAD

**Issue by wesleytrying** [InstaPy/InstaPy#1821]
## Current Behavior

So, my instapy isn't working all of a sudden and I'm a little confused as to why. I didn't change anything, but when I tried using it at around 9:30, it would log in and find the picture, but would then just log out. It was working all day yesterday too. What can I do to fix this?

## InstaPy configuration

Here is my traceback and as far as it got.

![screenshot 12](https://user-images.githubusercontent.com/36969569/38510959-6a75cd10-3bdb-11e8-82c1-f6c8c6184196.png)

Thank you all for reading and helping!

**Comment by ohio36** [comment]
I read that Instagram has changed it public API. I got the same error, leading to the lines where the script is checking the number of followers in the check_link method in like_util.py. It's not in the graphql data anymore. 

Since I don't really mind the number of followers anyway, I just "fixed" it by commenting out the following lines: 

```
num_followers = browser.execute_script(
            "return window._sharedData.entry_data."
            "ProfilePage[0].graphql.user.edge_followed_by.count") 
```

And replaced it by: 

`num_followers = 50`

Yes, I know. Not really a fix, but it's at least a quick workaround until somebody who knows how to actually fix this the right way. I only use Instapy for likes and comments by the way, and no idea if this workaround is enough to let everything in Instapy run again.

**Comment by bhuiyanmobasshir94** [comment]
Can you please share your quickstart.py file to get better ideas about the solution

**Comment by sionking** [comment]
I don't see any change

**Comment by sionking** [comment]
Anyway try this method:
````
    try:
        followed_by = browser.execute_script(
            "return window._sharedData.""entry_data.ProfilePage[0]."
            "graphql.user.edge_followed_by.count")
    except WebDriverException:
        browser.execute_script("location.reload()")
        sleep(1)
        followed_by = browser.execute_script(
            "return window._sharedData.""entry_data.ProfilePage[0]."
            "graphql.user.edge_followed_by.count")
    # raise exception if number can't be read second time
````

**Comment by wesleytrying** [comment]
I'm sorry, I'm getting back to this so late. But, share my quickstart.py file or were you talking to @ohio36 ?
I'll aslo try that out real quick. That goes in the quickstart.py file, right, @sionking ?
