### ISSUE TITLE
ImportError: No module named selenium.common.exceptions

### ISSUE THREAD

**Issue by KyleTodd** [InstaPy/InstaPy#1822]
## Expected Behavior
After installing InstaPy on Ubuntu 17.10.1 following all instructions, i tried to run quickstart.py but it comes up with this error:
## Current Behavior
`
Traceback (most recent call last):
File "quickstart.py", line 5, in <module>
from selenium.common.exceptions import NoSuchElementException
ImportError: No module named selenium.common.exceptions
`
## Possible Solution (optional)
I have tried running as sudo, changing the chromedriver version in instapy\setings.py and in the assets folder. Have also tried installing selenium directly.
## InstaPy configuration
Default options in quickstart.py except for username and password.

Any help appreciated. Thank you.

**Comment by bloggerpact** [comment]
Try @KyleTodd 

> pip install selenium

Download the updated version of chrome diver and put in assets folder : https://sites.google.com/a/chromium.org/chromedriver/downloads

**Comment by akyzer** [comment]
Hi,

Doesn't work for me :(
Chromediver is in the assests folder..

i tryed this : Go to folder
~/Projects/InstaPy/instapy/
with file explorer and edit the last line of: settings.py to
chromedriver_min_version = 2.33

Make sure your internet connection is stable before you type
echo "deb http://security.debian.org/debian-security stretch/updates main" >> /etc/apt/sources.list

Instead of
mv /usr/bin/chromedriver /path/to/InstaPy/assets/chromedriver
try
mv /usr/bin/chromedriver ~Projects/InstaPy/assets/chromedriver
If you get an error, copy the file manually with file explorer.

but well its quiet exactly the same and still doesn't work..

Any help appreciated too :)

**Comment by johnnelito** [comment]
`python -m pip install -U selenium`

Or replace `selenium` with any module not found in error.

**Comment by frankpitale** [comment]
still not working....damn!
chromedriver installed, but nothing.

**Comment by nicoworq** [comment]
I´m having the same issue. Have you managed to solve it ? Thanks !

**Comment by nicoworq** [comment]
I´ve managed to solve this problem by installing the dependencies with python3

**Comment by xiaowenao** [comment]
@nicoworq which dependencies did you install?

**Comment by nicoworq** [comment]
Try with `sudo apt-get install python-selenium`

**Comment by pakson4** [comment]
@nicoworq thanks for fix it
