### ISSUE TITLE
Theme: disable the info bar in chrome

### ISSUE THREAD

**Issue by sionking** [InstaPy/InstaPy#1862]
Just add it to the chrome options:
chrome_options.add_argument("--disable-infobars")

**Comment by uluQulu** [comment]
Hey @sionking,
It is great I have even thought of removing that annoying banner, too and tried your suggestion which works perfetly
But there is a **drawback** using it (esp. _for mostly Chrome browser users_), **cos** once you have more than 1 Chrome windows opened, **that banner** in that selenium-controller window **reminds you** of _"Hey, it is controlled by selenium! DON'T touch this window! (otherwise, in a new tab opened or navigation to other webpage, selenium will most probably crash out of not finding the requested element)"_

>But I have recently tried latest Firefox browser started by selenium, and I see that **that banner** is shown right in the adress bar. Chrome should also do it, cos that banner captures a big space and sometimes it really is annoying...
