### ISSUE TITLE
[BAN LOG THREAD] Please Record User Bans Here

### ISSUE THREAD

**Issue by AlexBailey** [InstaPy/InstaPy#192]
I think it might be a good idea to create a ban log (in this thread?) so we can see activity getting banned for, for example... Settings used when banned, such as tags liked, messages commented, used Claifai API or not and quantities of each, when the ban was date/timezone, along with the given reason of the ban itself. I think if we can detect trends between bans we might be able to keep one step ahead, obviously do not share your Instagram name in a ban log...

With this said, anyone who has been banned previously, please, if you feel this is useful, log it here with as much details as you can remember.

Let me know your thoughts!

**Comment by littleswany** [comment]
@AlexBailey Great Idea.

I think you get a temporary ban if you like more than 300 pictures in an hour.

I believe that you also get a temp ban if you unfollow/(follow) more than 10 people in an hour also and as such the tool has got this factored in.

**Comment by littleswany** [comment]
#193 @marudon If you want to post your findings here to keep it all in one place.

**Comment by deronsizemore** [comment]
@littleswany more than 10 people in an hour leads to a ban? Is that something very new? I follow way more than 10 per hour and have never been banned.

**Comment by AlexBailey** [comment]
@deronsizemore To be fair with @littleswany I have even heard of this limit myself, I'm certain it's not as low as 10 though, it has been around for a while however.

**Comment by deronsizemore** [comment]
@AlexBailey @littleswany Maybe I've just been lucky. I have four accounts that I actively build and I've never had an issue.

**Comment by littleswany** [comment]
@AlexBailey @deronsizemore The emphasis was on the unfollow limit of 10, I am not certain for following.

From reading around today and on other threads here I believe the limits can changed based on your account which isn't much help to us.

**Comment by deronsizemore** [comment]
@littleswany @AlexBailey Oh, gotcha. I do unfollow as well, but I try to be a little more careful in that regard than I am when following. I was using another service online to unfollow and had it set to 40 per hour with no issue but who knows. I've read all kinds of things in regards to limits and how it depends on how old your account is and all sorts of things.

For following, I have noticed when I follow manually that it seems to depend (maybe?) on when the last time you followed someone was. For example, when I first started I was following accounts like crazy to the point that after about 75 or so, the Instagram app would just stop following people. That's when I knew it was time to slow down. I noticed that over time, let's say that I go a whole week without following anyone and then I start mass following again (manually) that Instagram seemed to allow me to follow much more than the normal 75 or so before they start cutting my following off. It's almost like there's a daily limit and if you don't reach that limit then it (or some of it) carries over? I don't know. All anecdotal evidence of course.

**Comment by sakowicz** [comment]
I didn't used follow/unfollow feature and I've got temporary ban, I can't comment anything. I've changed comment ratio from 25% to 40%.

**Comment by AlexBailey** [comment]
> I can't comment anything

@giebeka Just so we can rule it out, what were the comment contents set to? it wasn't something that would've been marked as spam regardless of volume would it? E.g. linking promotion etc

**Comment by littleswany** [comment]
@giebeka It is possible to get a ban without following/unfollowing. It looks like the increased rate of commenting is the reason. But like @AlexBailey says it would be helpful to know the content of the comments.

**Comment by sakowicz** [comment]
@AlexBailey @littleswany  There were standard comments like _Awesome_, _I like your stuff_ etc. 
It says I'm **temporary** banned from commenting because _comment function_ was used _in too fast way [translated from polish]_

**Comment by littleswany** [comment]
@giebeka Yeah just looks like overuse of the commenting function, I would leave it a little while before using it again and when you do reduce the comment percentage. @deronsizemore Any experience of what works well?

**Comment by AlexBailey** [comment]
@giebeka Sounds like they either mean in ratio you were commenting on content or perhaps field input is tracked in instagramweb? Maybe @vlntdds can shed some light on what he thinks it probably will be

**Comment by deronsizemore** [comment]
@littleswany I honestly don't comment much. If there's something that really catches my attention, I'll comment on it, but I've grown to HATE the "cool gallery, bro" type bot comments and I don't want to leave them on someone else's stream as I feel like it's quite obvious they are bot comments. So all of my comments that I do leave are legit. I have used some bots to like and follow/unfollow before although I do prefer to follow most of the users myself because I can better target who to follow. What's worked well for me is searching a relevant hashtag and then clicking on the recent posts which show "likes" rather than "views" and follow everyone who's liked that post. The thought behind is that hopefully those users had just recently liked that image (since it's a new image) so by you following them, they're likely still online and active on Instagram and will follow you back. Once I reach my follow limit, I'll start unfollowing and then just start the process over again.

**Comment by eduardocalazansjr** [comment]
@AlexBailey i'm still working on it and finding an way out for comments.
Like you said, yeah, it tracks the inputs on the field (not just that field, but in the entire page).

Mixing mouse movements with the keypress and make some typo/erase/write the right comment will avoid that, but if the user do not have a high comment ratio on the app and uses this script with a high % of comments/like it still got flagged and it leads to a temporary ban.

**Comment by atomhax** [comment]
I got a "suspicious activity" email from instagram today and they emailed me a code to enter in the app. I think it's because I had my upper follower limit set very low by mistake (sub 100). I ended up cycling through many many posts without liking or commenting. It's possible that their detection algo is looking for scrapers. In any case it's working fine now when I set the limit back up to around 800.

**Comment by atomhax** [comment]
Do we know if the app can be open while a browser session is going or will that result in a soft ban? I've had a few instances where the auto comment came off as super sarcastic to the point of being rude so I had to kill my session to delete the comment.

Edit: I have to elaborate: It was a post of a failed cake that was totally ruined and the bot commented "wow it's looking great!!!". I couldn't stop laughing.

**Comment by timgrossmann** [comment]
@atomhax I don't really know when it's running for me, so I'm probably online with my phone quite some time when it's running. No problem with that (at least for now).

Haha, had that same problem a few times, even more before I began adding clarifai to the system.
It commented "Soooooo good!" under a picture of a car accident... That was pretty bad

**Comment by razvanilin** [comment]
My bot is commenting "That's awesome" on pictures with naked girls

**Comment by littleswany** [comment]
@razvanilin Thats because the hashtags you have selected have naked girls, if you setup Clarifai you can filter them out.

**Comment by razvanilin** [comment]
@littleswany sorry I used the present tense in the sentence above. I did set up clarifai and it's not happening that often now 😄

**Comment by cazaa** [comment]
@razvanilin I've had the same issue. You should be able to avoid it by setting:

`set_lower_follower_count(limit = 50)`

Accounts posting pictures of naked girls are usually removed by Instagram pretty fast, and before they reach that many followers.

**Comment by littleswany** [comment]
@cazaa Clarifai is the best way of achieving this, setting a lower follower count limit is possibly not advisable for achieving this as it will significantly limit the amount of interactions you have.

**Comment by raulafrosa** [comment]
I have already be soft banned sometimes , I really think that's because of commenting . If its more than 35% they will suspect of your activites .

**Comment by trompx** [comment]
> It commented "Soooooo good!" under a picture of a car accident... That was pretty bad

@timgrossmann what do you think about implementing conditional tags.
For instance only comment if post has "dog" AND "puppy" AND "cute". This could potentially reduce this kind of things to happen. We could apply it to likes too.

**Comment by AlexBailey** [comment]
@trompx Sounds like a good idea, it might also be worth considering that if someones tags are a bit of a niche, they might end up commenting on content that is very old. On my Instagram account I have that occur quite a bit (as a recipient) and it automatically strikes me glaringly obvious that it's a bot. Then again, if the operator is a fool - there's not a lot you can do!

**Comment by wordythebyrd** [comment]
I have the script setup in docker and kicks off around 2AM.  This morning at 7:38AM, Instagram sent me an email, "We detected some suspicious activity that suggests your Instagram account may have been compromised. Don't worry, we've taken measures to secure your account. As a result, we need you to reset your password, using the links below..."  I actually kicked it off at the same time for 2 different accounts and they both had the passwords reset.  This was the first night I've let the task scheduler kick off a powershell script restarting the docker container, rather than running the script manually myself.  For reference, it was going through 30 tags, 30 likes each tag, commenting 15%, following 20%, then unfollows 180 (20% of 900) at the end.  I'm wondering if running the script while I was logged out of the computer had an effect.

**Comment by Jandyk** [comment]
[9484:9488:0217/143527.065:ERROR:broker_win.cc(57)] Error reading broker pipe: The pipe has been ended. (0x6D) 
How I can resolve this error?

**Comment by condomfighters** [comment]
I follow/unfollow around 700 a day, still no ban
idk about shadowban, but i don't think so

**Comment by GitNees** [comment]
@condomfighters for how long already?

**Comment by atwine** [comment]
What would one say are the best settings for follow/unfollow in order not to get suspiciously marked by Instagram? I am quite new at this and just got my account blocked..
