### ISSUE TITLE
How to customize bot login and change tags

### ISSUE THREAD

**Issue by ghost** [InstaPy/InstaPy#1926]
When the bot is working it shows tags like this, how do i change this code in what file, maybe its in instapy.py but i cannot find please help !

`INFO [2018-02-28 13:52:53] [iguser_3332]  Description: b'\xe4\xb9\x85\xe3\x81\x97\xe3\x81\xb6\xe3\x82\x8a\xe3\x81\xab\xe3\x82\xb8\xe3\x83\xa7\xe3\x83\xb3\xe3\x83\x93\xe3\x83\xb3\xe3\x81\xa8\xe3\x83\x92\xe3\x83\xa7\xe3\x82\xaf\xe3\x82\xb8\xe3\x83\xb3\xe4\xbc\x9a\xe3\x81\xa3\xe3\x81\x9f !\n\xe6\xad\x8c\xe3\x81\xa7\xe5\xa7\x8b\xe3\x82\x81\xe3\x81\xa6\xe3\x80\x81\xe6\xad\x8c\xe3\x81\xa7\xe7\xb5\x82\xe3\x82\x8f\xe3\x81\xa3\xe3\x81\x9f\xe6\x97\xa5\xe3\x81\xa0\xe3\x81\xa3\xe3\x81\x9f\xe3\x81\xad \xe7\xac\x91\n\n#\xe6\x97\xa5\xe6\x9c\xac\xe8\xaa\x9e #\xe3\x82\xab\xe3\x83\xa9\xe3\x82\xaa\xe3\x82\xb1 #\xe3\x81\x8a\xe8\x85\xb9\xe3\x81\x84\xe3\x81\xa3\xe3\x81\xb1\xe3\x81\x84 #\xe9\x9f\x93\xe5\x9b\xbd\xe4\xba\xba'
`

**Comment by uluQulu** [comment]
hi @loopypanda,
It is the result of encoding console-unprintable characters into `UTF-8` so that console (_portably_) CAN output string flow without crashing.
 Assume that you have `english` as your system language and `russian` for non-`Unicode` programs,
now your console will print both `english` or `russian` strings properly but when encounters an `arabic` string it will either output `?` or will crash.
 So, if you think you only encounter _readable_ characters in your targets, you can simply remove that encoding phase,
in **like_util.py** file, find this line in `check_link` function and remove `encode(utf-8)` part:
```python
logger.info('Description: {}'.format(image_text.encode('utf-8')))
```
 But for general use, it is prone to crash, cos there are users from different parts of the world with different console encodings, that's why it is staying there.
##### Is there not a way to make it any readable?  
* It can be accomplished by converting language specific letters to its standard pairs in `english` (_console portably language, basically_)
e.g., `russian` word `Хорошо` could be converted to `Khorosho`

_Hope it helps_
