### ISSUE TITLE
Still can't run the script

### ISSUE THREAD

**Issue by supmag** [InstaPy/InstaPy#1950]
## Expected Behavior
Script runs 24/7
## Current Behavior
Won't even load up
## InstaPy configuration
Sorry, Record Activity is not working on Windows. We're working to fix this soon!
 INFO [2018-05-03 05:11:49] [ehsen.sonny] Logged in successfully!
 Traceback (most recent call last):
 File "quickstart.py", line 8, in <module>
 session.set_upper_follower_count(limit = 2500)
 AttributeError: 'InstaPy' object has no attribute 'set_upper_follower_count'

I have th emost basic quickstart setup...and yes I tried removing the upper follower count option from the gui

**Comment by uluQulu** [comment]
hi @supmag,
_have a read this https://github.com/timgrossmann/InstaPy/issues/1941#issuecomment-386045927 for solution_

**Comment by farooqy** [comment]
I had the same problem, even tried to pull updates since these two functions were deprecated but nevertheless, still the same problem. I improvised some solution. Head to the instapy folder and inside the instapy.py file add the code as in the photos:-
![screenshot from 2018-05-14 05-05-45](https://user-images.githubusercontent.com/15178376/39988098-7fbd348c-5734-11e8-95f7-a834c9629270.png)

![screenshot from 2018-05-14 05-02-13](https://user-images.githubusercontent.com/15178376/39987927-0dd3e3ac-5734-11e8-9c55-ea6e4303bd32.png)
 That worked for me.

**Comment by supmag** [comment]
Hu for the solution which part of the file do i input this code?


________________________________

**Comment by farooqy** [comment]
After you have downloaded, you should have the folder named InstaPy, beginning from that folder, follow this path.   InstaPy/instapy/instapy.py

**Comment by supmag** [comment]
Ohhh this is for the follower count, that was fixed when I update the script, I have an issue with "cor! did you send to many requests" its been there for weeks I tried so many things -_-


________________________________

**Comment by uluQulu** [comment]
@supmag,
To get help to solve something you must provide a good feedback but I see no any answer to my questions in your 2nd opened thread https://github.com/timgrossmann/InstaPy/issues/1987#issuecomment-387464034.
