### ISSUE TITLE
Already Liked images

### ISSUE THREAD

**Issue by joaointech** [InstaPy/InstaPy#1994]
Hello, i am trying instapy, but i'm with a problem, when i define like by locations an amount of 50 per tag, when i loop the bot will go to the same posts, so it will give me the same message image already liked because there is not to much people taking photos in that locations, there is another way to scroll more in each interation, or ignore liked posts...
I am trying to do a script with a switch random case loop.
Hope you can help me avoid this issue.

**Comment by sionking** [comment]
Store visited links database.

**Comment by joaointech** [comment]
How do i do that? @sionking

**Comment by uluQulu** [comment]
Hi guys,
@joaops95,
For the ease of modifications, you can use this approach:
1. Get the possible posts amount per that location (_located inside `entry_data` script_) to avoid misbehaviours once you request more amount than possibly existing...
2. Add a sufficiency block to that method, so that if the amount is not filled it will try again with scrolling more
3. For `2`nd step behave cleverly, store the overall scroll count in a variable so that when the amount is not filled, it should scroll more than previous attempt
> You might need to add new parameters to pass and return from the method to the link grabber definition, conditional statements and simple iteration will handle the rest :)

**Comment by sionking** [comment]
@uluQulu there is issue with locations and tags with very few posts, since you can access the same posts over and over again, wasting precious automation time.

Storing instagram links is very easy using sets, so search is a o(1).
Store the set in pickle file on disk and load it on init, move to next tag/location until it will reload with new posts!

**Comment by uluQulu** [comment]
@sionking,
_Diving into storing externally it will end up having huge files after certain amount of activity and even then will even cause slight lags having compared againist huge data (well, file can be reset after some time but it is odd to this idea)_
I believe that there are less tags having less updated content that average user interacts with and sufficiency loop will be requested in those rare situations, even there could be break time handler added...
> And yes, if a user KNOWS that total tags has less pictures (_rarely updated feed_) and still wants to interact with it repeatedly, well it is a problem, an unefficiency problem.

Your suggestion is robust I totally agree with but I aim for simplicity and having less resources consumed possible..
You like pickling a lot, ain't xD

**Comment by sionking** [comment]
@uluQulu I like easy solutions, I have no knowledge in DB but I am one it to learn.
But take this scenario:
tag has 50 posts.
you want 25.
you take first 25. no scrolling.
tomorrow  you have 55 so you take the first 5 and 20 more from yesterday.
already like X 20 times!
now you scroll for more...
Loop it every day, you will end up looping too many times and getting already like (xpath not found == 15 sec !!! for each already like)

conclusions: no other option!
save 5000 links, it will be the best (use sets it hashing the links to search very fast).
1 MB is not to much those days.

**Comment by uluQulu** [comment]
So true, @sionking,
It is an inefficiency problem in first hand user side.
But it can happen in many cases, e.g., sometimes you pick lots of tags without checking the size of content in there and you use the same list many times repeatedly.
That's why this scenario must be handled.
You are right about delays and wasted time `already liked` attempts
What about just storing the number of scrolls externally for pages with less content?
But it will not be robust solution cos the update of content in pages has a fuzzy algorithm.
At this point I think it should be the best for storing links in your suggestion and it will be robust and also fast after sorting them.
It still must be improved, cos in a few weeks or months the links storage will fill hundred of thousands elements.
I think it is best to store pages with less than e.g. 100k or 300k content.
There pops out another issue:
Say you don't want to get the link of already liked content but what about when you want to follow but not like, it will not take that content again (_will affect features requesting other features for functionality_)
How do you think about this?
In which features link matching should be applied and in which scenarios?
And it can be, storing content in monthly basis and after e.g. 2 or 3 months passed remove that month and its elements, so that file size grows dynamically...
kind of, `{2018//05:[link1, link2], 2018/06:[link1, link2, link3]}` ...
JSON can be used but it is error prone, DB can also be used for reliability

**Comment by sionking** [comment]
I already implemented my simple solution storing all links (using sets) and pickling it (I am a FW guy, pickle is the way we do it in FW also (kind of lol))

**Comment by uluQulu** [comment]
cool @sionking,
what does FW stand for? :P

**Comment by joaointech** [comment]
Guys I have been thinking on a way to get past this: 

I was thinking about using a database to store urls and make the script search for it for validation: if he should take that link or not by making a query to that database.

If not, the script would move to the next url until it finds a url that doesn't exist in the database and go perform a like/comment to the post.

My questions is if this is a possibility and how can I achieve it? I've only made very small changes to the script and I'm unfamiliar with functions that are retrieving the page elements (like url).

Thanks.

**Comment by sionking** [comment]
@joaops95  look at my comments ....
@uluQulu FW==Firmware== C coding and working with ASIC.

**Comment by uluQulu** [comment]
that's great @sionking,
It is an advanced industry but serialization for python, ehm, lots of python pioneers adviced pickling to be highly inefficient technic, although, it would be completely different in C
DB engine like SQLite is very easy for that purpose considering the ease of well-defined structure to be used efficiently
It is an amazing language btw, I am learning C++ for systems programming :P

**Comment by redsector72** [comment]
@sionking 
I'm interested in your implementation. Have you done a Fork already?

**Comment by sionking** [comment]
Mmm I can post it here but PR is too hard for me since my repo is completely diffrent than original instapy

**Comment by redsector72** [comment]
Better than nothing :)

**Comment by joaointech** [comment]
Yeah it would be great!
