### ISSUE TITLE
New to the game, need some looking for some basic help.

### ISSUE THREAD

**Issue by S4nderr** [InstaPy/InstaPy#2041]
## Expected Behavior
Is there a way to run this script faster? I am now so looking for some tips.

## InstaPy configuration

```python
    # settings
    session.set_relationship_bounds(enabled=True,
				 potency_ratio=0.30,
				  delimit_by_numbers=True,
				   max_followers=1000000,
				    max_following=1000000,
				     min_followers=500,
				      min_following=1)
	
    session.set_user_interact(amount=3, randomize=True, percentage=100, media='Photo')
    session.set_do_follow(enabled=False, percentage=0)
    session.set_do_like(enabled=False, percentage=100)
    session.set_comments(["Cool", "Super!"])
    session.set_do_comment(enabled=False, percentage=0)
    
    

    # actions
    session.interact_user_followers(['DJKhaled'], amount=250, randomize=True)
```

**Comment by ShiftingKill** [comment]
You can speed up time between actions if that's what you mean:
Change page_delay (a few scrolls down in instapy(home folder)\instapy\instapy.py).
Add session.set_sleep_reduce(*InsertPositiveIntegerWithinParenthesis*) to instapy.py, on top or below any other session.*...
As far as I know this works, get a timer ready and benchmark it and keep changing values, Instagram's limit is about 2000 likes a day.

**Comment by imjustin** [comment]
If what you mean by faster is that the script as a whole takes a long time, I think that's because of the interact_user_followers. It seems to take the most time for me because in order to work it has to load all the images from a given person first, and then it randomly selects some images to like/comment on. It's that act of loading that takes a long time, because you're gated by your internet connection. 

try using a different action and see if that helps?
