### ISSUE TITLE
New confirmation msg show when unfollow!

### ISSUE THREAD

**Issue by sionking** [InstaPy/InstaPy#2187]
I forgot to capture but this fails the unfollow.
not always shown!

**Comment by CharlesCCC** [comment]
Can you please provide a screen-shot what is looks like ?

**Comment by sionking** [comment]
Pop-up window, we need to catch it when failing to unfollow.

**Comment by sionking** [comment]
![image](https://user-images.githubusercontent.com/7851877/41054201-6561ca7c-69c6-11e8-8396-88eeeeb13f0a.png)

**Comment by sionking** [comment]
I have it stopped (locky me getting telegram msg when unfollow not working!)

**Comment by sionking** [comment]
/html/body/div[3]/div/div/div/div[3]/button[1]

**Comment by sionking** [comment]
the unfollow confirmation

**Comment by CharlesCCC** [comment]
uhh, good catch, we will need add this to the part of unfollow function.

**Comment by sionking** [comment]
<button class="aOOlW -Cab_  " tabindex="0">Unfollow</button>

**Comment by sionking** [comment]
Can someone give me proper xpath to use ? kind of button with text eq to Unfollow?
I am bad at this :(

**Comment by jeremycjang** [comment]
@sionking  This is based off of the few mins/maybe one hour I read about xpath after seeing this PR lol

```
(//button[contains(@class ,'aOOlW -Cab_')])[1]
```
?

I noticed your original was an absolute path; I opted to try a relative path.  

Used a few assumptions here:

1.  There is only one button on the page with the class attribute value set to ```aOOlW -Cab_``` and as such it's the "first" button on the page with that value (because you wrote button[1] in your original)

2. I used the xpath ```contains()``` function because I wasn't sure if the spaces in the tag you presented are part of the actual class or if they're a typo

I'm testing it right now and will let you know as soon as I see a success or failure!

Cheers 🍻 

Update: Followed pool sample size wasn't large enough to trigger the confirmation box 😅  will have to continue testing to confirm results

**Comment by jeremycjang** [comment]
Update: My xpath didn't work. Trying the more general ``` //*[contains(text(), 'Unfollow')] ``` using the pattern of pre-existing code tomorrow.

**Comment by dgursh** [comment]
Hi, this xpath works. Just make sure you put sleeps above and below so it gives the dialog box enough time to load.

@timgrossmann 
@jeremycjang 
@sionking 
```
unfollow_button = browser.find_element_by_xpath(
                    "//*[contains(@class, '-Cab_')]")
unfollow_button.click()
```

**Comment by jeremycjang** [comment]
@dgursh can you clarify the sleep amounts you’ve used to make this code work with the dialog box load time? Currently testing this setup after ```sleep(2)``` in the first sleep proved to not be enough:

```
try:
logger.info('we might have gotten a confirmation request')
 sleep(5)
unfollow_button = browser.find_element_by_xpath("//*[contains(@class, '-Cab_')]")
 sleep(2)
 unfollow_button.click()
```

**Comment by dgursh** [comment]
Here is my code, I've placed it in the section where you unfollow each user from their own account page, since that's where I've seen the confirm box appear. I am using a sleep(2) after the follow button is clicked, and then again once I confirm the follow button text still says "following" (meaning the dialog box has appeared. Then I search for the unfollow button and then click unfollow.

Hope this helps 

@timgrossmann 
@jeremycjang 

```
               browser.get('https://www.instagram.com/{}'.format(person))
                sleep(2)
                follow_button = browser.find_element_by_xpath(
                    "//*[contains(text(), 'Follow')]")

                if follow_button.text == 'Following':
                    unfollowNum += 1
                    click_element(browser, follow_button) # follow_button.click()
                    sleep(2)
                    # If diaglog pops up confirm
                    if follow_button.text == 'Following':
                        sleep(2)
                        unfollow_button = browser.find_element_by_xpath(
                    "//*[contains(@class, '-Cab_')]")
                        unfollow_button.click()
                    logger.info('--> Ongoing Unfollow ' + str(unfollowNum) +
                          ', now unfollowing: {}'
                          .format(person.encode('utf-8')))
                    sleep(15)
                    if hasSlept:
                        hasSlept = False
```

**Comment by aleeepp** [comment]
Hello, i got a new clone master,  but Its not working , I have the same problem, is it work for yor?

**Comment by jeremycjang** [comment]
I confirmed @dgursh 's code worked; thank you!

**Comment by aleeepp** [comment]
@jeremycjang @dgursh , can you please pass the unfollow_util.py ??, I try but Its not working for me.

**Comment by jeremycjang** [comment]
@sionking @timgrossmann  Should we add this to the master to check for confirmation boxes? I think it'll have to be modified now to fit with the most recent ```unfollow_util.py``` code
