### ISSUE TITLE
Is possible to save the console output to file?

### ISSUE THREAD

**Issue by redsector72** [InstaPy/InstaPy#2237]
I've tried to follow some googling, but seems like it is not possible to save the console output to a file.
Is there a method to either save the output to a file or to generate a log that contain the errors?
I get the script, from time to time, that stop randomly. From the log I see it reached the session end correctly, so I suppose it's a kind of bug, but I can't reproduce it as I have not the console output.
I'm on a mac, headless and with cron.

**Comment by uluQulu** [comment]
Hi @redsector72 
There is a `logger` for InstaPy which prints most of the messages and all of them are saved at **general.log** file at **logs** folder.

But the messages printed with `print` function  are on the fly. And those messages are no so much, cos almost every printer line uses `logger` instance.

Here is the thing:
It will be great to revise every printer line to see if it needs to be printer with `logger` so that it can save those messages in **general.log** file **OR** if the message is not important (_e.g. `--------` kind of messages_) then keep it with `print` function.

It is what I understood from your Title.

But if you like to get the crash messages from console, you have to do something exclusive. Cos those crash messages are not printed by the Instapy `logger` so they can't be saved by default.

Instead you can do some stuff, e.g.
+ direct the console output to some file (_it will save every message in there: from `logger`, `print` function or other from `stdout`_)
+ or direct only the error messages (_possible `Exception`s thrown, etc._)

Regards

**Comment by marcomokastyle** [comment]
If you're using a Mac, in the terminal window you can press ctrl+s and will save the output as a txt file (not everything but at least a big part of it)
