### ISSUE TITLE
send the logs to a data base

### ISSUE THREAD

**Issue by CamiloB** [InstaPy/InstaPy#2268]
## Expected Behavior

Hi i know there are about 9 diferrent logs for insta.py, i want this logs send it to a data base to then use this data to generate a report

## Current Behavior

there is a path  Instapy/logs/myaccount/ 

i this path i have 9 txt files 

general.log

myaccount_followedpool.cvs

myaccount_record_all_followed.cvs

myaccount_record_all_unfollowed.cvs

fallowed.txt

fallowednum.txt

## Possible Solution (optional)

i want to send the 

fallowed.txt
and 
fallowednum.txt
and 
general.log

to a data base how can i do that?

thanks a lot

**Comment by marcomokastyle** [comment]
What kind of database are you thinking of? followerNum.txt and followingNum.txt are simple text files, but general.log can be long, even more than 10mb. Are you sure that you need also the log file? what part of this log do you need? I'm asking, because, maybe, you can use a different approach, like made some changes in the code and export what you need in a much suitable way, like JSON. Or if you don't need complex data structure maybe a CSV file is just fine.

**Comment by CamiloB** [comment]
@marcomokastyle  hi im thinking on sqlite, so how i send those .txt files to the data base?, plus i already found a data base on the instapy is located on InstaPy/db/instapy.db but i don't see to much info about how to handle this statadistics report

**Comment by marcomokastyle** [comment]
@CamiloB what  do you want to do? do you have an idea of what you want to store in the database?
have an idea of the structure of the tables? that's the most part. Once you have in mind this, just insert a record/s in the desired table.

**Comment by CamiloB** [comment]
@marcomokastyle  hi thanks a lot for the replies, i dont know to much about data bases i just know that you can record the progress of the instapy on a data base, sorry for not knowing to much about this, i want to have a stadisttics of how the instapy works in my account, something like se the growth of followers and see the list of the people instapy followed, i want to use this data to send it on my web page and show a graphic on real time how the bot its working. do you get me?

**Comment by marcomokastyle** [comment]
@CamiloB I'm thinking about a solution, at least how to do that. By the way, if you want use it with a web site, maybe sqlite is not the best option, could be a better solution using MySql. Maybe on a remote server. In other words, InstaPy, write the db already on a remote server instead of a local one. On your website you can query directly the db. And export whatever you want.

This could be a nice feature. I don't know if right now I'm capable of doing it, but indeed is a very good idea!

**Comment by CamiloB** [comment]
@marcomokastyle  so when your tell me this " InstaPy, write the db already on a remote server instead of a local one. " your talking about this file InstaPy/db/instapy.db ? and i can acces if from anywhere if this .db is on a server ?

**Comment by marcomokastyle** [comment]
@CamiloB No. This is another thing.  At the moment this functionality does not yet exist, what i'm saying is an approach to take, to implement this feature. 
At the moment, instapy.db should contain this data in the table statistics:
likes,comments,follows,unfollows,server_calls,created

but is a **local** database, for your needs I thinks could be better using a MySQL remote database.
I'm not saying that you have to implement this, but I'm looking for a good solution to this problem.

**Comment by CamiloB** [comment]
@marcomokastyle  ok thanks a lot ill going to search to, if i can do something ill tell you thanks a lot again
