### ISSUE TITLE
possible posts: 0

### ISSUE THREAD

**Issue by baaswietse** [InstaPy/InstaPy#2358]
I get this error when searching for tags to like. This randomly appeared.

![image](https://user-images.githubusercontent.com/40791418/42242512-6246d8f2-7f0e-11e8-901a-1714152a625d.png)

**here is my quickstart.py:**

_import os
import time
from tempfile import gettempdir

from selenium.common.exceptions import NoSuchElementException

from instapy import InstaPy

insta_username = 'XXX'
insta_password = 'XXX'

session = InstaPy(username=insta_username,
                  password=insta_password,
                  headless_browser=False,
                  multi_logs=True)
	
session.login()
'''session.set_skip_users(skip_private=True, skip_no_profile_pic=True, min_media=25)
session.set_do_comment(True, percentage=10)
session.set_comments(['aMEIzing!', 'So much fun!!', 'Nicey!'])
session.set_dont_include(['friend1', 'friend2', 'friend3'])
session.set_dont_like(['pizza', 'girl'])'''

session.set_relationship_bounds(enabled=True,potency_ratio=0.90,delimit_by_numbers=True,max_followers=5000,max_following=2000,min_followers=200,min_following=100)
session.set_do_follow(enabled=True, percentage=100, times=1)    						# Follows 100% of the picters looked at
session.set_user_interact(amount=3, randomize=True, percentage=100, media='Photo')		# Like posts based on hashtags and like 3 posts of its poster
#session.set_dont_unfollow_active_users(enabled=True, posts=5)							# Prevents unfollow followers who have liked one of your latest 2 posts

session.like_by_tags(["l4l","likeforlike","like4like"], amount=50)
unfollow_after=48*60*60, sleep_delay=600) #2dagen

    # end the bot session
session.end()_

**Comment by HansDaigle** [comment]
1. Change skip_private=`True` to skip_private=`False`.
2. Try to like more commun tags session.like_by_tags(["travel","love","food"].

The issue here is that you are filtering the possible post that you can like to 0.

**Comment by baaswietse** [comment]
I'm sorry, that part of the code was commented out. Should have deleted it.
But the l4l tags have like 140.000.000 possible pictures, so I don't get why it gives me no possible posts.

**Comment by roquestre** [comment]
It also happens to me.

0 possible posts for a common tag like follow4follow @timgrossmann

**Comment by wyvers** [comment]
I'm seeing the same thing. It looks like it's pulling the number of possible posts from the webpage itself. The bigger tags don't list the number of posts on for that tag. Smaller ones do.

If you search for like4like it shows hundreds of millions in the search bar but when you click on to the actual tag page, it doesn't show. A smaller tag say like4likes shows around 24 million in the search bar and when you click to the page it also shows the same number. It looks specific to like4like

like4like: https://www.instagram.com/explore/tags/like4like/ (Does not display total number of posts on the page, so skipped)
Love: https://www.instagram.com/explore/tags/love/ (does show total number of posts, not skipped)

I'm wondering if the script looks at the page, see's no total number of posts and skips it because of this. Is Instagram specifically trying to kill bots from using these tags?

**Comment by giulioco** [comment]
I'm also seeing this issue

**Comment by lyori6** [comment]
> I'm also seeing this issue

same
