### ISSUE TITLE
Modify User Agents for advanced Instagram features

### ISSUE THREAD

**Issue by tibor** [InstaPy/InstaPy#236]
Instagram is pushing its efforts to make more features available via smartphone browsers as well (combined with the recent added offline functionality I personally think they are going to launch a PWA anytime soon).

At the moment some accounts can [upload photos via the web interface with an iPhone User Agent](https://petapixel.com/2017/05/06/post-photos-instagram-desktop-browser/) but more features may be added.

Maybe we should keep this in mind and think about setting UA strings in InstaPy as well.

**Comment by atomhax** [comment]
I noticed that my account has the features enabled from my smartphone browser. What Features need to be explored? Often i'll take a dozen photos and want to upload them at regular intervals instead of all at once. I think it could be an interesting feature if the bot would poll a folder for new images and related text. If there is new content it would post every "X amount of hours". 

Part of my motivation for this is gaming the "Instagram algorithm" which apparently favors users who post at least once a day. This is a second-hand unverified claim.
