### ISSUE TITLE
Auto updater for InstaPy

### ISSUE THREAD

**Issue by tibor** [InstaPy/InstaPy#237]
To make sure that all InstaPy users are using the newest version we should think about a simple auto updater via `git pull` (maybe also as a opt-in or opt-out solution).

I think with a growing number of features and pull requests this will bug tracking and resolving issues easier.

**Comment by timgrossmann** [comment]
@tibor Yes, I think this is a nice idea.

**Comment by wizarduk** [comment]
is this now a feature?

**Comment by timgrossmann** [comment]
@wizarduk Nope, haven't been implemented yet,

**Comment by dkbast** [comment]
@wizarduk I implemented this in my scheduling script - as long as there are no breaking changes this should work fine :-) 
@tibor I believe this could be put in the example scheduling script, rather than adding a "feature" - InstaPy's number of features is already growing quite (too) fast for the documentation to keep up.
