### ISSUE TITLE
Too few images, skipping this tag: usopen

### ISSUE THREAD

**Issue by bardascat** [InstaPy/InstaPy#2397]
Hi,

Sometimes the bot enters in this loop, saying the it can't find any new images for my hashtags.

I'm pretty sure that there are plenty of post with hashtag "usopen", so I was wondering if you guys have any experience with this behaviour ?
Is this happening when you have a bad internet connection and the images are not loaded (just the placeholder is visible) ?

Do you know if this behaviour is caused by an instagram block? 

Thanks

**Comment by ianmonat** [comment]
I experienced this too today, the hashtags I entered have hundreds or thousands of images but I keep getting the message, 'Too few images, skipping this tag', please help!

**Comment by JSdotPY** [comment]
The same problem also appears to me - but only when using Proxy Servers - is this a common problem?

I also have set the self.browser.implicitly_wait(self.page_delay) to 100 as described in #41 https://github.com/timgrossmann/InstaPy/issues/4 . But still the problem persists.

INFO [2018-09-11 21:22:24] [maennertagebuch]  Tag [1/15]
INFO [2018-09-11 21:22:24] [maennertagebuch]  --> b'trust'
INFO [2018-09-11 21:26:16] [maennertagebuch]  Too few images, skipping this tag

#trust
9.078.772 Entries found on Instagram.

Thanks for sharing your insights.

**Comment by bardascat** [comment]
Hi,

By increasing the wait should work. I think the problem is bad internet
connection and the images dont load properly.

**Comment by JSdotPY** [comment]
@bardascat Thanks for your fast reply - have set the waiting to 1000 - will post my findings here.

**Comment by bardascat** [comment]
Maybe you should try changing the proxies if they are too slow

**Comment by bardascat** [comment]
Also if i remeber corectly, the code will try to scan for images for a
certain amount of times( maybe 3 times) after that, if nothing is found it
will pause for a few minutes and then try again.

If you don t like the pause You can increase the number of tries.

**Comment by JSdotPY** [comment]
@bardascat thank you very much.

It turned out that I made a mistake in the configuration of the proxy, as I provided a port as if I would use it in Chrome directly. As it turns out this is not necessary when using the chrome driver such that the IP by itself was sufficient (I am using IP whitelisting for authentification)

One might want to think about changig the log to be more percise, as the messages that I got were:
1) Login Successfull
2) Not enought images
As my connection was not set up correctly - the login by itself should not have worked initially.

But nevertheless everything works again by now.
Cheers
J
