### ISSUE TITLE
Unable to unfollow

### ISSUE THREAD

**Issue by condomfighters** [InstaPy/InstaPy#2398]
## Expected Behavior
Unfollow
## Current Behavior
not unfollowing
## InstaPy configuration
I just updated instapy and i get this error when i try to unfollow users.
I copy pasted the logs folder to the updated instapy and get this error

```
INFO [2018-07-09 14:12:54] [igaccount]  Please select a proper unfollow method!  ~leaving unfollow activity

INFO [2018-07-09 14:12:54] [igaccount]  --> Total people unfollowed : 0
```

This is the script i use
```
from instapy import InstaPy

insta_username = 'meme machine'
insta_password = 'wtfboi'

session = InstaPy(username=insta_username, password=insta_password)
session.login()
session.unfollow_users(amount=1000)
session.end()
```

**Comment by zheskiel** [comment]
try this one:

`session.unfollow_users(amount=1000, allFollowing=True, style="FIFO", sleep_delay=450)`

**Comment by condomfighters** [comment]
@idpelago Thank you!

**Comment by jseps** [comment]
@idpelago that line has been giving me "TypeError: unfollow_users() got an unexpected keyword argument 'allFollowing'"

until roughly 10 days ago I was using `session.unfollow_users(amount=30, onlyNotFollowMe=True, sleep_delay=60*10)` with no issues, but since then the code has been running and saying it's unfollowing but having no actual effect

**Comment by jseps** [comment]
@idpelago that line has been giving me "TypeError: unfollow_users() got an unexpected keyword argument 'allFollowing'"

until roughly 10 days ago I was using
session.unfollow_users(amount=30, onlyNotFollowMe=True, sleep_delay=60*10)
with no issues, but since then the code has been running and saying it's unfollowing but having no actual effect

session.unfollow_users(amount=30, sleep_delay=450)
returns NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//div[text()='Following']/following-sibling::div"}
(Session info: headless chrome=xx)
(Driver info: chromedriver=2.38.552518 (183d19265345f54ce39cbb94cf81ba5f15905011),platform=Mac OS X 10.11.6 x86_64)

instapy version is 0.1.dev0

**Comment by zheskiel** [comment]
then you can try this one
`session.unfollow_users(amount=1000, sleep_delay=450)`

**Comment by rubinho101** [comment]
new parameters: `session.unfollow_users(amount=20, nonFollowers=True, style="RANDOM", unfollow_after=3*60*60, sleep_delay=655)` works for me.
