### ISSUE TITLE
like_back?

### ISSUE THREAD

**Issue by sunnypatel165** [InstaPy/InstaPy#241]
If I supply an image URL with say, 100 likes, and out of these 50 are from people I don't follow. 
Will it make sense to add a function in which a fixed number of pictures of such people(who liked your pic without you following them) are liked back?
The liked pictures maybe first N or 1,3,5,7... N or any random N pictures!

I observe that a lot of times like-backs eventually result in a mutual follow relationship. 
At the same time, to avoid spam/fake accounts we can still use the lower_limit to say like only if that person has >=1000 followers.

Views?
Thanks, 
Sunny.

**Comment by tibor** [comment]
Have thought about this feature as well and I think this would be great.

Correlates also with issue #70.

**Comment by sunnypatel165** [comment]
Okay. If already a WIP, might as well close this one!

**Comment by atomhax** [comment]
Correct me if I'm wrong but AFAIK this is currently NOT possible with the desktop user agent. I wasn't able to get it to work with the UA set as Safari iOS 9 agent either but I didn't do too much experimenting. From a browser after 11 people like an image it changes to a counter and theres "likes" page to go to. 

Instagram API has a way to get a list of users who liked a certain media.

**Comment by timgrossmann** [comment]
@atomhax Yes, this might be possible in the future or maybe with some JS magic... 

Well Instagram API has some nice features, but please let's keep staying away from that 😉

**Comment by atomhax** [comment]
@timgrossmann I can try and conjure up some of that magic. I wonder if a var on the page is holding the list of the users somewhere.

You're right about the Insta api.. seems like that might draw unwanted attention. Not sure why I even brought it up.

**Comment by patrickdundas** [comment]
> Well Instagram API has some nice features, but please let's keep staying away from that 😉

Can't help but reiterate the point here... As soon as we start relying on the Instagram API for features this project will crash and burn in API hell just like so many companies and projects have already. The reason this project is special to me is because it doesn't touch the API, and uses "humanlike" input methods, which is really the only successful way to safely interact with Instagram long-term. Let's keep it that way, and keep coming up with the creative solution to interacting with Instagram in our own way! 😄
