### ISSUE TITLE
link_elems error Message: stale element reference: element is not attached to the page document

### ISSUE THREAD

**Issue by ghost** [InstaPy/InstaPy#2437]
Hi there,

someone else has the same error ?

INFO [2018-07-16 22:10:14] [xxx]  Total of links feched for analysis: 8
ERROR [2018-07-16 22:10:14] [xxx]  link_elems error Message: stale element reference: element is not attached to the page document
  (Session info: chrome=67.0.3396.87)
  (Driver info: chromedriver=2.40.565383 (76257d1ab79276b2d53ee976b2c3e3b9f335cde7),platform=Linux 4.9.103-xxxx-std-ipv6-64 x86_64)

Thanks

**Comment by marcomokastyle** [comment]
@ilmetu I had a similar issue, I think the solution is handle StaleElementReferenceException reload from xpath, and check again, this issue happens when for some reason the element is not attached yet, or maybe with javascript removed. 
my problem was in get_links_for_username, but I think is almost the same error, I solved the issue using something like this:
```python
        try:
            links = [link_elem.get_attribute('href') for link_elem in link_elems
                     if link_elem.text in media]
        except StaleElementReferenceException:
            sleep(1)
            link_elems = main_elem.find_elements_by_tag_name('a')
            try:
                links = [link_elem.get_attribute('href') for link_elem in link_elems
                         if link_elem.text in media]
            except StaleElementReferenceException:
                links = []
```

more info here: https://docs.seleniumhq.org/exceptions/stale_element_reference.jsp
