### ISSUE TITLE
What to do when there is an update?

### ISSUE THREAD

**Issue by victorsandovalmattar** [InstaPy/InstaPy#2504]
Hello friends. Instagram updates are becoming more often. Everytime that happens InstaPy needs to be updated also. So I would like to know from you what to do when it happens? Do we need to reinstall InstaPy everytime it happens or there is an easier way? @uluQulu @tibor @CharlesCCC can you help us  a help?

**Comment by Areahints** [comment]
Usually when Instagram updates, users make the necessary changes and push to repo so that you and I can update and use accordingly, in the case of the latest changes, several users are already pushing different updates. As a user all you need to do is pull those latest changes and you will be fine.

**Comment by victorsandovalmattar** [comment]
Thanks a lot for the reply @Areahints, but how do I pull the latest changes?

**Comment by Areahints** [comment]
You use `git status`  to show the status of current branch
`git checkout master` makes sure you are on master branch too
`git stash` saves your edits such as the various quick config files 
`git fetch --all` gets the latest commits
`git reset --hard origin/master` overwrites all but your edited files
`git pop` brings back your edits saved with the git stash command

Ideally , you want to run git status every few days and then git reset hard origin. You can also automate the process in a bash script

**Comment by Mehran** [comment]
@Areahints can you explain more about it ? for Example i `git clone` fresh repository , now edit `quickinstall.py` file  , now from master repository some part of file `quickinstall.py` has been change .
Now i `git stash` to save my changes , and then` git pull` to update it .  now i want bring back my changes to file `quickinstall.py` ,  i use `git stash pop` but i see Conflict Error .

**Comment by CharlesCCC** [comment]
@Mehran I suggest you use google more often than just asking here. most answer are out there and easy to find. 
@Areahints great instruction, If you have time, would you please add this to the wiki page as part of the tutorial ? thank you.

**Comment by Areahints** [comment]
@Mehran you can name the `quickstart.py` file to `Instagramname.py` i.e my Instagram name is Areahints, so I changed my `quickstart.py` to `areahints.py` then I run it with `python areahints.py`  also I never said `git stash pop` it's `git stash` and then `git pop`
@CharlesCCC I will do that, thanks

**Comment by Mehran** [comment]
@Areahints Thanks yes but `git pop` not work

```
git pop
git: 'pop' is not a git command. See 'git --help'.

Did you mean this?
        log
```

also if i add new file it will be Untracked File and how can update them ?

**Comment by michaelBielang** [comment]
as already mentioned, also this question google hit number one helps ;)

**Comment by victorsandovalmattar** [comment]
@Areahints so, every now and then I have to type all the commands you told above?

**Comment by Areahints** [comment]
Yes, for me I automated it with a cronjob, so every 3 days I have a bash script that cd into InstaPy folder and run `git pull origin master` updates are taken care of automatically cos I am not always online

**Comment by victorsandovalmattar** [comment]
That's amazing @Areahints!! would you teach us how to do that?

**Comment by victorsandovalmattar** [comment]
Well... maybe not... Thanks anyway for all the tips @Areahints

**Comment by CharlesCCC** [comment]
@victorsandovalmattar google is your friend my friend. 
if you can't google it, there are two things we can help here. 1st, we can google it for you; 2nd, if can't find the answer from google, then we can work it out and teach you how to do it.   (1st option should always give you 95% the anwer tho)  :)

**Comment by Areahints** [comment]
```
#!/bin/bash

# Clear InstaPy logs
cd path/to/InstaPy/logs
rm -rf Instagam-folder-name instagram-folder-name-2

#Check for updates and install 
cd
cd path/to/InstaPy
git pull origin master
```
this is my bash script that auto updates InstaPy and also deletes the logsfrom the instapy folder, i discovered that when i had too many log files, InstaPy kept crashing.

You want to replace the url of `path/to/InstaPy/logs` to point to your own InstaPy folder location, you also repeat the same for `path/to/InstaPy`, `rm -rf Instagam-folder-name instagram-folder-name-2` is a command to delete the folders found in the instapy logs you will change the `Instagam-folder-name` to the name of the folder you find in there, which is usually your instagram handle.

I named my script as clear.sh, but you can name it anything you want, however when you do name it, you create a cronjob that will run the script once a day or based on however you want it to run

my cron entry looks like this
`0 23 * * * ./clear.sh`

after writing your script you can always test by first running the script in terminal with ./nameofscript.sh if all goes well, the folder created in the logs of instapy will be deleted and any recent updates will be merged. it goes without saying that if you want to use this method, you should rename quickstart.py to a unique name.py so that during the update your config wont be overwritten.

I hope this is informative, i really am not online most of the time and it saves me a lot so i don't mind sharing!

**Comment by victorsandovalmattar** [comment]
@CharlesCCC you've been saying that a lot lately... If that is the only contribution you can give, just save it for yourself and let who wants to help do the job. Would you please friend?

**Comment by CharlesCCC** [comment]
@victorsandovalmattar If you have been to this community longer enough, you should know by now. the same answer have been given numerous times.  great people like @Areahints is generous enough to show you everything which is highly appreciated.  and you my friend, should not take this as granted. people here are to learn and to help each other, if you don't have the willing to learn by yourself, there is no point to teach. I hope you find this helpful. thanks. time is limited to everybody.

**Comment by victorsandovalmattar** [comment]
@Areahints that is awesome! Thanks a lot for the great help you've been giving for everyone new here! You could have been doing as our "collaborator" that just collaborates telling people to search google, but instead, you are really bringing us value! I am really grateful for what you have done. Teaching is the best way to get better and better at what you do!

**Comment by uluQulu** [comment]
Hey guys
This is a good question:

#### What to do when there is an update?
### **A1**  
It is a **general** _question_ regarding it's a `git` & **Github** process.
It's true, searching the web will answer ALL of the questions to you and will clear your mind much better than the answers we can give cos web contains the advanced explanations and solid understanding.  
But sometimes, we find it hard to search with the right term, that is understandable, in that case.  
Here are the ways you can update a Github repo:
**1** - using powerful `git` commands 😎 (**super** method)
**2** - using Github Desktop application (_made with Electron so is ultra portable and platform independent software and is **SO** useful_) 😊 (**recommended** method)
**3** - redownloading (_the ZIP_) **OR** recloning the repo from the repo's homepage 😂 (**do only when wants to reset**)
**4** - applying the changes of the new commits manually 😀 (**truly difficult** method)
_Now you have the terms to search the web for each method._

### **A2**  
It is an InstaPy **specific** _question_.
True, it also has a piece of InstaPy specification cos your are updating **it**.  
Alongside you have learnt how to do update a Github repository, you should know some more bits.  
+ **additions**: Well, while you do install InstaPy do start working, there will be some files made inside the logs folder by the program. Those are gonna be called **unstaged** files by the `git` so you don't need to touch them while updating the repo, cos the _unstaged files_ never make a conflict.  
+ **modifications**: there will be only one file modified by the program which is - **instapy.db** database file. And you should know that `git` cannot continue to pull the new changes once there is a **modified** file unlike **unstaged** files. So you have to hide that database before pulling new changes.  
That's where `stash` & `pop` commands come to help.
#### The **good news** is I have prepared a new set of revisions which is gonna make **instapy.db** file written by the program from scratch WHERE it will no more make a conflict ☄ again.  
>After the change I told above, you will just not need `stash` & `pop` commands anymore, just will `pull` flawlessly 🤩.

**EXTRA**: Above I have considered you have not modified the source files and you have a **quickstart** file else than default sample **quickstart.py**.  
If you have modified any of those files, then, you will have to **always** stash the changes before pulling, the pop and solve the possible conflicts by hand.  


For you @victorsandovalmattar, let the challenge be learning to solve conflicts, cos in future you may want to have modifications in the source files (_e.g. **like_util.py**_) and also want to pull the new changes from the main repo whilst keeping your existing changes 🛶.

If you have a question about using `git` commands, just [**bing**](https://www.bing.com/) it.  
Or, if you have a InstaPy specific question, let us know 🙌

@CharlesCCC is a great man, keep up the good work!
I am sorry for late reply, @victorsandovalmattar, but I have too less time nowadays and you're right, teaching is really making the knowledge fresher. 
Also, @Areahints, I think removing **logs** folder or the files inside it is not so good or at least to recommend others, cos it contains lots of useful information which is gonna be used by the program.  
>E.g. the files inside **relationship_data**, **blacklist.csv**, follow **pool CSVs**, etc are highly **crucial** files to be kept BUT e.g. **general.log** file which is for only informative purposes can be **backed up** (_optional_) and **resetted** from time to time if it gets so huge.


Cheer 😁

**Comment by kukkakeppi** [comment]
Hi all!

I am completely new here and I have tried to learn to use InstaPy - in which I succeeded a few weeks ago. 

I just wanted to say thank you to all of you. With your guidance and help, even this 31-year-old Finn learned to modify code 👍

**Comment by bianpratama** [comment]
When I first started to use InstaPy, I cloned the repo using Github Desktop application (to keep track of the changes) and manually download the zip and store in my own private repo. Everytime there is an update, I pull the update in Github Desktop and look for the changes, and manually copy-paste them to my repo.

It was time-consuming and error-prone. So, I tried to learn about git branching, merging, and remote. That was when I discovered this issue. Thanks to @Areahints, finally I really make use of `git stash`, `reset` and `pop` 😁 

For now, my method of managing InstaPy usage is:
- **New branch with difference remote**. I Create new branch in the cloned InstaPy repo to track my modified version. Then I add new upstream remote to this new branch to connect with my private repo (still learning about forking 😁).
- **Merging workflow**. When there is an update in the main repo, I `git checkout` to master branch, do `git pull`, then `git checkout` to my branch, and do `git merge master`.
- **Custom folder**. I make new folder to store the DB and logs file (and using `multi_logs=True`), so that it is not conflicted with updated instapy.db. Also, I duplicate and rename the DB file for each accounts I manage. For the logs file, I know that it just doesn't make sense to put the logs in folder other than **logs**. I just want to put all of them in the same place.
- **Setting variables**. I also add setting variables to my quickstart file, so that it stores the data to respective file and DB:
```python
from instapy import Settings

BASE_DIR = os.path.dirname(os.path.abspath(__file__))

Settings.log_location = os.path.join(BASE_DIR, 'newfolder')
Settings.database_location = os.path.join(BASE_DIR, 'newfolder', insta_username+'.db')
```
- **Additional files**. For additional files, e.g. hashtag files and custom functions (like the one I use in #2515, assisted by @uluQulu 😄) I just put it in the root folder.
- **Respective account's folder**. I plan to store every account-related files (quickstart, hashtag, DB, and logs) to its respective account's folder. And make new folder to store custom function files.

@uluQulu, I don't know if my method above will be conflicted with your planned set of revisions. But sure I will try to adapt 👊 

Pardon my sporadic method, I just want to share what I'm using. In case, anyone can make use of it or give advice on how to improve it 🙏

**Comment by meinert** [comment]
Found a lot of inspiration in this thread on how to use Git. 

What I currently do, which almost fullfill all my needs is:

Forked the repository.

Now in my forked repository I have master which is my "save habour". 

When ever there are changes in timgrossmann:master that I want to use I create a branch in my repo and creates a pull requst to pull the commits from timgrossmann:master to the branch in my own repository. When these changes have been tested I create a pull requst from the branch to my master.

This works fine. I have logs and the db file in my own folder and have made my own set of startup scripts thus I never get a merge conflict with any of these files.

My only issue is when I want to contribute with some new features or corrections of errors. When I have made the changes and want to send them to a branch in timgrossmanns repo I create a pull requst in timgrossmanns repo. But all the "private" scripts that I have in my own repo is also committed to the pull request.
How should I handle this? As far as I know there are no funtion to omit files from a pull requst. Seen different workarounds, but not very elegant which imply that there must a better way to handle this.

**Comment by CharlesCCC** [comment]
@meinert  Have you tried to add your own private script to the `.gitignore` file ?
In addition, I really like your approach about manage branch and feature, thus you don't need worry about having issue when there is a bad merge or anything.

**Comment by bianpratama** [comment]
@meinert,

I also wanted to learn about forking, but not yet get the time do it. When I do, I will try to use your workflow of managing branch and feature.

Out of curiosity, I checked your forked repository. IMHO, I think you need to change your Instagram password cause it's all over the repo 😅

**Comment by Areahints** [comment]
> My only issue is when I want to contribute with some new features or corrections of errors. When I have made the changes and want to send them to a branch in timgrossmanns repo I create a pull requst in timgrossmanns repo. But all the "private" scripts that I have in my own repo is also committed to the pull request.
How should I handle this? As far as I know there are no funtion to omit files from a pull request. Seen different workarounds, but not very elegant which imply that there must a better way to handle this.

@meinert 

- if you want to push a contribution, for example you updated something in `docker-compose.yml` and you want to share with the community,

- the first step is to ensure your branch is updated to the remote by running `git pull`, if you miss this step an issue might occur where you are trying to update the remote but the remote already is ahead of yours.

- `git status` will show you the files you've edited, in this case `docker-compose.yml` will be highlighted under this statement

> Untracked files:
  (use "git add <file>..." to include in what will be committed)
docker-compose.yml

- the next step is `git add docker-compose.yml` this will tell git that this file is ready to commit

- next you run git `git commit -m "added a new feature to docker-compose.yml"` the statement `"added a new feature to docker-compose.yml"` must be something that explains what your changes is about, this helps the main contributors to understand and test the files faster.

- the last step is `git push`  with this your commit is uploaded to the remote and you can now refrence it in an issue

of course this only works if you're allowed to contribute technically otherwise you'll get a 
>remote: Permission to timgrossmann/InstaPy.wiki.git denied to `username`.
fatal: unable to access 'https://github.com/timgrossmann/InstaPy.wiki.git/': The requested URL returned error: 403

i also created a repo of git commands i actively use and will be maintaining this repo, you can check it out https://github.com/Areahints/Git-Commands

hope this helps!
