### ISSUE TITLE
Follow, like or comment if post matches more than one hashtag

### ISSUE THREAD

**Issue by arisanguinetti** [InstaPy/InstaPy#270]
Hi everyone,

I see that many posts in Instagram have more than one hashtag, it would be great to be able to like, comment or follow based on matching more than one tag.

For example, I want to like, comment and follow to all Instagram posts that have both hashtags "#beer" and "#texas". It's more likely to find posts with a hashtag combination than by using a hashtag like "#BeerInTexas"

**Comment by ogerasymenko** [comment]
Hello. To not create new topic, write here. My ideas about InstaPy - will be good to add feature to skip Top Posts liking, because when we specify some tag, first of all happens liking this (Top) post; second - will be not bad to have some common features, for example get user followers list. I try to work with official  instagram python api and have permanent troubles with api_token (I'm not understand how to generate it).

**Comment by webdevandeverythingelse** [comment]
Any movement on this issue? I also entered a feature request for this same thing, doing only compound hashtags which match all the hashtags (not just one)
