### ISSUE TITLE
BUG:  follower count == 0 we not checking condition

### ISSUE THREAD

**Issue by sionking** [InstaPy/InstaPy#2715]
since:
```
 if followers_count:
                    if max_followers:
                        if followers_count > max_followers:
                            return False, \
                                "User {}'s followers count exceeds maximum limit  ~skipping user\n".format(username), \
                                   return_values_dist
                    if min_followers:
                        if followers_count < min_followers:
                            return False, \
                                "User {}'s followers count is less than minimum limit  ~skipping user\n".format(username), \
                                   return_values_dist
```

when followers_count == 0 we skip the first  if followers_count

Solution:
followers_count is not None or following_count is not None

@uluQulu @timgrossmann  ? I am not sure here

**Comment by sionking** [comment]
same for following

**Comment by sionking** [comment]
This is the only thing I hate with python you never sure what the IF condition will return...

**Comment by uluQulu** [comment]
Yes @sionking 
Funnily while writing it, all of the statements were using hardcore checking with `==` and `is None` rather than cooler `if sth:` but cos of there ended up too many expressions like that and the code was looking so bulky 😂
So I rewrote those expressions using that cooler way before sharing the changes...
And that particular piece seems to be affected off cool code 😀 in your case.

BTW it only affects the minimum values cos, user defined maximum values cannot be negative.

Also I think it was written at early times where I didn't know the **booleanic** power of `0` and `1` 😎.

Yet there is a new PR coming from @marcomocastyle which seems to have changed some bits in that definition while bringing a few new parameters.
I think it is best to edit it in his PR (_active_) or wait it gets merged then apply the changes.


-------

Cheers 😁
-----

**Comment by sionking** [comment]
I start liking the way you check conditions == is much safer, all other unpredictable "is None" "if sta:" and so are very confusing in Python for non pythonic ppl.
@uluQulu
