### ISSUE TITLE
Make InstaPy Language Independant

### ISSUE THREAD

**Issue by timgrossmann** [InstaPy/InstaPy#28]
#### Right now, InstaPy only works if your Instagram language is english. Make sure it works with any language (or at least, most)

- [x] change check if already likes from "Like" to something more generic
- [x] make sure there are no other areas of language problems

**Comment by eduardocalazansjr** [comment]
The comment is working perfectly because of the text inside the field.

Instead of turning everything to an language independent solution, why can we just use the chromedriver locale flag pointing to the en-US language?

Check my comment under https://github.com/timgrossmann/InstaPy/pull/31#issuecomment-292020518
