### ISSUE TITLE
ERROR Message: unknown error: DevToolsActivePort file doesn't exist

### ISSUE THREAD

**Issue by fgisslen** [InstaPy/InstaPy#2810]
I thought I had solved this but apparently not.
Any ideas @uluQulu ?

python3 ~/InstaPy/5b8878183e1f010014e23a76.py
ERROR [2018-08-31 07:15:09] [xxx]  Message: unknown error: DevToolsActivePort file doesn't exist
  (Driver info: chromedriver=2.41.578700 (2f1ed5f9343c13f73144538f15c00b370eda6706),platform=Linux 4.15.0-33-generic x86_64)
Traceback (most recent call last):
  File "/home/fredrik/InstaPy/instapy/instapy.py", line 305, in set_selenium_local_session
    chrome_options=chrome_options)
  File "/home/fredrik/.local/lib/python3.6/site-packages/selenium/webdriver/chrome/webdriver.py", line 75, in __init__
    desired_capabilities=desired_capabilities)
  File "/home/fredrik/.local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 156, in __init__
    self.start_session(capabilities, browser_profile)
  File "/home/fredrik/.local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 251, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/home/fredrik/.local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 320, in execute
    self.error_handler.check_response(response)
  File "/home/fredrik/.local/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: DevToolsActivePort file doesn't exist
  (Driver info: chromedriver=2.41.578700 (2f1ed5f9343c13f73144538f15c00b370eda6706),platform=Linux 4.15.0-33-generic x86_64)

Traceback (most recent call last):
  File "/home/fredrik/InstaPy/instapy/instapy.py", line 305, in set_selenium_local_session
    chrome_options=chrome_options)
  File "/home/fredrik/.local/lib/python3.6/site-packages/selenium/webdriver/chrome/webdriver.py", line 75, in __init__
    desired_capabilities=desired_capabilities)
  File "/home/fredrik/.local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 156, in __init__
    self.start_session(capabilities, browser_profile)
  File "/home/fredrik/.local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 251, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/home/fredrik/.local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 320, in execute
    self.error_handler.check_response(response)
  File "/home/fredrik/.local/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: DevToolsActivePort file doesn't exist
  (Driver info: chromedriver=2.41.578700 (2f1ed5f9343c13f73144538f15c00b370eda6706),platform=Linux 4.15.0-33-generic x86_64)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/fredrik/InstaPy/5b8878183e1f010014e23a76.py", line 13, in <module>
    session = InstaPy(username=insta_username, password=insta_password, headless_browser=True, nogui=True, multi_logs=True, bypass_suspicious_attempt=True, proxy_address=proxy, proxy_port=port, page_delay=100)
  File "/home/fredrik/InstaPy/instapy/instapy.py", line 193, in __init__
    self.set_selenium_local_session()
  File "/home/fredrik/InstaPy/instapy/instapy.py", line 309, in set_selenium_local_session
    Settings.chromedriver_location))
instapy.instapy.InstaPyError: ensure chromedriver is installed at /home/fredrik/InstaPy/assets/chromedriver

**Comment by dpashutskii** [comment]
Noticed that error today's morning.

**Comment by uluQulu** [comment]
@fgisslen @guar47 
How frequently you encounter that issue?

------

Cheers 😁
--------

**Comment by fgisslen** [comment]
I would say once a week maybe. I thought I hade fixed it with chrome_options.add_argument('--disable-dev-shm-usage') but apparantely not.

**Comment by uluQulu** [comment]
@fgisslen 

I would need more details from you to suggest a total solution.
Note that that problem is a bit controversial and can be caused off several problems:
+ Memory issue in Chrome side [at `/dev/shm`] AND since that argument does not work, it means,
either the problem is elsewhere OR it cannot handle the low memory
+ virtual Display has not started yet [in `nogui=True`]
+ etc.

Can you give this feedback?
- When you  started to see that error?
- Do you have any clue of after WHAT or in what condition it could start?

In any case, I can offer a trivial solution if you like.
1-) Put blocks in your quickstart script into a **function**
2-) Catch exceptions, if it contains that keyword, do some logic 


-------

Cheers 😁
-------

**Comment by fgisslen** [comment]
@uluQulu yes, have to try that.

**Comment by fgisslen** [comment]
@uluQulu it starts when the script starts. Like session or login or something like that

**Comment by uluQulu** [comment]
@fgisslen 
Can you verify if it DECREASED the crashes of that sort after adding that argument to disable `dev-shm-usage`?
If so, then you should increase the `/dev/shm` size to handle much better. And at that case it is a problem of Chrome implementation which cannot be handled by its chromedriver.

I really think adding a personal crash handler for those kinds of [errors] BECAUSE those bugs are in the Chrome suite for years and has yet neither FULLY defined NOR provided an end-to-end solution.

-----

Cheers 😁
------

**Comment by fgisslen** [comment]
@uluQulu
I think it happens less often after adding that, yes.

What is /dev/shm and how to increase it? 😅

**Comment by uluQulu** [comment]
@fgisslen 
`/dev/shm` is a location exclusive to Linux (_and maybe MacOS?_) for Chrome

Thanks to the @issuj & @elgalu for sharing,
https://github.com/elgalu/docker-selenium/issues/20#issuecomment-132967581;
https://github.com/elgalu/docker-selenium/issues/20#issuecomment-133011186;
_Although you do not use docker, those comments should help you_.



----------

Cheers 😁
-------

**Comment by fgisslen** [comment]
@uluQulu 
Then I have to remove “disable dev-shm usage” right?

**Comment by fgisslen** [comment]
@uluQulu
But it happens even after I disabled the usage. But probably less often

**Comment by uluQulu** [comment]
Right @fgisslen 
I'm a bit sleepy.

Use it increasing its size.

**Comment by SchDen** [comment]
Check it and next comments. It's helped me:
https://github.com/timgrossmann/InstaPy/issues/2748#issuecomment-416246072

**Comment by fgisslen** [comment]
@SchDen thx, I use that though.

**Comment by fgisslen** [comment]
@uluQulu 
I used this line to improve the dev shm, what do you think?
sudo mount -o remount,size=8G /dev/shm

**Comment by fgisslen** [comment]
@uluQulu even if it didn't appear as much today as yesterday it dit appear.
What do you think about adding https://github.com/timgrossmann/InstaPy/issues/2362#issuecomment-405241751 
and 
https://github.com/timgrossmann/InstaPy/issues/2362#issuecomment-415909174
?

**Comment by imikeh** [comment]
Hi all, I cannot solve this problem too lol.
My program works fine today, I had been running it over 2 days but today evening ...
it happened this error. 
Most of the error is
unknown error: DevToolsActivePort file doesn't exist
and
unknown error: Chrome failed to start: crashed (chrome not reachable)

I try to resize the /dev/shm seems is not working

**Comment by fgisslen** [comment]
@imikeh I have solved this problem here https://github.com/timgrossmann/InstaPy/issues/2841

**Comment by imikeh** [comment]
@uluQulu 
For me, it just happened this issue by itself. I run my code around 2 days and just found out it 
show this error two hour before, and cannot fix it now.

**Comment by fgisslen** [comment]
Check the thread I posted. There you will solve it @imikeh

**Comment by imikeh** [comment]
Hi @fgisslen , any suggestion of the version? latest one?
But just confused why this happened, I mean so there is a bug inside it, or 
when will it happened lol

**Comment by fgisslen** [comment]
@imikeh it seems that chromedriver bugs and it is a know issue. Use the latest chromedriver on the link I posed on https://github.com/timgrossmann/InstaPy/issues/2841 .
It has a fix of that bug. Just download the correct one for you OS.

**Comment by imikeh** [comment]
@fgisslen gotcha, thanks bro. 
No idea why this is not happening in the beginning, I mean I did successfully run my code for roughly two days.

**Comment by imikeh** [comment]
I still get this error
`
selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally
  (Driver info: chromedriver=2.36 (7165af0ca9863529f28e493568ae3d105eddcdef),platform=Linux 4.1.12-112.14.10.el7uek.bug27766149.x86_64 x86_64)
`
in my code
```python
def get_driver():
    options = webdriver.ChromeOptions()
    options.add_argument('--headless')
    options.add_argument('--no-sandbox')
    options.add_argument('--disable-dev-shm-usage')
    driver = webdriver.Chrome(executable_path="/usr/bin/chromedriver", chrome_options=options)
    return driver`
```

I did put the chromedriver under /usr/bin and also chmod 777 to it.
My $PATH is
`-bash: /usr/lib64/qt-3.3/bin:/bin:/usr/bin:/usr/dev_infra/platform/bin:/usr/dev_infra/generic/bin:/usr/local/bin:/usr/X11R6/bin:/usr/local/ade/bin: No such file or directory`

And with this update chromedriver, not sure but it runs longer time to get the error msg

**Comment by imikeh** [comment]
@fgisslen  @uluQulu 
Do you know how to solve the wrong version of my chromedriver?
Thanks

**Comment by fgisslen** [comment]
That one works for me 🤨

**Comment by launganik** [comment]
I tried the following and nothing works:
1. Increasing space in /dev/shm
2. Adding the following
`options.addArguments("--disable-extensions"); // disabling extensions
options.addArguments("--disable-gpu"); 
options.addArguments("--no-sandbox"); // Bypass OS security model
options.addArguments("--disable-dev-shm-usage"); // overcome limited resource problems
options.setExperimentalOption("useAutomationExtension", false);
options.addArguments("--disable-setuid-sandbox");`
P.S. I specifically do not want to make it headless
3. Using chromedriver 2.38 and 2.39
4. Using chromedriver-electron
5. Using Chromium instead of Chrome

I'm working on a remote machine, Ubuntu 18.04 LTS. Can anyone please help me here? My selenium java tests work perfectly fine on windows 10 remote + jenkins but gives me the "devtoolsactiveport file doesn't exist" error on ubuntu 18.04 remote + jenkins.

**Comment by eespitiarea** [comment]
@launganik, you can go to https://github.com/electron/electron/releases, there you can select the proper chromedriver version for your use case. For me version 3.0.7 was the ideal.

**Comment by launganik** [comment]
@eespitiarea I tried 3.0.7 and 4.0.0, both don't work

**Comment by eespitiarea** [comment]
@launganik, would you mind sharing a bit more info about your use case to see if I would be able to help?

**Comment by launganik** [comment]
I need to run some selenium tests every 8 hrs (I use Jenkins). I need to run them headfully. Currently they're being run in parallel (max 5 chrome instances) on Amazon Workspaces (win10) and I need to migrate them to Ubuntu LTS 18.04 server which I access using a Remote Desktop Connection. This is because the top CPU configs available on workspaces are not able to handle more chrome instances. 

The requirement is to run more test suites all running parallely, all headful, using 3-5 instances each, making it around 15-20 independent chrome instances running in parallel at any given time.

The problem is when I try to start tests in ubuntu's Jenkins instance, it shows me the DevToolActivePort error (unless I make it headless). I've tried things mentioned in [my comment above](https://github.com/timgrossmann/InstaPy/issues/2810#issuecomment-430225514). I am open to any solution that fulfills the above requirement - suggestions to fix the issue, move to another infrastructure, run tests in a fundamentally different way, etc. Suggestions welcome from @eespitiarea and others :)

**Comment by eespitiarea** [comment]
@launganik Based on the input, reminds me of a dependency related issue I faced some time ago, please review https://bugs.chromium.org/p/chromedriver/issues/detail?id=2470 about setting up xvfb, you can still take screenshots from a virtual display. Additionally, I would suggest you to try Chromedriver Canary version or consider a managed grid, probably Browserstack.
