### ISSUE TITLE
'unfollow_users' doesn't work when logged in using email id

### ISSUE THREAD

**Issue by Nocturnal-2** [InstaPy/InstaPy#2870]
## Issue
Minor one. 'unfollow_users' doesn't work when logged in with email id in 'insta_username'

## Log

INFO [2018-09-07 16:29:11] [loginemailid]  Starting to unfollow users..
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
INFO [2018-09-07 16:30:11] [loginemailid]  Failed to get followers count of 'loginemailid'  ~empty list
INFO [2018-09-07 16:30:50] [loginemailid]  Unfollowing the users followed by InstaPy

INFO [2018-09-07 16:30:50] [loginemailid]  Retrieving live `Followers` data of loginemailid at "full" range
INFO [2018-09-07 16:31:50] [loginemailid]  Failed to get followers count of 'loginemailid'  ~empty list
INFO [2018-09-07 16:32:40] [loginemailid]  Failed to get following count of 'loginemailid'  ~empty list
ERROR [2018-09-07 16:32:40] [loginemailid]  Sorry, an error occured: Message: unknown error: Cannot read property 'entry_data' of undefined
  (Session info: chrome=68.0.3440.106)
  (Driver info: chromedriver=2.40.565498 (ea082db3280dd6843ebfb08a625e3eb905c4f5ab),platform=Windows NT 10.0.17134 x86_64)

**Comment by CharlesCCC** [comment]
for quick fix, why not try login as username ?

**Comment by Nocturnal-2** [comment]
@CharlesCCC Yes, did it! Thank you! Just bringing it to attention.

**Comment by uluQulu** [comment]
@CharlesCCC @Nocturnal-2 
_It made me think this_,
We use the provided username as `self.username` and pass it everywhere WHICH is fine.
But user might enter email address (_or ID_) instead of username.
And I see 2 requirements to be fulfilled here:
**1**- add a **new parameter** to hold email
_e.g._,
```python
def __init__(self,
                 username=None,
                 email=None,   # NEW PARAMETER
                 password=None,
                 nogui=False,
```
**2**- in that scenario where user did not provide username, then **go get username** and assign it to `self.username`

---------

Cheers 😁
------
