### ISSUE TITLE
If your account doesn't follow any people, unfollow will crash #Bug 

### ISSUE THREAD

**Issue by MoritzGruber** [InstaPy/InstaPy#290]
In file unfollow_util.py
```python
browser.get('https://www.instagram.com/' + username)

following_link_div = browser.find_elements_by_class_name('_218yx')[2]
```
If follow 0 people that following_link_div is undefined and will crash.
In the browser you can see that this div doesn't exist, there is just a span element instead.

How should the bot act in this case? I feel like just give a warning and return 0 for the number of unfollows.

**Comment by timgrossmann** [comment]
@MoritzGruber You are right! This should be fixed...
If you think about submitting a PR, feel free to do so.

Just make sure to not only catch this problem but also abort the whole unfollowing process if something like that happens since it will continue until the whole "amount" of people has been unfollowed 😉

**Comment by MoritzGruber** [comment]
Yeah I will submit a PR soon :+1:

**Comment by timgrossmann** [comment]
#295
