### ISSUE TITLE
follow_user_followers, interact_user_followers error - due to mismatching validation...

### ISSUE THREAD

**Issue by EduardKov** [InstaPy/InstaPy#2904]
## Current Behavior
INFO [2018-09-12 05:40:09] [***]  Follow per user: 1  |  Total Follow: 1
INFO [2018-09-12 05:40:09] [***]  Ongoing Follow [203/1776]: now following 'lyubov_bryutova'...
INFO [2018-09-12 05:40:12] [***]  User: lyubov_bryutova >> followers: 130  |  following: 7500  |  relationship ratio: 0.02
INFO [2018-09-12 05:40:12] [***]  User lyubov_bryutova's following count exceeds maximum limit  ~skipping user
WARNING [2018-09-12 05:40:12] [***]  --> Simulated Unfollow 1: unfollowing 'lyubov_bryutova' due to mismatching validation...

## InstaPy configuration
    session.set_quota_supervisor(enabled=True, sleep_after=["likes", "comments_d", "follows", "unfollows", "server_calls_h"], sleepyhead=True, stochastic_flow=True, notify_me=True,
                              peak_likes=(57, 1120),
                               peak_comments=(21, 182),
                                peak_follows=(48, 1000),
                                 peak_unfollows=(35, 1000),
                                  peak_server_calls=(490, 4700))
    session.set_relationship_bounds(enabled=True,
				 potency_ratio=None,
				  delimit_by_numbers=True,
				   max_followers=2000,
				    max_following=800,
				     min_followers=None,
				      min_following=None)
    spisok2=['rica_stom','olgasmile.ru']
    session.set_user_interact (amount=random.randint(2,3), percentage=100, randomize=False)
    session.set_do_like (enabled=True, percentage=100)
    session.set_do_follow (enabled=True, percentage=100, times=1)        
    session.set_blacklist(enabled=True, campaign='***')        
    ###
    session.follow_user_followers(spisok2, amount=100000, randomize=False, interact=True)

**Comment by Nocturnal-2** [comment]
I couldn't find set_quota_supervisor in the repository. Is this is a old version of InstaPy?

**Comment by EduardKov** [comment]
> I couldn't find set_quota_supervisor in the repository. Is this is a old version of InstaPy?

https://github.com/timgrossmann/InstaPy#quota-supervisor

**Comment by Nocturnal-2** [comment]
I am sorry, for some reason I couldn't find it in the repository this morning when I searched through Github web interface.

**Comment by uluQulu** [comment]
@EduardKov 
It is a simulated unfollow rather than an error.
Simulated follows happened through the dialog box cannot validate the user [through relationship bounds] and it does it once visiting its profile after leaving the dialog box.  
And there if that user is not valid, then it directly unfollows it- called simulated unfollow.

If you do not want to use simulations, you can easily disable it (_read on simulations in **README**_)

-------

Cheers 😁
---------

**Comment by EduardKov** [comment]
@uluQulu
The point is that at this stage the process is frozen
I waited 5 hours, but he did not continue to work

**Comment by uluQulu** [comment]
I see, @EduardKov 
You should note it in the name of thread so that we could get it solved more quickly

Let's troubleshoot it **now**!

#### How frequently it does happen?
+ **always**, **sometimes** [how often?], **daily**, **hourly**, **idk** [check?], **many times** [how many?], etc., 😉

_happen = [it does freeze the process for that long time]_

--------

Cheers 😁
---------

**Comment by MelleNi** [comment]
The same happens to me **every** run. It then practically stops and has to be manually closed and restarted. It takes less than an hour to occur each time, often below half an hour.
