### ISSUE TITLE
Timed out with failure while explicitly waiting until visibility of element located!

### ISSUE THREAD

**Issue by MasonLyons** [InstaPy/InstaPy#2905]
## Expected Behavior
Account should be logged in

## Current Behavior
The account isn't logged in and ends with the wrong login data error message. When I login to the account in a web browser it asks me to confirm that this login was from me but even after accepting I still can't login with the account using the bot.

## InstaPy configuration
import os
import time
from tempfile import gettempdir

from selenium.common.exceptions import NoSuchElementException

from instapy import InstaPy

insta_username = 'X'
insta_password = 'X'

# set headless_browser=True if you want to run InstaPy on a server

# set these in instapy/settings.py if you're locating the
# library in the /usr/lib/pythonX.X/ directory:
#   Settings.database_location = '/path/to/instapy.db'
#   Settings.chromedriver_location = '/path/to/chromedriver'

session = InstaPy(username=insta_username,
                  password=insta_password,
                  headless_browser=True,
                  multi_logs=True)

try:
    session.login()

    # settings
    session.set_relationship_bounds(enabled=True,
		delimit_by_numbers=True,
		max_followers=1000,
    )
    session.set_do_comment(True, percentage=15)
    session.set_comments([u'X', u'X'])
    session.set_dont_include(['friend1', 'friend2', 'friend3'])
    session.set_dont_like([
        'X'
    ])

    # actions
    session.like_by_tags([
        'X'
    ], amount=20
    )

except Exception as exc:
    # if changes to IG layout, upload the file to help us locate the change
    if isinstance(exc, NoSuchElementException):
        file_path = os.path.join(gettempdir(), '{}.html'.format(time.strftime('%Y%m%d-%H%M%S')))
        with open(file_path, 'wb') as fp:
            fp.write(session.browser.page_source.encode('utf8'))
        print('{0}\nIf raising an issue, please also upload the file located at:\n{1}\n{0}'.format(
            '*' * 70, file_path))
    # full stacktrace when raising Github issue
    raise

finally:
    # end the bot session
    session.end()

**Comment by sionking** [comment]
Another logged out account.
@uluQulu can you step in ?

**Comment by uluQulu** [comment]
This is a different situation.
Since I'm invited to this thread I run some tests.
I should say again,
1-) Get App offer loads only in some accounts [mostly less active, new accounts]
2-) In case of Get App offer does not load, it will timeout and output the same message as the name of this thread AND that message is cool and MUST NOT be taken any serious.

Well, I noticed one thing in new tests.
### A: Get App offer does not load in headless mode
+ Maybe window size is smaller in it?
Here is the screenshot [from selenium] of the screen before the offer loads up [before clicking **Log in**]
![before_offer_headless](https://user-images.githubusercontent.com/33269249/45445267-cf30ae80-b6da-11e8-96ee-ced7466d9cc5.png)

And here is the screenshot after clicking the **Log in** and waiting for the Get App offer come
![inside_offer_headless](https://user-images.githubusercontent.com/33269249/45445285-dce63400-b6da-11e8-9379-9d7edbf4b68d.png)

As you see here is no such offer instead something different!

### B: The same account in graphical mode, 1st screenshot
![before_offer](https://user-images.githubusercontent.com/33269249/45445218-aa3c3b80-b6da-11e8-87cb-ffdaff58182b.png)

2nd screenshot
![inside_offer](https://user-images.githubusercontent.com/33269249/45445202-a1e40080-b6da-11e8-8362-89b32da8630a.png)

As you see it is a bit different and for this situation you should know there there is no any problem, the only difference will be while logging in in headless mode you will not encounter that offer and it will still log in properly and you will just get the message from the `explicit_wait()` cos it will not find that offer element.

Why I told about that test?
+ I think it needs to be taken account for some reasons and in future might be also handled.


For your issue, @MasonLyons
>When I login to the account in a web browser it asks me to **confirm that this login was from me** but even after accepting I still can't login with the account using the bot.

You are interrupting the session manually?
+ Well it may work some time but it is not the way to go, if there is a problem, ask us to get it work.

Well, here you are having problems with confirmation and I have not much experience with that situation but can you try `bypass_suspicious_login` parameter cos I saw you have not added it to the `Instapy()` instance.


Finally, what I said and do say is the problem with @MasonLyons has nothing to do with `explicit_wait()`.

-----

Cheers 😁
------

**Comment by knezzit** [comment]
I got the same error. Anyone know a solution?
