### ISSUE TITLE
Unfollow loop error:  Message: stale element reference: element is not attached to the page document

### ISSUE THREAD

**Issue by pagokrat0r** [InstaPy/InstaPy#2924]
While using unfollow FIFO style with 100 sleep delay, after a few unfollows I keep getting the following error and InstaPy crash:

> ERROR [2018-09-15 00:40:10] [***********]  Unfollow loop error:  Message: stale element reference: element is not attached to the page document
>   (Session info: chrome=68.0.3440.106)
>   (Driver info: chromedriver=2.41.578737 (49da6702b16031c40d63e5618de03a32ff6c197e),platform=Windows NT 10.0.17134 x86_64)

Can't seem to fix it whatever I tried so far.
Already had an issue with app hanging when trying to unfollow a profile that's not active anymore, but I solved this with @uluQulu 's solution.

**Comment by uluQulu** [comment]
Hi @pagokrat0r 
Are your files up-to-date?

If so,
**open** up **unfollow_util.py** file and **add** this new `raise` line
```python
        except BaseException as e:
            logger.error("Unfollow loop error:  {}\n".format(str(e)))
            raise   # ADD THIS LINE
```
Then **post** the _output_ of the thrown exception from console [FULLY] to find the **issue** 🦅

--------

Cheers 😁
-------

**Comment by ceribbo** [comment]
actually i'm having this error too, trying to understand how it happened i saw that when opening following list, under the users to unfollow there are some suggested users to follow, that's why it start following people instead of unfollowing. 

I think it is a bug in instagram, and only just in some accounts, by the way the solution in pretty simple, if the software scroll down to the bottom, the popup doesn't load additional users to unfollow, instead load some suggested users to follow. The simple solution is to scroll at the bottom and the back at the top. in this way only real following users are only loaded and suggested users disappear.
The only implementation to do is:
scroll bottom -> scroll top -> now act as normal unfollow and start scrolling until reaching the desired amount of users.
