### ISSUE TITLE
get_following_status return error; need to change to graphql

### ISSUE THREAD

**Issue by sionking** [InstaPy/InstaPy#2950]
We need to change the following status function to use graphql:
"followed_by_viewer":true,"
To verify we follow the user.

And for some reason the follow button haveent found so we get error and than remove the user from pool.

**Comment by sionking** [comment]
Can someone assist here ?
![image](https://user-images.githubusercontent.com/7851877/45695856-f9ff8480-bb6a-11e8-84eb-5a833b1cd67f.png)

**Comment by sionking** [comment]
So checking the "//*[contains(text(), 'Follow')]" it is not the only and not the first element. maybe is that it ?
@uluQulu ?

**Comment by uluQulu** [comment]
@sionking 
>"We need to change the following status function to use graphql..."

That would definitely be great addition alongside XPath method but both options should operate in harmony in case of the one does not work.

>And for some reason the follow button havent found so we get error and than remove the user from pool.

Well, I think you have not seen my upgrades on that definition and NOW it does **truly** verify IF there REALLY is a problem OR NOT at 100% stability.

>So checking the "//*[contains(text(), 'Follow')]" it is not the only and not the first element. maybe is that it ?

In my last PR I wrote about it in details and not, NOW it does not use `contains(text(), 'ExpectedText')`, **instead** it uses `text()='ExpectedText'` AND yes it is not the only and the first element (_please, read my comment on that PR_) that's why `text()='ExpectedText'` approach is chosen.

----

Cheers 😁
------
