### ISSUE TITLE
BUG: more than 1 xpath when mutual followers

### ISSUE THREAD

**Issue by sionking** [InstaPy/InstaPy#2960]
@uluQulu I think this is your part of the code?
Can you assist here (I am no web/js dev).
```
 Traceback (most recent call last):
  File "quickstart.py", line 165, in job
    session.interact_user_followers(followers_list[:5], amount=20, randomize=True)
  File "C:\\22\instapy\instapy.py", line 2476, in interact_user_followers
    self.logfolder)
  File "C:\\22\instapy\unfollow_util.py", line 983, in get_given_user_followers
    allfollowers = format_number(browser.find_element_by_xpath("//a[contains"
  File "C:\\22\instapy\util.py", line 912, in format_number
    return int(formatted_num)
ValueError: invalid literal for int() with base 10: 'Followed by sivangino and or_richer16'
```

![image](https://user-images.githubusercontent.com/7851877/45797748-caa66000-bcaf-11e8-9f68-6354d603c66b.png)

**Comment by sionking** [comment]
opps account is private. so maybe we need to check it ?

**Comment by uluQulu** [comment]
@sionking It can be handled as usual
```python
                    followers_element = browser.find_element_by_xpath("//a[contains"
                        "(@href,'followers')]/span")

                    if followers_elements:
                        allfollowers = format_number(followers_elements.text)
```
But since the profile is private and is not followed [yet], user cannot load any Followers/Following data from that page.
Shortly for that case of `get_given_user_followers()` definition which needs some Followers/Following data, the scenario must be as this:
+ check if the profile is private on top of other statements
+ if the profile is private and IS NOT followed, then return `[]`

--------

Cheers 😁
-----
