### ISSUE TITLE
Having a timeout set in webdriver.

### ISSUE THREAD

**Issue by sionking** [InstaPy/InstaPy#2968]
## Expected Behavior
browser.set_page_load_timeout(30)

## Current Behavior
More than 30 minute wait for timeout !

What is the proper timeout ?

**Comment by uluQulu** [comment]
@sionking 
There are several types of timeouts and their occurrences:
![timeouts](https://user-images.githubusercontent.com/33269249/45849473-2241db80-bd43-11e8-9b17-d6da49a87263.png)

`set_page_load_timeout()` is waiting for the `get()` navigation method and `click()` action complete.
[For python] its default timeout is 30 _seconds_ [rather than minutes].
See its [source code](https://seleniumhq.github.io/selenium/docs/api/py/_modules/selenium/webdriver/remote/webdriver.html#WebDriver.set_page_load_timeout) & short [documentation](https://seleniumhq.github.io/selenium/docs/api/py/webdriver_remote/selenium.webdriver.remote.webdriver.html#selenium.webdriver.remote.webdriver.WebDriver.set_page_load_timeout).

Implicit wait is currently in use and it has 25 seconds of **InstaPy** default,
```erlang
self.browser.implicitly_wait(self.page_delay)
```

`set_page_load_timeout()` is a bit problematic in cross-platform usage but can be tried [AFAIK]

Why do you think it should be used? - `30` seconds is not enough for normal operation?
_I think @fgisslen would like to try it out_ 👨🏼‍💻 _with big delays_.

----

Cheers 😁
---

**Comment by sionking** [comment]
@uluQulu 
browser.get now don't wait 30 seconds but much more from my testing.
Have you ever reached timeout in web_address_nev.. ? I did, once, after 30 minutes, as I understand there is not timeout in pageload as defaults.

**Comment by uluQulu** [comment]
@sionking 
That's what I said,
>`set_page_load_timeout()` is a bit problematic in cross-platform usage but can be tried [AFAIK]

Cos in other [unofficial] documentation it says the default timeout is `300000` milliseconds (_`5` minutes_)

That's why I have looked into its source code [which we do use] and it is `30` seconds for python.

But yet it is problematic and some people manually apply it by,
```python
            self.execute(Command.SET_TIMEOUTS, {
                'ms': float(time_to_wait) * 1000,
                'type': 'page load'})
```
It is the `except` block of the `set_page_load_timeout()` definition in its source code.

I use local connection and never encountered a `TimeoutException` from that position but people using unhealthy connections or blacklisted servers might have that issue from time to time.

One more fact, there is nowhere that says what does `time_to_wait` parameter gets- _seconds_ or?
`set_page_load_timeout(time_to_wait)`
In its source code it says,
```erlang
        :Args:
         - time_to_wait: The amount of time to wait
```
But in the source code of other similar functions, `implicit_wait()` and `set_script_timeout()`
```erlang
        :Args:
         - time_to_wait: Amount of time to wait (in seconds)
```
means they get _seconds_ as a value.

How I know `set_page_load_timeout()` also gets _seconds_? - code analysis [see the same `except` blocks]

-----

Cheers 😁
---

**Comment by sionking** [comment]
@uluQulu ok
lets anyway set it to 60 ?
set_page_load_timeout(60) I tested it and it working.
Should it be set once or before every call to get ?


> I use local connection and never encountered a `TimeoutException` from that position but people using unhealthy connections or blacklisted servers might have that issue from time to time.

I have symmetric 200/200 Mbps and as a communication engineer I can tell you it is not the only case for getting packets lost on the way to/from target/source. There is so many bed and cheap equipments (4-8 in average) between you and the IG server so something can get lost.

**Comment by uluQulu** [comment]
I have no idea, @sionking 
Cos I have never had issues with it and it needs some experience to choose a good default value.
It might worth trying, if it does not work for some users, it then could be removed or offered partially.

For you question,
>Should it be set once or before every call to get ?

All of the 3 available session timeouts' [in the above screenshot I shared] value lives till the instance of the webdriver is alive, be it the default value or a custom value set by the user.
Once you set a `browser.set_page_load_timeout()` value, it will remain constant throughout the lifetime of the `browser` instance. If you want to change the value you will have to reset it.

> There is so many bed and cheap equipments (4-8 in average) between you and the IG server so something can get lost.

I have 1 Mbit/s speed right now and the cables are mostly copper [homemade 😄 from telephone cables] but I do not get such problems.

----

Cheers 🧐
------
