### ISSUE TITLE
Sessional Live Report shows wrong FOLLOWING/FOLLOWERS count

### ISSUE THREAD

**Issue by adisch79** [InstaPy/InstaPy#2980]
## Expected Behavior
Sessional Live Report should show the current FOLLOWING/FOLLOWERS count at the end of the session.

## Current Behavior
Sessional Live Report shows the FOLLOWING/FOLLOWERS count from the start of the session.
e.g. 
Session begins with 100 FOLLOWERS and 100 FOLLOWINGS.
Session ends with 150 FOLLOWERS and 150 FOLLOWINGS.
Sessional Live Report:
        |> LIKED 0 images  |  ALREADY LIKED: 0
        |> COMMENTED on 0 images
        |> FOLLOWED 50 users  |  ALREADY FOLLOWED: 0
        |> UNFOLLOWED 0 users
        |> INAPPROPRIATE images: 0
        |> NOT VALID users: 0
**currently FOLLOWING 100 users & has got 100 FOLLOWERS** 

**should be:**
_**currently FOLLOWING 150 users & has got 150 FOLLOWERS**_
## Possible Solution (optional)
assign "get_relationship_counts(browser=session.browser,username=session.username, logger=session.logger)" to a new variable (e.g. followers_end,following_end)

**Comment by uluQulu** [comment]
@adisch79 
`get_relationship_counts` is being requested at,
+ **util.py** for `validate_username()` on guest users' profiles
+ **unfollow_util.py** for `unfollow()` on guest users' profiles
+ **relationship_tools.py** for `get_followers()` & `get_following()` host_user's profile

And that information you need for live session report is host user's relationship counts.
It is gonna be renewed only by using relationship tools (_e.g. once you find non-followers for unfollow feature or run some grabber or picker relationship tool_)

For that reason it is practically inefficient to add a new storage for holding updated relationship counts.

For that numbers being ultimately accurate one must add getting relationship counts into the `end` method but it is also not so efficient.

So ideas:
+ Remove that line from the live report
+ Make it print: "_relationship counts at session start_" rather than "_currently_"

----

Cheers 😂
----

**Comment by adisch79** [comment]
@uluQulu - thanks!
