### ISSUE TITLE
Scroll issue with instagram update

### ISSUE THREAD

**Issue by assafelovic** [InstaPy/InstaPy#2989]
## Expected Behavior
Scrolling down successfully 
## Current Behavior
A new feature by instagram requires clicking on "See all suggestions" therefore the bot freezes
## InstaPy configuration
Very basic and nothing new.

Would appreciate any assistance! It seems that it is currently rolled out only on a few users but I assume it'll eventually roll out to all users which is why it should be resolved ASAP.

<img width="401" alt="screen shot 2018-09-23 at 9 24 53" src="https://user-images.githubusercontent.com/13554167/45924857-f5442300-bf12-11e8-8164-d5cce7901451.png">

**Comment by assafelovic** [comment]
@uluQulu to the rescue? :)

**Comment by AvocadoStyle** [comment]
> @uluQulu to the rescue? :)

שמע בתאכלס אני גם יכל לעזור לך...

**Comment by uluQulu** [comment]
Hi @assafelovic 
I have just seen it and it seems like a beta test stage cos
+ it has so unpredictable actions
+ it has many bugs

I remember @timgrossmann talked about this change at its mobile app some time ago.

Once the changes somehow stabilize, I will try to help you.
But if it does not change and shows suggested people from explore tab instead of Followers & Following then it will be a big pity.

-----

Cheers 🙂
-----

**Comment by sionking** [comment]
> שמע בתאכלס אני גם יכל לעזור לך...

הלו !

**Comment by assafelovic** [comment]
Resolved it myself with a hack so I'd rather not contribute it at this stage. I'll add a PR if necessary like @uluQulu stated. Thank you everyone :)

**Comment by sionking** [comment]
Please Share the code when possible

**Comment by assafelovic** [comment]
@sionking simply click the button and scroll as normal by browser and not by dialog
