### ISSUE TITLE
[IDEA] Suggested Feature 

### ISSUE THREAD

**Issue by cyberpz** [InstaPy/InstaPy#3008]
The whole thing came to my mind when i was zapping though profiles, the bot doesn't really have a feature to take advantage of instragram suggested profiles.

I thought coding it as a "set_*" type of function, but i'm too worried of slowing down the full cycle of the bot. 

So what about a "follow_suggested_users" function with the following parameters:
* target_list
* amount 
* randomize
* sleep_time (between profiles)

Let's talk about it.
Pz.

**Comment by Peppuz** [comment]
#

**Comment by ghost** [comment]
I think this would be great to follow suggested users. I do it on twitter a lot.

**Comment by sionking** [comment]
good IDEA ! but please make it interact_suggested_users with optional 100% follow.
We must not maintain too many functions.

**Comment by cyberpz** [comment]
@sionking, so this interact_suggested_users should be an option like the "interact" parameter in multiple functions? 
P.S.
I'm studying the whole bot code to write this as consistently as possible, it might need some time. 
In the meantime I would like to discuss about the feature to make as useful as possible.

**Comment by timgrossmann** [comment]
@Peppuz He meant that, as of now, there are different methods for following.
E.g. `follow_user_followers` and `interact_user_followers` which are slightly different in the way they execute.

So he asked you to please do it as a `interact_suggested_users` since this one is more configurable. `follow_suggested_users` would mean that it will follow through the suggested dialog, not giving the chance to simply interact with users without following them.

So it should, in a very good case, look like this:
```python
session.interact_suggested_users(amount=10, randomize=True, sleep_time= 10)
```

However, this would not do "anything" without setting the actual interaction like this:
```python
session.set_user_interact(amount=5, randomize=True, percentage=50, media='Photo')
session.set_do_follow(enabled=False, percentage=70)
session.set_do_like(enabled=False, percentage=70)

session.interact_suggested_users(amount=10, randomize=True, sleep_time= 10)
```

With optional he meant that people wo really want to follow everyone can do something like this:
```python
session.set_user_interact(amount=1, percentage=100)
session.set_do_follow(enabled=True, percentage=100)

session.interact_suggested_users(amount=10, randomize=True, sleep_time= 10)
```
Which would basically follow every single one of the people the `interact_suggested_users` would come across.
This gives InstaPy users way more power in terms of how they want to use it.


Hope that clears things up a bit.

What is the `target_list` for?

**Comment by cyberpz** [comment]
Forget about the target list, I thought to put directly a list of usernames to make this function working, we might extend that layer
