### ISSUE TITLE
Make chrome NOT load images while running Instapy (save bandwidth)

### ISSUE THREAD

**Issue by Tachenz** [InstaPy/InstaPy#3017]
In the interests of saving bandwidth and traffic... Is it possible to make chrome start, when starting Instapy, with "not load any images" setting in content settings, by default?

I've changed it in the main browser settings, but when instapy chrome instance starts - it has the option "show all images", all the time.  (I can change it every time I start the scrip manually, but it is a bit of a pain, as I am using remote desktop for that).

Also, do you think this can be detected by instagram in any way?

Thank you as always :)

**Comment by HCWcoder** [comment]
@Tachenz 

use this : 

```
session = InstaPy(username=insta_username,
                  password=insta_password,
                  headless_browser=True,
		  disable_image_load=True,
                  multi_logs=True)
```

:dango:

**Comment by Tachenz** [comment]
Amazing - thank you!

**Comment by cline23** [comment]
that's very irritating. disable_image_load=True, it should be false, that would mean it is not loading the image. just my opinion

**Comment by timgrossmann** [comment]
@cline23 Well, if the parameter would be named `image_loading` the having it = to `False` would be what you mean.
It's called `disable_image_load` though, which implies that if it is `True`, the image loading is disabled, otherwise it is not disabled.
Having loading disabled with `False` is kind of double negotiation which would be more confusing.

hopefully that clears things up for you.
