### ISSUE TITLE
Last follow is not verified!	~smells of a temporary block

### ISSUE THREAD

**Issue by xiaomibrasil** [InstaPy/InstaPy#3023]
## Expected Behavior

Hi Everyone
Firstly the message shadow ban,
now it.

What the way? need compare the follows? @uluQulu 
The project don like more this follow method?
because everyone know that are the better way to get success on account instagram.

Sorry for my poor english.

## Current Behavior

Last follow is not verified!	~smells of a temporary block

## Possible Solution (optional)

Liberate the funcion equal old time (2 week before)

## InstaPy configuration

followers_data, selected_filename = load_followers_data(username="mi$....
    session.follow_by_list(followers_data, times=1, sleep_delay=0, interact=Fal$....

**Comment by uluQulu** [comment]
Hi @xiaomibrasil
I have offered a solution to stabilize that part of code you can use at https://github.com/timgrossmann/InstaPy/issues/2981#issuecomment-424388954.
Please keep the discussion in that thread- #2981 for this topic.

#### A few more words
**1**-) It is checking for the button behavior: does it accept the follow or not.
If it does not accept the follow or any other action, then there is a problem and you cannot just jump away such problem.
In future can be added one more layer to hold those failures and break on e.g. 3 consecutive failure rather than on the first one.

**2**-) Ask @sionking about verification in details since it is mostly his idea. I have just improved it 🍬

------


Cheers 😁
----

**Comment by uluQulu** [comment]
Hi @xiaomi
I have offered a solution to stabilize that part of code you can use at https://github.com/timgrossmann/InstaPy/issues/2981#issuecomment-424388954.
Please keep the discussion in that thread- #2981 for this topic.

#### A few more words
**1**-) It is checking for the button behavior: does it accept the follow or not.
If it does not accept the follow or any other action, then there is a problem and you cannot just jump away such problem.
In future can be added one more layer to hold those failures and break on e.g. 3 consecutive failure rather than on the first one.

**2**-) Ask @sionking about verification in details since it is mostly his idea. I have just improved it 🍬

------


Cheers 😁
----
