### ISSUE TITLE
How can I import a list so Instapy won't unfollow specific users

### ISSUE THREAD

**Issue by s-h-a-d-o-w-pixel** [InstaPy/InstaPy#3103]
Hi, not really an issue, just looking for help,
So, I want to have a list so Instapy won't unfollow. How can I achieve that? I've created the list both in json and in csv. Do I have to load it in session.set_ignore_users? How can I import the list?

Sorry and thank you!

**Comment by uluQulu** [comment]
Hi @renmatheus
>How can I import the list?

Can you upload a sample of the data format of your list in the CSV or JSON file of your choice?
So that I can offer a method to read that data into your **quickstart** script for further usage.
_e.g._,
**my_users_data_file.json**:
`["user1", "user2", "userN"]`
Or if you can upload that sample file would be much better.

-------

>I want to have a list so Instapy won't unfollow

You should use `session.set_dont_include(friends=["user1"])`.

----

#### Knowledge Base:
+ `set_ignore_users(users=[])` - if a user who posts is one of these, the image won't be liked
+ `set_dont_include(friends=[])` - defines which accounts should not be unfollowed

-----

Cheers 🐬
----
