### ISSUE TITLE
row 305 instapy.py

### ISSUE THREAD

**Issue by fgisslen** [InstaPy/InstaPy#3135]
row 305 instapy.py

if self.disable_image_load:
                    chrome_options.add_argument('--blink-settings=imagesEnabled=false')

shouldn't it be:
if self.disable_image_load:
                    chrome_options.add_argument('--blink-settings=imagesEnabled=False')

??
@timgrossmann @uluQulu

**Comment by sionking** [comment]
Why do you say that ? I don't think it is a python syntex

**Comment by fgisslen** [comment]
@sionking okey, maybe I should take this back then :P 
But it should work with False also, right?

**Comment by uluQulu** [comment]
Hi there
@fgisslen
It is not a python syntax, @sionking is right. It is a chromium-specific syntax and they accept it like this:
+ `true`: load images
+ `false`: do not load images
+ _any invalid value_- [`True`, `False`, `None`, `null`, `adadaszxcz`, `🤢`]: do not load images

---

Cheers 😄
-------

**Comment by fgisslen** [comment]
The problem is that I'm not sure that it's working properly.
Before I wrote chrome_options.add_argument('--blink-settings=imagesEnabled=False') by my self.
Now I have started to use the build in which calls 
if self.disable_image_load:
chrome_options.add_argument('--blink-settings=imagesEnabled=false')

Now my bandwith have more than doubled per day.

@sionking @uluQulu

**Comment by uluQulu** [comment]
@fgisslen 
>Now my bandwith have more than doubled per day.

I have no idea about it.

>The problem is that I'm not sure that it's working properly.

I learnt that in programming you can't always be definitely sure about a matter but for this particular thing I have no doubts.
If you really think it does not work properly, test it!
In the default source code,
`'--blink-settings=imagesEnabled=false'`
argument is being used only with the headless mode and in the graphical mode it uses the newer preferences method.

#### So, you can do this to verify it,
+ EITHER add that argument to the graphical (_non-headless_) condition instead of the preference method and **see how it works**
preference method is `chrome_prefs['profile.managed_default_content_settings.images'] = 2`
+ OR take a screenshots inside the headless mode by a selenium command- `save_screenshot()` and **see how it works by screenshot(s)**
`browser.save_screenshot("image-load-test.png")`

---

Cheers 😀
---
