### ISSUE TITLE
"//article/div/div/p/a[text()='Log in']")

### ISSUE THREAD

**Issue by fgisslen** [InstaPy/InstaPy#3137]
Hi,
there is a problem when logging in.
@sionking @uluQulu any ideas?

Traceback (most recent call last):
  File "/home/fredrik/InstaPy/5bb9bf41f2603d00134369d8.py", line 18, in <module>
    session.login()
  File "/home/fredrik/InstaPy/instapy/instapy.py", line 390, in login
    self.bypass_suspicious_attempt):
  File "/home/fredrik/InstaPy/instapy/login_util.py", line 184, in login_user
    "//article/div/div/p/a[text()='Log in']")
  File "/home/fredrik/.local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 393, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/home/fredrik/.local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 966, in find_element
    'value': value})['value']
  File "/home/fredrik/.local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 320, in execute
    self.error_handler.check_response(response)
  File "/home/fredrik/.local/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//article/div/div/p/a[text()='Log in']"}
  (Session info: headless chrome=69.0.3497.100)
  (Driver info: chromedriver=2.42.591071 (0b695ff80972cc1a65a5cd643186d2ae582cd4ac),platform=Linux 4.15.0-36-generic x86_64)

**Comment by ajankuv** [comment]
How are you running it? I have accounts working, and 1 doing this same thing. It's a new account under it's own venv.

**Comment by fgisslen** [comment]
@ajankuv I also have a lot of accounts running, but I think it's the ones that don't have cookies or something like that.

**Comment by ajankuv** [comment]
@fgisslen first logins? or new accounts? or just randomly? I'm trying to narrow this down

**Comment by fgisslen** [comment]
I'm not sure. Will check some more.

**Comment by anton4** [comment]
I have been unable to log in due to this error for the last 2 weeks. 
My account is 2 years old.

When i run quickstart.py with headless_browser=False it just stares at this page for 10 seconds and then closes - https://www.upload.ee/image/9069572/Screenshot_20181015_085606.png 
and then in the script output i get following error ..

OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2018-10-15 14:22:39] [myusername]  Session started!
ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo

Issue with cookie for user myusername. Creating new cookie...
**********************************************************************
If raising an issue, please also upload the file located at:
/tmp/20181015-142313.html
**********************************************************************
INFO [2018-10-15 14:23:14] [myusername]  Sessional Live Report:
        |> LIKED 0 images  |  ALREADY LIKED: 0
        |> COMMENTED on 0 images
        |> FOLLOWED 0 users  |  ALREADY FOLLOWED: 0
        |> UNFOLLOWED 0 users
        |> INAPPROPRIATE images: 0
        |> NOT VALID users: 0
currently FOLLOWING 0 users & has got 0 FOLLOWERS


OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2018-10-15 14:23:14] [myusername]  Session ended!
ooooooooooooooooooooooooooooooooooooooooooooooooooooooooo



Traceback (most recent call last):
  File "quickstart.py", line 19, in <module>
    with smart_run(session):
  File "/usr/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/home/localuser/InstaPy/instapy/util.py", line 1331, in smart_run
    session.login()
  File "/home/localuser/InstaPy/instapy/instapy.py", line 390, in login
    self.bypass_suspicious_attempt):
  File "/home/localuser/InstaPy/instapy/login_util.py", line 184, in login_user
    "//article/div/div/p/a[text()='Log in']")
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 293, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 752, in find_element
    'value': value})['value']
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//article/div/div/p/a[text()='Log in']"}
  (Session info: chrome=68.0.3440.106)
  (Driver info: chromedriver=2.41.578700 (2f1ed5f9343c13f73144538f15c00b370eda6706),platform=Linux 4.18.3-041803-generic x86_64)

**Comment by ajankuv** [comment]
Ok so I guess we can rule out new accounts, it seems like everyone has gone dark for this issue.

**Comment by uluQulu** [comment]
İ will help you

Sent from MailDroid<https://goo.gl/ODgwBb>

-----Original Message-----

**Comment by mocnik10** [comment]
Hi, I have this problem too :(

**Comment by ajankuv** [comment]
So I was able to fix this, I have been cloning my venv's from one to another being lazy. Which has worked until this last clone. 

I did a new venv in python, a fresh install and the latest version of chromedriver. It' all works now.

$ virtualenv username
$ source venv/bin/activate
$ pip install git+https://github.com/timgrossmann/InstaPy.git
$ latest_version=$(wget https://chromedriver.storage.googleapis.com/LATEST_RELEASE -O -)
$ wget https://chromedriver.storage.googleapis.com/${latest_version}/chromedriver_linux64.zip
$ unzip chromedriver_linux64
$ mkdir -p local/lib/python2.7/site-packages/assets
$ mv chromedriver local/lib/python2.7/site-packages/assets
$ chmod +x local/lib/python2.7/site-packages/assets/chromedriver
$ chmod 755 local/lib/python2.7/site-packages/assets/chromedriver
$ python yourscript.py

**Comment by Zettt** [comment]
@ajankuv Thanks for helping out with this issue! 

I followed your instructions 1-by-1 and it's now working again. The only difference is that it's just `lib/python2.7/site-packages/` on a Mac. Also `wget` doesn't exist on a Mac, and `curl` throws an error. I just downloaded the latest driver by hand. 

I don't believe it's necessary to chmod the `chromedriver`, and I presume that this issue is caused by some sort of incompatibility with specific packages. Maybe it should be noted in the README that the virtualenv installation is the one preferred method? It's not clear from reading the file. It says, you can install it this way, but preferred would be this way.

**Comment by anton4** [comment]
Virtualenv did not help in my case, but deleting cookie file at InstaPy/logs/myusername/myusername_cookie.pkl made instapy work again.

When it said Issue with cookie for user myusername. Creating new cookie...
i watched the cookie file and it was dated back to 2 october, so it did not create new cookie unfortunately and had to manually delete it.
