### ISSUE TITLE
Help needed with formatting values for followedPool.csv

### ISSUE THREAD

**Issue by Nocturnal-2** [InstaPy/InstaPy#3340]
## Slightly offtopic - looking for a around about solution

I have couple of hundred user which I want to unfollow. They were not followed by InstaPy and they are in an csv (with username, userid and date-time each in a separate column). 

I would like to add them to followedPool.csv so that I can use InstaPy to unfollow them. But I am having difficulty with putting them all to the following format

`2018-09-15 17:17 ~ username ~ userid`

Can someone please suggest me a easy way of doing this (without having to write a code :) )? Thanks in advance!!

**Comment by GabrieleCalarota** [comment]
date is not relevant and you should write a list of usernames.
Give this list in input to a python script that dumps it in that format using also getuserId from username function.

**Comment by Nocturnal-2** [comment]
Thanks @GabrieleCalarota !

**Comment by uluQulu** [comment]
@Nocturnal-2 
```python
                """
                Data entry styles [historically]:
                    user,   # oldest
                    datetime ~ user,   # after `unfollow_after` was introduced
                    datetime ~ user ~ user_id,   # after `user_id` was added
                """
```
That comment was taken from the `set_automated_followed_pool` definition at **unfollow_util.py** file.

It means the data in any of those formats are supported by default for generating a user list to unfollow.

In other words, e.g. you can just add all the users you have got in plain format,
```csv
user1,
users2,
```
to the **_followedPool.csv** file.

What will it be different than other style of entries?
+ Since you will not provide the datetime data (_the time user was followed_) for that user, then you will not be able to benefit the from `unfollow_after` parameter for that user.
+ Since you don't provide the user's ID data in that line entry, in case of user has changed username, you will not be able to find the user's new username.

---
Read source code, read more.

Cheers 😁
---

**Comment by Nocturnal-2** [comment]
@uluQulu Thank you so much for the detailed explanation! It worked!! :)
