### ISSUE TITLE
A few thoughts on InstaPy's features (vs. Instabot)

### ISSUE THREAD

**Issue by kairosooo** [InstaPy/InstaPy#3377]
Too Long Didn't Read(TLDR): Instapy could improve by default running 24/7 non-stop, and stabilize liking frequency.

I have been using IG automation program for 5 months now. I finally chose to stick with Instabot, after trying this Instapy and another software called Ninjagram.

I think Instapy would have some good features to adopt from Instabot to benefit more people.

Firstly, **what Instapy should adopt from Instabot:**

### **1. default to run script forever.** 
Instabot allows user to set "likes per day" e.g. 200. Then, it will automatically divide each like action to happen once every 7 mins. (24hours x 60mins =1440mins; 1440mins / 200 actions =7.2 min/action)
Instabot requires no additional schedule setup to make the bot running 24/7, which is much easier for script user to manage.

### **2. Removing potency ratio.**
I found InstaPy's potency ratio more of an annoying feature which only complicate stuff by adding more variables to the script, for two reasons.

                -It cannot reflect the actual "like amount".
                -It fluctuates the actual liking frequency.

Furthermore on (i), for example, if I type "desired like amount" as 200, if the potency ratio is too strict, then it may skip many users. At last, what I would have got might be only 40 likes. 

**_However, what I wanted to achieve is exactly 200 likes!_**

Furthermore on (ii), for example, if I again type "desired like amount" as 200, if the potency ratio is too strict, then the script will take like action very slowly, it might take 2 days to complete. On the other way around, if the potency ratio is too loose, then it might only take 4 hours to complete. 

Also, if the script luckily found 10 in-range users in a row, the script will like 10 posts consecutively in a very short time.

So, how is this a problem? We all know that liking too frequently causes IG to ban the account. On the other hand, we don't want the script to take ages to finish.  In conclusion, although the potency ratio can help the account to only target realistic-looking IG users, it just adds too many unpredictable variables to the script.

I really appreciate how InstaPy could have distinct functions like "Interact with someone else's followers" which is very useful in tracking down real IG user (which Instabot doesn't have). I believe InstaPy could be further improved by adopting above suggestions.

Acknowledgment: I have no any mean to criticize InstaPy, it is a great script, I am not complaining but to suggest possible improvements only.

You have come a long way, thanks for reading :D

**Comment by lscaldas** [comment]
Hello @kairosooo . I am in noway an expert in instapy, but what you are saying is essentialy is: the best way to improve instapy is to downgrade it. First question can be answered by looking in the quickstart templates in the last version, there are multiple options to choose. There is a solution to put a waiting time inside evey like (30 seconds instead of 2 seconds) in like_util. So you can easily avoid over liking in a time frame. Your second request is already solved too: You dont need to use potency ratio, you can just put False instead of True, then you dont use this parameter.  I suggest you to read the documentation, cause Instapy is miles ahead Instabot, with much more features.

**Comment by sionking** [comment]
both have security issues.
I think instapy code is too complex and could be much simpler.

**Comment by converge** [comment]
@sionking you touch in a crucial point, it's a bit too complex at the moment, that's why Im adding PEP8 code style, it force us to have a better code quality.

Other point is, a roadmap would guide us to a direction, and I think it's time to discuss about releases/tag.

**Comment by sionking** [comment]
Spaghetti code

**Comment by uluQulu** [comment]
@https://github.com/kairosooo
>I found InstaPy's potency ratio more of an annoying feature which only complicate stuff by adding more variables to the script, for two reasons.

You better get a basic understanding on
+ how **InstaPy** works;
+ what is its style [ideology];

And only then you will get if it is right to compare it with other application in its own forum and moreover _negatively_ criticize (_complain on_) `potency_ratio`.

### Post Script
I wrote the part containing `potency_ratio` and it really feels wasted after reading your detailed analysis on how useless and ANNOYING it is.


BTW, if you want to improve something, start by writing it and raising a pull request.
_Yet, I did not see any piece of word containing an improvement for the project in your **Issue** desciption, anyways_..

### Details - I will also criticize

>Too Long Didn't Read(TLDR): Instapy could improve by default running 24/7 non-stop, and stabilize liking frequency.

Again, you are not familiar with **InstaPy** and its style.
But it's normal for people coming from using similar features which has such capability.

I used **instabot** (_guessing it is the project from LevPasha you meant_) before heard of this project.
But although it was doing good, it had no any support [from the community & owner(s)] and interestingly, owner opened its C# version which had a full support in a paid (_non-free version_) plan WHICH made me to quit that software.

Then I heard of **InstaPy** and was so much complex cos I INSTALLED tons of other software to use it and at that time I had no any python knowledge..
Shortly, the point is InstaPy can be advanced but it is how it works and it worths to learn it since there is no any (_really_) competitor to **InstaPy** in the means of esp. **interactions** [paid or free].
If I think again, today **InstaPy** is getting easier day by day, and having a dynamic GUI for it will end this pain behind whilst preserving the same experience.

And **instabot** is so lite as @tiranin mentioned, and if you don't think to invest time to learning **InstaPy** to benefit its features, just go with it.
_Remember, I also had no any python knowledge before **InstaPy**, but I can use it today in its best and also know lots of python alongside IG automation_.

I don't think any time **instabot** can reach **InstaPy** cos of the style it uses.
BTW while writing `unfollow_after` parameter I used the idea I saw in **instabot** and you can see the same value style in there (_if it did not change.._).


@tiranin has told most of what I wrote here but I just read it after writing this and it will be a re-share of some common thoughts.
@sionking and security is getting stricter day by day or I feel like it..
@converge some PEP8 rules are crazy, though. like allowing only 2 empty lines between definitions 🤤 it decreases readability, isn't it?


>I finally chose to stick with Instabot

@https://github.com/kairosooo, Good luck!
But wait, then what is the point of discussing the software you will not use, I DON'T GET IT.  

### Conclusion
Due to the reasons I've outlined above, I find this thread to convey an [unhealthy criticism](https://www.quora.com/How-do-I-differentiate-between-a-healthy-criticism-and-an-unhealthy-one).

---
Currently my **quickstart** uses `potency_ratio` with the value of 1 without delimiting by numbers.

Cheers 😁
----

**Comment by converge** [comment]
@uluQulu I know how you feel, I used to feel the same. Most people on the InstaPy community are amazing, last night I was video chatting with a guy that worked on Tesla, and those things make our effort worth it.

And there is the 1%, that criticizes our job because it's not working as they expect, or because some bug is popping up on screen, but again, it's 1% , let's focus on 99% of great people we have here.

About PEP8, I know, it sounds strict. It's like getting a ticket for not crossing the road on crosswalk, doesn't sound right in the beginning, but when you see that there is no more accidents and everyone follow these rules, it's better for everyone.

**Comment by kushpvo** [comment]
With a little bit of programming knowledge, you can make InstaPy work 24/7
My current script was running since last 9 days on my Raspberry Pi 3B+ and it stopped yesterday because my electricity went off.

Basically, i put the whole code into a `while True:` and added a random delay of 2 to 4 hours at the end of the session. So, technically, it runs 24/7

**Comment by converge** [comment]
@kushpvo cron is a better approach (*nix).

**Comment by Areahints** [comment]
I wish I saw this before opening #3387 
InstaPy is waaaaaaaay better than instabot.py, the only thing I liked about instabot.py was the infinity feedliker script and the fact that it doesn't use a browser, that makes it possible for me to use it on my phone which saved me the cost of getting proxies and a server, also its unfollow is top notch.

InstaPy, on the other hand, emulates smart ways of bypassing Instagram strict rules on automation and that's a lifesaver, with instabot.py, I'm solving a security challenge every 6 hours, and if I need to fix something, there's no community to fall back on. instapy can also run 24/7. you just need to schedule it

**Comment by uluQulu** [comment]
@Areahints, 
it uses HTTP 
```scala   
  /__)  _  _     _   _ _/   _
 / (   (- (/ (/ (- _)  /  _)
          /
```

And you can make unfollowing much faster than it is in **InstaPy** by changing default delays, inashmuch, it's behalf of the safe use policy..
There are apps (_mobile & paid_) I used earlier that could do unlimited amounts of unfollow in no time, e.g., I have unfollowed ~200 in less than 10 seconds in one button click which is by far, a non-human activity 😉

**InstaPy** has super duper platform & python independency unlike any other similar app that's why too many people are able to use it easily; E.g. **instabot** isn't python independent (_last time I used_)..
The point is mobile platform can be the targeted in future for **InstaPy** and I think, it can happen only after a good GUI cos its huge variety of tools will be difficult to maintain in those little devices 😛

**Comment by Areahints** [comment]
@uluqulu sorry i meant instabot.py and it runs on both python 2 and 3. 

i like the fact that mobile phones could be a feature of instapy, afterall python runs anywhere right?

**Comment by uluQulu** [comment]
@Areahints 
I think we both talk about LevPasha's project, it did not have full python support at the time I used (_~a year ago_) and it seems they have worked it out.

Python can run anywhere but software must also be supported in the target platform; Else than that, resources in the target device must be sufficient enough, etc...

**Comment by visualheroes** [comment]
Potency ratio is not working for me as it is right now. It simply doesn't works with my targeted audience and i think it urgently needs some options to fine-tune it. However, I really think it's a great feature/option to have.
Now, i think your critic is a bit harsh as you just set it to "false" and use the relationship bounds instead.

I had a script running on a while loop, acting exactly like every other bots out there: liking/following/unfollowing the same amount every 12 or so minutes. It's easy to script with Instapy. 
Anyway, i don't run this script anymore as it is not organic at all. It looks like a bot and is way too aggressive. 

I think the others are right, Instapy is not the same philosophy. I do not run 24/7 anymore and all my script are very organic with tons of randomizations. 

To conclude, Instapy is the only platform (open-source or not) providing that amount of customization. I just wish we have a more stable development in the future with a clear roadmap, i lost too many hours re-coding my scripts after code changes.

**Comment by uluQulu** [comment]
Hi @visualheroes 
How come `potency_ratio` does not work?
It is just a basic ratio,
+ `followers_count`/`following_count` - **potential user** [positive value] 
+ `following_count`/`followers_count` - **massive follower** [negative value]

Maybe you mean it is not efficient enough, eh?

Well, one of its role is leaving the pain of setting numbers manually,
E.g. currently in my setup, I want to target **potential users** who has more followers than following regardless of has how many followers or following users has WHERE `potency_ratio=1.00001` does the job for me;

@visualheroes, any ideas to improve it? or a better idea to replace it?

About "_recoding the script after updates_":
Try to add your customizations outside the core files, so that after updates, they don't make conflicts.

The most annoying changes are renamings in the user interface and I think the last one was renaming the unfollow feature's parameters [by me]. Such changes affect everybody and must be avoided if not so important.

---

Cheers 😁
---

**Comment by visualheroes** [comment]
Hey @uluQulu !

Don't get me wrong, i wrote it doesn't work for my targeted audience atm.

Look if i check my friends/client accounts some have really small accounts with a lot of following (brands, etc..) and they mostly don't care about followers. Depends on my potency ratio this kind of account get set aside when i fine tune potency ratio for large account with massive followers.

For me, as i already said in another thread, potency ratio needs some bounds/limit. It simply not possible to have the same ratio with a new/small account (under 1000) and a large account. 

That's why for the moment i'm not using it anymore. On paper it's a very cool and simple idea but there are so many different types of accounts out there. It's too much of a generalization without a way to differentiate between account size etc..

For the re-coding. Well, i had only a couple of corrections on the core script (eg: follow by tag not using followrestriction). Mostly it's the renaming that was a bit of a problem lately, i do not have enough time to check the forums everyday! ;)

Edit: By the way, i did not check recently, do you know if follow_by_tags now use the followrestriction? I stopped using it after the last rewrite broke my corrections.

**Comment by octavius-1** [comment]
@Areahints How do you make the usage of proxies and servers? I'm usually running 10 accounts in 2 raspberries (5 accounts each) and instagram has been blocking my "follow" actions there.
