### ISSUE TITLE
ERROR (Driver info: chromedriver=2.36 (a81166ad79e68fbfe7cf5ba243192d6412e26b37),platform=Linux 4.14.79-v7+ armv7l)

### ISSUE THREAD

**Issue by tomtactom** [InstaPy/InstaPy#3386]
## Expected Behavior
`sudo python3 quickstart.py`
quickstart.py should be run in chromium.
## Current Behavior
**These errorcode:**

> ERROR [2018-11-18 20:39:29] [myinstaname]Message: unknown error: Chrome failed to start: exited abnormally
> (Driver info: chromedriver=2.36 (a81166ad79e68fbfe7cf5ba243192d6412e26b37),platform=Linux 4.14.79-v7+ armv7l)
> Traceback (most recent call last):
> File "/home/pi/Dokumente/InstaPy/instapy/instapy.py", line 357, in set_selenium_local_session
> chrome_options=chrome_options)
> File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/chrome/webdriver.py", line 81, in __init__
> desired_capabilities=desired_capabilities)
> File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
> self.start_session(capabilities, browser_profile)
> File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
> response = self.execute(Command.NEW_SESSION, parameters)
> File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
> self.error_handler.check_response(response)
> File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
> raise exception_class(message, screen, stacktrace)
> selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally
> (Driver info: chromedriver=2.36 (a81166ad79e68fbfe7cf5ba243192d6412e26b37),platform=Linux 4.14.79-v7+ armv7l)
> Traceback (most recent call last):
> File "/home/pi/Dokumente/InstaPy/instapy/instapy.py", line 357, in set_selenium_local_session
> chrome_options=chrome_options)
> File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/chrome/webdriver.py", line 81, in __init__
> desired_capabilities=desired_capabilities)
> File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
> self.start_session(capabilities, browser_profile)
> File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
> response = self.execute(Command.NEW_SESSION, parameters)
> File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
> self.error_handler.check_response(response)
> File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
> raise exception_class(message, screen, stacktrace)
> selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally
> (Driver info: chromedriver=2.36 (a81166ad79e68fbfe7cf5ba243192d6412e26b37),platform=Linux 4.14.79-v7+ armv7l)
> During handling of the above exception, another exception occurred:
> Traceback (most recent call last):
> File "quickstart.py", line 16, in <module>
> headless_browser=False, nogui=True)
> File "/home/pi/Dokumente/InstaPy/instapy/instapy.py", line 232, in __init__
> self.set_selenium_local_session()
> File "/home/pi/Dokumente/InstaPy/instapy/instapy.py", line 361, in set_selenium_local_session
> Settings.chromedriver_location))
> instapy.instapy.InstaPyError: ensure chromedriver is installed at /home/pi/Dokumente/InstaPy/assets/chromedriver
> 

## InstaPy configuration
```
from instapy import InstaPy
from instapy.util import smart_run
insta_username = 'myinstaname'
insta_password = 'mypassword'
session = InstaPy(username=insta_username, password=insta_password, headless_browser=False, nogui=True)
with smart_run(session):
session.set_relationship_bounds(enabled=True, delimit_by_numbers=True, max_followers=4590, min_followers=45, min_following=77)
session.set_dont_include(["friend1", "friend2", "friend3"])
session.set_dont_like(["pizza", "#store"])
session.like_by_tags(["natgeo"], amount=10)
```

## System
**Raspberry PI**
**Chromium**: Version **65.0.3325.181** (Offizieller Build) Built on Raspbian , running on Raspbian 9.6 (32-Bit)
**Chromiumdriver**: **2.36** (32-bit)
System: _armv7l_ (32-bit)

**[Instapy Say:](https://github.com/timgrossmann/InstaPy/blob/master/docs/How_to_Raspberry.md#readme)**

> The combination of the versions of chromium-browser and chromdriver is important. This combination is currently working
> Chromium 65.0.3325.181 Built on Raspbian , running on Raspbian 9.4
> ChromeDriver 2.36 (a81166ad79e68fbfe7cf5ba243192d6412e26b37)

**Comment by converge** [comment]
did you install chrome browser ?

**Comment by tom12aschmann** [comment]
I have installed the chromium browser.
-------- Ursprüngliche Nachricht --------Von: João Paulo Vanzuita <notifications@github.com> Datum: 19.11.18  00:01  (GMT+01:00) An: timgrossmann/InstaPy <InstaPy@noreply.github.com> Cc: tom12aschmann <tom.aschmann@t-online.de>, Author <author@noreply.github.com> Betreff: Re: [timgrossmann/InstaPy] ERROR (Driver info: chromedriver=2.36
  (a81166ad79e68fbfe7cf5ba243192d6412e26b37),platform=Linux 4.14.79-v7+ armv7l)
  (#3386) did you install chrome browser ?

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/timgrossmann/InstaPy","title":"timgrossmann/InstaPy","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/timgrossmann/InstaPy"}},"updates":{"snippets":[{"icon":"PERSON","message":"@converge in #3386: did you install chrome browser ? "}],"action":{"name":"View Issue","url":"https://github.com/timgrossmann/InstaPy/issues/3386#issuecomment-439734054"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/timgrossmann/InstaPy/issues/3386#issuecomment-439734054",
"url": "https://github.com/timgrossmann/InstaPy/issues/3386#issuecomment-439734054",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [timgrossmann/InstaPy] ERROR (Driver info: chromedriver=2.36 (a81166ad79e68fbfe7cf5ba243192d6412e26b37),platform=Linux 4.14.79-v7+ armv7l) (#3386)",
"sections": [
{
"text": "",
"activityTitle": "**João Paulo Vanzuita**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@converge",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"timgrossmann/InstaPy\",\n\"issueId\": 3386,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"timgrossmann/InstaPy\",\n\"issueId\": 3386\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/timgrossmann/InstaPy/issues/3386#issuecomment-439734054"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 413173318\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by tomtactom** [comment]
> did you install chrome browser ?

I have install "**chromium**" _(Chromium: Version 65.0.3325.181 (Offizieller Build) Built on Raspbian , running on Raspbian 9.6 (32-Bit))_
becouse the original Google Chrome are not available for Linux

**Comment by MrLemur** [comment]
I have received the same issue suddenly. Nothing has changed on my end.

**Comment by gitpatrickhub** [comment]
Same issue on new raspberry pi install

**Comment by tomtactom** [comment]
Hey people, I have now written a install code :)💪😃👍

# Part 1
`sudo apt-get update
sudo apt-mark hold chromium-browser
sudo apt-get update
sudo apt-get upgrade
sudo apt-get update
sudo apt-get install python
sudo apt-get install python-imaging
sudo apt-get install libjpeg8
sudo apt-get install libfreetype6
sudo apt-get install libjpeg8 libjpeg62-dev libfreetype6 libfreetype6-dev
sudo apt-get install xvfb
sudo apt-get install selenium
sudo apt-get install tmux
sudo apt-get install chromedriver
sudo apt-get install python-pip
sudo apt-get install git
mkdir Projects
cd Projects
git clone https://github.com/timgrossmann/InstaPy.git
sudo reboot`

# Part 2
`cd Projects
cd InstaPy
sudo pip install .
sudo apt-get install python-imaging
sudo apt-get install libjpeg8
sudo apt-get install libfreetype6
sudo apt-get install libjpeg8 libjpeg62-dev libfreetype6 libfreetype6-dev
sudo pip install future
sudo pip install pyvirtualdisplay
sudo pip install .
cd assets
wget https://github.com/electron/electron/releases/download/v3.0.0-beta.5/chromedriver-v3.0.0-beta.5-linux-armv7l.zip
unzip chromedriver-v3.0.0-beta.5-linux-armv7l.zip
sudo apt-get remove chromium
sudo reboot`

# Part 3
> • change in the quickstart.py on line 14 "session = InstaPy(username=insta_username, password=insta_password, headless_browser=False)" to "session = InstaPy(username=insta_username, password=insta_password,headless_browser=True)"
> • fill in your Instagram Account data

`sudo xvfb-run python quickstart.py`

**Comment by Ryogaag** [comment]
> Hey people, I have now written a install code :)💪😃👍
> 
> # Part 1
> `sudo apt-get update sudo apt-mark hold chromium-browser sudo apt-get update sudo apt-get upgrade sudo apt-get update sudo apt-get install python sudo apt-get install python-imaging sudo apt-get install libjpeg8 sudo apt-get install libfreetype6 sudo apt-get install libjpeg8 libjpeg62-dev libfreetype6 libfreetype6-dev sudo apt-get install xvfb sudo apt-get install selenium sudo apt-get install tmux sudo apt-get install chromedriver sudo apt-get install python-pip sudo apt-get install git mkdir Projects cd Projects git clone https://github.com/timgrossmann/InstaPy.git sudo reboot`
> 
> # Part 2
> `cd Projects cd InstaPy sudo pip install . sudo apt-get install python-imaging sudo apt-get install libjpeg8 sudo apt-get install libfreetype6 sudo apt-get install libjpeg8 libjpeg62-dev libfreetype6 libfreetype6-dev sudo pip install future sudo pip install pyvirtualdisplay sudo pip install . cd assets wget https://github.com/electron/electron/releases/download/v3.0.0-beta.5/chromedriver-v3.0.0-beta.5-linux-armv7l.zip unzip chromedriver-v3.0.0-beta.5-linux-armv7l.zip sudo apt-get remove chromium sudo reboot`
> 
> # Part 3
> > • change in the quickstart.py on line 14 "session = InstaPy(username=insta_username, password=insta_password, headless_browser=False)" to "session = InstaPy(username=insta_username, password=insta_password,headless_browser=True)"
> > • fill in your Instagram Account data
> 
> `sudo xvfb-run python quickstart.py`

I was having trouble running it on a raspberry pi 3 b+ with octopi
Thank you! This worked for me!
