### ISSUE TITLE
Make sure to not follow the same users as last session

### ISSUE THREAD

**Issue by sbredberg** [InstaPy/InstaPy#3400]
Hey all! I'm pretty new to this, learning by doing. I'm right now using @cormo1990's template for _Basic follow-unfollow activity_ (thanks a lot for sharing that!) 

My question is, if I use `session.follow_user_followers(['USERNAME1','USERNAME2','USERNAME3'], amount=800, randomize=False, interact=False)` wouldn't it be following the same set of users in every session as the list in the popup loaded in the actual Instagram session seem to be in same order everytime? Of course, this might easily be fixed by setting `randomize=True` but I would like to hear a good argument _to not_ randomize it then, to make sure I don't miss anything out here. Thanks in advance, keep up the good work all contributors!

**Comment by cormo1990** [comment]
Hello @sbredberg and thanks for your feedback.
You can set to skip the user that already has been followed 1(or two or three times) for  example. 
Into the field amount you have to put an high number in order to be sure to follow new users.
Another solution could be follow all the followers of that account but you have to keep in mind the IG limit of following if your account is recently (7500).

But let me know more about it....so which would you like to be the discriminator to select users?
Maybe other users have this needs.
thanks

**Comment by ghost** [comment]
I'm interested in this too. it seems like the session.follow_user_followers starts fresh each time. Dose it log the last postion it was at when its run? or if it sees its prosessed that account before will it skip them users and carry on when it sees users it hasnt interacted with before?

also can the times=1 be used with all follow and comment fetures to only follow and comment a user only once ever and is this information kept if the program ends and starts again?
