### ISSUE TITLE
ModuleNotFoundError: No module named 'commands' 

### ISSUE THREAD

**Issue by tooxiic49** [InstaPy/InstaPy#3425]
Hello, sorry i dn't speak english.
J'ai un soucis, lorsque j'installe avec powershell, la commande ''python setup.py install" 
à la fin de l'installation j'ai un message qui me dit : ModuleNotFoundError: No module named 'commands'
et impossible de lancer mon quickstar par la suite.
si vous avez une solution, merci beaucoup :)

**Comment by tooxiic49** [comment]
help plz :/

**Comment by peroutek** [comment]
I don't know how to fix it, but I have narrowed my issue down a little bit. If you scroll up in your error, its having an issue because you don't have Visual Studio Build Tool. However, even after you download that, you get the error:
 C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\cl.exe' failed with exit status 2.

If you go and try to manually run that .exe, it errors because it cannot find mspdb140.dll. I have tried all of the solutions online to generate this .dll and have had no luck. Someone pls help.
