### ISSUE TITLE
Quota supervisor hanging issue?

### ISSUE THREAD

**Issue by brunomiguelleal** [InstaPy/InstaPy#3440]
## Expected Behavior
Quota supervisor to hold the script to ensure that limits are not breached
## Current Behavior
In gerenal Quota supervisor works ok, but for a couple of times it just hangs and I need to press ENTER for it to continue, for instance:

> INFO [2018-11-27 08:38:07] [<my username>]  Quota Supervisor: hourly likes reached quotient!	~going to sleep 28 minutes long
> 	take a coffee colombia break? :>

It hanged here and then I pressed ENTER...

> INFO [2018-11-27 09:08:26] [<my username>]  --> Image Liked!

Thanks in advance,
Bruno

## InstaPy configuration

```
    session.set_quota_supervisor(enabled=True,
                                 sleep_after=["likes_h"],
                                 sleepyhead=True, stochastic_flow=True, notify_me=False,
                                 peak_likes=(100, 1500)
                                 )
    session.like_by_tags(['travel', 'travelphotography', 'travelawesome', 'traveladdict', 'doyoutravel', 'instatravel'], interact=True, amount=25)
```

**Comment by uluQulu** [comment]
Make sure your terminal is active.
E.g. in _command prompt_ console application of Windows OS, there is a feature called "_Quick Edit Mode_" and unless it is turned off, once you click or press `CTRL Shift Up/Down` on it, it will freeze the ongoing operations in there until you press either `Enter` or `Esc`.

If you have a Windows OS, check out the _Edit Options_ at _command prompt's_ properties and uncheck the features you don't want since your issue has nothing to do with QS.

Also there is a point of `sleep` function wakes up sometimes at unpredicted [late] time cos of certain reasons tied up mainly to the processors' capabilties.
But at that case, which you don't have an issue yet, the solutions is truly non-easy.

---

Cheers 😁
---

**Comment by brunomiguelleal** [comment]
Many thanks for the reply and the help.

For the last 24h it worked ok, but anyway I have turned off those options and let it run for a few days!

Cheers,
Bruno
