### ISSUE TITLE
How to do to like all the users of a user being that he possessed 3M of followers?

### ISSUE THREAD

**Issue by zsvendo** [InstaPy/InstaPy#3447]
@uluQulu 
How to do to like all the users of a user being that he possessed 3M of followers?
I want to like 500 photos daily, how to do it?

**Comment by uluQulu** [comment]
Hey @zsvendo 

Tell me what you cannot do.

**Comment by zsvendo** [comment]
@uluQulu  I want to give like followers that has 3 million followers, giving 1000 likes a day

**Comment by uluQulu** [comment]
Alright @zsvendo 

I asked, 
"_Tell me what you cannot do_"
cos I don't know the details you have in mind.

But this activity flow can achieve your need at the simplest form,
```python
import random

superstars_followers = session.grab_followers(username="superstar", amount=1000)
chosen_followers = random.sample(superstar_followers, 500)

session.like_by_users(usernames=chosen_followers, amount=2)
```
It will grab 1000 followers of a Super Star and then take random 500 people from them.
Finally, like 2 photos from all of those 500 people.

Since 500 * 2 makes 1000, you will like 1000 photos a day from followers of the Super Star.


---
Details are important.

Cheers 😁
---

**Comment by zsvendo** [comment]
@uluQulu Okay, but I want to reach the 3 million followers that this person has. That's the big problem, how to hit the 3 million?

**Comment by uluQulu** [comment]
@zsvendo 
It is madness to get those 3 million users at once 🤩

You can do this,
E.g. every day you need 1000 new users to interact from that Super star's followers;
So go grab followers until reaches 1000 new followers.
That will be an efficient way to fulfill your need.

You can do it by editing the core files

---
I still did not see details 😀

Cheers 😁
---

**Comment by zsvendo** [comment]
@uluQulu 
I'll ask the question differently.
how do I reach a user's likes with 3 million followers?
Being 1000 likes per day without repeating?
