### ISSUE TITLE
Unfollow not followers

### ISSUE THREAD

**Issue by emKaroly** [InstaPy/InstaPy#352]
How can i achieve this functionality?

**Comment by emKaroly** [comment]
If i think about it, it can be done with adding current followers to set_dont_include and let InstaPy unfollow as much it can. It would be nice if the [instagram-profilecrawler](https://github.com/timgrossmann/instagram-profilecrawl) could return the followers list also without going through all my post for advanced statistics.

**Comment by timgrossmann** [comment]
@emKaroly Well that's a hard and dirty get around 😄 
will work though

**Comment by wesleyabbey** [comment]
In order to get around this, I went to my followers on Instagram on my computer and then pushed all of them into a comma delimited string.

I pushed this string into a file called `followers.txt` and in my quickstart.py I read from that file. I can recreate this and post a solution or possibly try to create a script for this if enough people want it.

Edit: Actually it looks like we might linearly read from the python list of friends. I'm not sure about what sort of performance impact this might have for large enough friends list but maybe it could be worth exploring creating a dictionary instead of a list of friends?

**Comment by deronsizemore** [comment]
>I went to my followers on Instagram on my computer and then pushed all of them into a comma delimited string.

Can you explain how you went about this?

**Comment by datteba** [comment]
I'm also interested in this feature! I would like to unfollow users that are not following back **after more than 24 hours**.

Is there anyone who wants to contribute to a bounty to develop this feature quickly? 

@emKaroly @deronsizemore @wesleyabbey @timgrossmann

**Comment by converge** [comment]
#695 #581 #221 #707 -> all about this feature.

I'm working on it, and need some help ( #707 )

this is my progress:  https://github.com/converge/InstaPy/commit/c7897b9ddf376ecbf2ce6b5dd8df3530c8f5eba2

**Comment by converge** [comment]
1. I tried to scroll down until the bottom at "Followers" list, but it takes too long to complete and it does a lot of server requests. bad approach.
2. Now I'm getting just some pages at "Followers" list and adding it to a file, and telling unfollow() function to now unfollow usernames in this file.
3. I still need to update this file to remove users that aren't following me anymore, how could I do that ?

**Comment by pleum** [comment]
i try to get follower and following list by api that scroll down fetch, need some test: https://github.com/pleum/InstaPy/commit/883c36cdea73f7018a4b7d2e1febc3525e9a469a
