### ISSUE TITLE
Deploy to PyPi

### ISSUE THREAD

**Issue by timgrossmann** [InstaPy/InstaPy#3569]
#### In order to make InstaPy more friendly to integrate into other applications, we want to automatically deploy InstaPy to PyPi for easy install with `pip install InstaPy`.   
We also have to set up a GitHub Pipeline that will deploy InstaPy with every (Release|Version) for automatic updates of the PyPi entry.

Advantages of this feature:
- People working locally with InstaPy don't need to clone the repo from GitHub but can simply import it into their quickstart file everywhere on their device.
- Better tracking of downloads

Possible ways of achieving this while keeping control:
- Resolve #3567 which will remove the problem with the chromedriver, then set up a GitHub pipeline to do the deployment

> [Bountysource this Issue](https://www.bountysource.com/issues/67479147-deploy-to-pypi)

--- 

###### Feel free to comment with adjustments and improvements

**Comment by uluQulu** [comment]
O'la la bounties 🍭
Things get interesting 😋 here

I was thinking the same - to pin this thread but you are faster, @timgrossmann 😂
I agree that those 3 pinned threads has higher priority than many others, at the moment.

@timgrossmann @converge @sionking @CharlesCCC @GabrieleCalarota 
Before thinking about solutions, I would ask how do you think on these matters,
The situation being discussed would and will fairly require user level elevation - a super user or administrator or user with administrative privileges access in order to,
+ install packages by `pip` [may or may not - depends on python installation config]
+ off-thread but installing other external packages like chromedriver

The point is, as far as I know, currently without that higher-level resource access, users can get InstaPy to work, but to sort-of automate it, it must be considered.

So, what is your point?
+ How to design it in this regards?

Just a note that, most of the software of this kind requires that high-level access either while installing [one-time] or everytime [either while running or in background].


For me, preparing a solution safely will not harm. Just users will be notified that - "_Please, run [this portion] as sudo/admin_"..


---

Cheers 😁
---

**Comment by timgrossmann** [comment]
Thanks to @uluQulu we are now on PyPi! 🙌 🙌 
https://pypi.org/project/instapy/

And look at that name! Thank you very much to @gekitsuu for removing your project and allowing the InstaPy community to take over the official project on PyPi, we really appreciate it.

**Comment by timgrossmann** [comment]
#3887
