### ISSUE TITLE
BUG: can't like comments

### ISSUE THREAD

**Issue by sionking** [InstaPy/InstaPy#3594]
```
ERROR [2018-12-15 07:36:53] [xxx]  Error occured while liking a comment.
        b'Message: no such element: Unable to locate element: {"method":"tag name","selector":"button"}\n  (Session info: chrome=70.0.3538.110)\n  (Driver info: chromedriver=2.42.591088 (7b2b2dca23cca0862f674758c9a3933e685c27d5),platform=Windows NT 10.0.17134 x86_64)\n'
```
@uluQulu  @timgrossmann @CharlesCCC 
?

**Comment by sionking** [comment]
Bug is in line `comment_like_button = comment_line.find_element_by_tag_name('button')`

```

def like_comment(browser, original_comment_text, logger):
    """ Like the given comment """
    comments_block_XPath = "//div/div/h3/../../.."   # quite an efficient location path

    try:
        comments_block = browser.find_elements_by_xpath(comments_block_XPath)
        for comment_line in comments_block:
            comment_elem = comment_line.find_elements_by_tag_name("span")
            comment = extract_text_from_element(comment_elem)

            if comment and (comment == original_comment_text):
                # like the given comment
                comment_like_button = comment_line.find_element_by_tag_name('button')
                click_element(browser, comment_like_button)

```
Any assistance ? ( I am not an selenium expert)

**Comment by sionking** [comment]
@uluQulu thanks
BTW, 
changing to this line:
`comments_block_XPath = "//div/div/../../.."   # quite an efficient location path`

also did the work.

**Comment by uluQulu** [comment]
Hey @sionking 
Welcome, I've just looked at the page layout after your mention, and saw some changes I really did not expect at this soon time.

The thing is now the button of liking a comment is in a separate division at root level, so now we go one more level back to take the comment line blocks.

For people having this problem wanna **solve it manually**, just do this:
In **like_util.py** and **comment_util.py** files,
**replace**
```python
comments_block_XPath = "//div/div/h3/../../.."
```
**with**
```python
comments_block_XPath = "//div/div/h3/../../../.."
```

Or apply the changes from my commit for it- https://github.com/timgrossmann/InstaPy/pull/3460/commits/37028354b87058ba9a36b79d9b6393078c2ecd68 shared at my live PR #3460.

---


@sionking 
While looking to find an efficient way to find the element of comment [text], commenter [username] and the comment like button at once in harmony, I used the logic of getting a relative unique XPath location and then using backwards.

`//div/div/h3/../../../..` location is unique in that page and that's why I have used it for that purpose.
But, `//div/div/../../..` is not unique. It can cause a misbehaviour easily since a casual page contains tons of division inside division..

---

Cheers 😁
---
