### ISSUE TITLE
Got 0 likers shuffled randomly who you can follow: [ ]

### ISSUE THREAD

**Issue by andreescocard** [InstaPy/InstaPy#3855]
## Expected Behavior
I am using the script "Follow the likers of photos of users", expected behavior is to get the likers of photos

## Current Behavior
Getting 0 likers, showing empty array

## InstaPy configuration
Only using "Follow the likers of photos of users" and "Follow the commenters of photos of users" in this script

session.login()
session.set_relationship_bounds(enabled=False)
session.set_skip_users(skip_private=False)
session.follow_likers(['XXXXX' , 'XXXXX'], photos_grab_amount = 2, follow_likers_per_photo = 3, randomize=True, sleep_delay=600, interact=False)
session.follow_commenters(['XXXXX', 'XXXXXX'], amount=50, daysold=365, max_pic = 100, sleep_delay=600, interact=False)
session.end()

**Comment by panchoma** [comment]
Hello! I have the same problem, updated to the latest version of instapy and stop working the function "Follow the likers of photos of users". 
I have seen that previously there was a similar issue  #2476 that was solved it, but I think the solution is outdated. Since "commenters_util" is currently very different from the solution then. 

For example I can't find these lines: "//div/div/button[text()='Follow']")
username_url = person.find_element_by_xpath("../../*").find_element_by_tag_name("a").get_attribute('href')

@timgrossmann @uluQulu

**Comment by JoeFertig** [comment]
I have this issue on some accounts.
Any help or fix for this?
