### ISSUE TITLE
Got 0 likers shuffled randomly whom you can follow

### ISSUE THREAD

**Issue by unipython** [InstaPy/InstaPy#3866]
Just synced the fork and it was working fine until I tried implementing headless browser, one hour later the fix stopped working.

Error: Got 0 likers shuffled randomly whom you can follow

Any ideas?

_Originally posted by @unipython in https://github.com/timgrossmann/InstaPy/pull/2463#issuecomment-459321474_

**Comment by a-popov** [comment]
Same here, glad I found this. It opens up the dialog to the picture's likers and is unable to pull any actual instagram profile names from the dialog.

**Comment by unipython** [comment]
Found out that the minimum amount of pictures likers was set too small.

**Comment by spikeyhair** [comment]
My amount is set to 4 and previous doesn't have this problem. After pulling the latest version, this problem still there.

**Comment by unipython** [comment]
Try to update to the latest version it should do the job / sync fork

**Comment by panchoma** [comment]
Hello! I have the same problem, updated to the latest version of instapy and stop working the function "Follow the likers of photos of users". 
I have seen that previously there was a similar issue  #2476 that was solved it, but I think the solution is outdated. Since "commenters_util" is currently very different from the solution then. 

For example I can't find these lines: "//div/div/button[text()='Follow']")
username_url = person.find_element_by_xpath("../../*").find_element_by_tag_name("a").get_attribute('href')

@timgrossmann @uluQulu

**Comment by spikeyhair** [comment]
As stated in thread 
https://github.com/timgrossmann/InstaPy/issues/3737

you need just need to change the indentation in commenters_util.py.

look for these codes:
        user_list = get_users_from_dialog(user_list, dialog)

        # write & update records at Progress Tracker
        progress_tracker(len(user_list), amount, start_time, None)

just make sure they are one tab in front, same row with:
print('\n')
random.shuffle(user_list)
sleep(1)

**Comment by panchoma** [comment]
> As stated in thread
> #3737
> 
> you need just need to change the indentation in commenters_util.py.
> 
> look for these codes:
> user_list = get_users_from_dialog(user_list, dialog)
> 
> ```
>     # write & update records at Progress Tracker
>     progress_tracker(len(user_list), amount, start_time, None)
> ```
> just make sure they are one tab in front, same row with:
> print('\n')
> random.shuffle(user_list)
> sleep(1)

Thank you so much @spikeyhair !!!!!
