### ISSUE TITLE
failed to load desired amount of user

### ISSUE THREAD

**Issue by roncam82** [InstaPy/InstaPy#3911]
any help on this error. it happened after the last update

**Comment by cyberiainformatica** [comment]
+1

**Comment by roncam82** [comment]
and the follow is not working correctly ! it is looping on the same person

**Comment by gitpatrickhub** [comment]
@uluQulu has a fix for this in a PR #3910 I've test his fix on Raspberry Pi3 and it's working correctly.

**Comment by roncam82** [comment]
And I need to change the green parts ?

**Comment by oridamari** [comment]
> @uluQulu has a fix for this in a PR #3910 I've test his fix on Raspberry Pi3 and it's working correctly.

it didn't work for me.

**Comment by oridamari** [comment]
> @roncam82 @orisust just replace your whole unfollow_util.py file with this one from #3910
> Works for me!

sometimes the bottom of the dialog shows **'see all suggestions'** button and then i get
"Failed to load desired amount of users"

**Comment by ishandutta2007** [comment]
> > @uluQulu has a fix for this in a PR #3910 I've test his fix on Raspberry Pi3 and it's working correctly.
> 
> it didn't work for me.

Make sure you do the following:
1. check if you are on master branch of /timgrossmann/InstaPy
2. run `git pull`
3. check `git log` to see latest commit of there matches what you see on github master banch.
4. run `pip install instapy -U` (or `pip uninstall instapy` followed by `pip install instapy`)

**Comment by ishandutta2007** [comment]
> @roncam82 @orisust just replace your whole unfollow_util.py file with this one from #3910
> Works for me!

this is a hack , you shouldn't do that.

**Comment by tE3m** [comment]
@ishandutta2007 from now on, 
`Git` commands aren't needed for most users anymore, because they install and manage it via pip. That means that the old folder (where the github repo was at) *can* be deleted if the pip version is used, but it doesn't have to be. It's just important that scripts aren't run from inside the old folder anymore with that style, since that would call the `instapy` folder in the old `InstaPy` folder. So, long story short: updating happens via 
```
pip<version> install instapy -U
```
from now on, not git.
Or the other way. Only use git, not pip.

**Comment by ishandutta2007** [comment]
`pip install instapy` will install the latest version from pypy not the latest master from github. isn't it ?

**Comment by tE3m** [comment]
@ishandutta2007 yes.... it's recommended for most users to use `pip`.

**Comment by ishandutta2007** [comment]
@TarekJ03 How do you install the latest master pulled ?
