### ISSUE TITLE
wont unfollow anyone - every user is in don't include list

### ISSUE THREAD

**Issue by leviwinks** [InstaPy/InstaPy#3939]
## Expected Behavior
session.unfollow_users(amount=501, nonFollowers=True, style="RANDOM", sleep_delay=120)

## Current Behavior
Finds all users that I have followed, goes though each one and states didn't unfollow, user is in the dont include list. I've played with the unfollow_after command and doesn't do anything. Every now and then it might unfollow 1 or 2 users. Most of the followers in my list have been there for over 4 days.
## Possible Solution (optional)
How can i update the don't include list??

## InstaPy configuration

**Comment by gagna** [comment]
Hi @leviwinks if you switched to the new version of instapy maybe you don't copied the old `instapy.db` to the new workspace.

**Comment by CharlesCCC** [comment]
unfollow 501 each run seems a lots.  based on your description
"Every now and then it might unfollow 1 or 2 users. Most of the followers in my list have been there for over 4 days" 
You might have been soft-banned from unfollowing users. There is certain limit you can do each day. try to minimize that amount.

**Comment by leviwinks** [comment]
> unfollow 501 each run seems a lots. based on your description
> "Every now and then it might unfollow 1 or 2 users. Most of the followers in my list have been there for over 4 days"
> You might have been soft-banned from unfollowing users. There is certain limit you can do each day. try to minimize that amount.

Yeh 501 is alot, orignally i had it set to 75 and still wasn't working so i increased it to include my entire followers list just in case the 75 it was using were all in the dont include list - but still nothing.

**Comment by mpoliakov** [comment]
Same issue, I have older version (pulled few weeks ago) installed

**Comment by andreademasi** [comment]
Same issue on a fresh installation with pip

**Comment by gagna** [comment]
@leviwinks try to edit your `session.unfollow_user`

`session.unfollow_users(amount=501, allFollowing=True, style="RANDOM", sleep_delay=120)`

**Comment by leviwinks** [comment]
Did the workspace update and everythings come good cheers guys!

**Comment by tE3m** [comment]
@leviwinks so you can close this issue now? For everyone still having this: [Workspace migration](https://github.com/timgrossmann/InstaPy#workspace-folders)

**Comment by mpoliakov** [comment]
Did new install with `pip`; copied `db`, `logs` and `assets` folders into new location, still having the issue. Any help?

**Comment by MacroAnarchy** [comment]
"You will now find an InstaPy folder located at the above mentioned home folder. Simply copy and paste the content of your logs folder into that workspace folder in order to assure that all your data is migrated." 

What does this mean? Content of logs folder into workspace folder? just the folder with your account name inside logs folder directly into /instapy/ ? that doesnt seem right! and doesn't work for me.

**Comment by tE3m** [comment]
@blacksn0w13 the new Workspace also has a `logs` folder. You should simply move you current logs folder into the new workspace and replace the folder with your "old" one.

**Comment by MacroAnarchy** [comment]
Yeah I figured that.

My old Instapy folder always was at that Location, so I should have to change nothing, since it’s already there.
Still get the above error when unfollowing though. 
Is there no way to edit the dont_include list?

**Comment by tE3m** [comment]
How about `db`? That should also be migrated to the new workspace.

**Comment by MacroAnarchy** [comment]
Yeah but I always had my Github folder at 
Users/username/instaPy

And since the new default path is the same, I shouldn’t have to change nothing!?

(if the folder structure wasn’t changed, the migrating description sounds like it was, that’s why I asked, what you‘re saying means it wasn’t changed and should work right away)

**Comment by leviwinks** [comment]
Issue has re-appeared! using update!
Not unfollowed 'user'!	~user is in the list dont_include. This happens to everyone of the users it tries to unfollow :/

**Comment by MacroAnarchy** [comment]
Yeah me too, did clean install, copied everything as explained, database gets used normally but error still exists! 

Can’t say if my data was corrupted in some way though and if the error would appear with a fresh account. 

Had to switch to a different tool for unfollowing, that’s unfortunate because it doesn’t have the data when I followed and can’t do fifo now.

**Comment by leviwinks** [comment]
strangely works when you comment out the rest of the code and leave the unfollow part.

session.unfollow_users(amount=126, nonFollowers=True, style="RANDOM",
                           unfollow_after=42 * 60 * 60, sleep_delay=300)

**Comment by digiboons** [comment]
I am having the same problem. It was working 2 days ago but now it says that  
`~user is in the list dont_include`

My settings 
```

 session.unfollow_users(amount=70, InstapyFollowed=(True, "nonfollowers"),
                           style="FIFO",
                           unfollow_after=24 * 60 * 60,
                           sleep_delay=600)
```

I haven't changed anything about the work environment 

Any idea Please otherwise it will ruin my Instagram account! 

How did you solve the problem @leviwinks

EDIT:

It works under this configuration 

`InstapyFollowed=(True, "all")`
 
EDIT 2 :

`InstapyFollowed=(True, "all")`  This works partly 

Thanks in advance

**Comment by Sap3W** [comment]
I had the same issue
`Not unfollowed '*********'!   ~user is in the list dont_include`

in my case, the probleme come from the blacklist, you need to desactive it
