### ISSUE TITLE
Using database for blacklist instead of .csv file

### ISSUE THREAD

**Issue by andreademasi** [InstaPy/InstaPy#3964]
Looking at the code i noticed that Instapy uses a .csv file to store blacklisted users. Can't this be more efficient by using a database (maybe with an ORM like sqlalchemy the entire database logic can be refactored)? I can work at this but i'm a beginner developer so i cannot ensure anything.

**Comment by antwal** [comment]
I'm developing a separate version, where I already integrated sqlalchemy with support for sqlite3, mysql; currently I have not published the changes since they are still developing instapy with a non-dynamic structure. As soon as possible and if the support for python 3.5 versions is completely removed, I push the changes.

**Comment by sionking** [comment]
@antwal this sound great.
Please just consider small PRs as ppl here have modified version of instapy.

**Comment by antwal** [comment]
> @antwal this sound great.
> Please just consider small PRs as ppl here have modified version of instapy.

unfortunately it is not a small PR, all the changes I made are based on commit 93cf663; all you have added after is to be fixed. Currently I have made changes to you to manage multiple accounts in the application on a recent commit (PR #3840) but the introduction of the workspace is a huge problem so it has been totally removed like other things. I work there alone and you are many, so it is convenient that you publish a separate repository and then in the future you will see how to integrate things

**Comment by ccook22** [comment]
Following
