### ISSUE TITLE
Error in run mac_start.command

### ISSUE THREAD

**Issue by FullHeleno** [InstaPy/InstaPy#4056]
Traceback (most recent call last):
  File "quickstart.py", line 3, in <module>
    from instapy import InstaPy
ImportError: No module named instapy

**Comment by timgrossmann** [comment]
@FullHeleno Have you executed the installation before?

**Comment by Edin-Top** [comment]
Hi, I have the same problem. I tried to run the installation (from the QuickStart folder) a second time then I got this message:

Could not install packages due to an EnvironmentError: [Errno 13] Permission denied: '/Library/Python/2.7/site-packages/enum34-1.1.6.dist-info'
Consider using the `--user` option or check the permissions.

**Comment by FullHeleno** [comment]
> @FullHeleno Você já executou a instalação antes?


TY for the feedback, I decided to install python3 and pip3, now it is running fine in vscode

**Comment by FullHeleno** [comment]
@Edin82 See my answer above, and solve your problem too.

**Comment by zacjuntan** [comment]
Hey guys, I'm having the same issues as you previously were. I tried installing python3 and pip3 but it didn't solve the issue. I'm running on a Macbook Pro with the latest Mojave os.

Currently when I try to run mac_start.command I get the error "ImportError: No module named instapy"

And when I try to reinstall instapy using the install.command from the quickstart folder, I get the error "Could not install packages due to an EnvironmentError: [Errno 13] Permission denied: '/Library/Python/2.7/site-packages/enum'
Consider using the `--user` option or check the permissions." 

as well as "clarifai 2.5.2 has requirement jsonschema<3,>=2.5, but you'll have jsonschema 3.0.0 which is incompatible."

I'm new to anything coding related, so any help would really be appreciated :)

**Comment by zacjuntan** [comment]
@Edin82 did you end up resolving this?

**Comment by sbug51** [comment]
@timgrossmann @Edin82 @zacjuntan I tried the earlier solution, I am still met with the same error when installing, Pip3 installation didn't work... I am not an expert, but I tried the advanced install for instapy, resulting in the same error.

> clarifai 2.6.0 has requirement jsonschema<3,>=2.5, but you'll have jsonschema 3.0.1 which is incompatible.

and

> Could not install packages due to an EnvironmentError: [Errno 13] Permission denied: '/Library/Python/2.7/site-packages/enum' Consider using the `--user` option or check the permissions.

Help would be highly appreciated.

Thank you,
A

**Comment by zacjuntan** [comment]
@sbug51 hey! Ok, so I tried @timgrossmann ‘s suggestion of using the terminal command: 

sudo pip install instapy --ignore-installed 

And it worked! Give that a shot and let me know what happened.

**Comment by zacjuntan** [comment]
It might still give you the clarifai error, but it works regardless, as long as it doesn’t give you the environmenterror you should be fine
