### ISSUE TITLE
NOT COMMENT

### ISSUE THREAD

**Issue by TheXeon81** [InstaPy/InstaPy#407]
today the script in docker version... works... but not comment.... :-(

**Comment by onyxim** [comment]
There are no changes in comments sections in new docker architecture. And it works as I can see. 

But , I am currently working on new version of InstaPy with new global limits settings (based on schedule mechanism) including for comments. I hope to release it during 1 or 2 next weeks. Stay tuned! 

So if it  really doesn't work in Docker, I'll fix it soon or later. Because Docker is the most breakthrough technology for development in the last few years.
