### ISSUE TITLE
Running all with Docker Compose using config file - Page not found

### ISSUE THREAD

**Issue by jwpwhite** [InstaPy/InstaPy#4099]
Any ideas why the "Running all with Docker Compose using config file" URL is giving a 404 Page not found error?

**Comment by Herrox** [comment]
It looks like the documentation is not up to date
You could use the below commands:

- Start all the containers (`selenium` + `InstaPy`)
`docker-compose up -d --build`
- Start only `selenium` container
`docker-compose up -d --build selenium`
- Start only `InstaPy` container
`docker-compose up -d --build web`
- Stop all container
`docker-compose stop`
- Stop only `selenium` container
`docker-compose stop  selenium`
- Stop only `InstaPy` container
`docker-compose stop web`
- Stop and remove Docker configs for all containers
`docker-compose down`

**Comment by converge** [comment]
For me it's just:

1. setup the docker_quickstart.py

2. ```docker-compose up -d --build``` to start the container

3. ```docker ps``` to get the container ID

4. ```docker logs _container_id_ -f``` to check the logs

Can someone confirm it ? So we can update the docs.

**Comment by Herrox** [comment]
@converge 
For point 2. the command start two container (`selenium` and `InstaPy`), not just one.
For point 4. you also could directly do `docker logs -f instapy_web_1` or `docker logs -f $(docker ps -a | grep instapy | cut -d " " -f 1)`. This will output all the logs so you could add option `--tail 50` for displaying the last 50 lines

It might happens you just want to start/stop/... `InstaPy` container, for exemple if you run quick actions. `selenium` container will still be up but not `InstaPy` container. It exit after finishing running the script, so you could juts restart it with `docker-compose up -d --build web`.  That's why I add some additionals commands
