### ISSUE TITLE
Login without username/ password

### ISSUE THREAD

**Issue by tobeyond** [InstaPy/InstaPy#4151]
## Expected Behavior

I would like to login to my account using only the session id (I've seen it in a website and a golang script, but I don't know how to translate it to Python), without my username and password information.
Is it possible to add this feature?

Thank you.

**Comment by CharlesCCC** [comment]
I believe you are reference cookie, which InstaPy already using. 
You only need the username/password once, then you don't need the password again  for 3 months,  (username is needed of course which can be hard-coded as well.)

**Comment by bugre** [comment]
As CharlesCCC correctly comments, InstaPy already (by default) saves a session cookie.  So you'll have to run the script once with your credentials, that should create the cookie file, after that you can change you're password to a fake one. You can not remote/empty it, because the script does a check on it. But while the cookie is valid, the login process will work without problem, until the cookie needs to be reevaluated.
