### ISSUE TITLE
Order of items in quickstart?

### ISSUE THREAD

**Issue by deronsizemore** [InstaPy/InstaPy#418]
```
InstaPy(username='#', password='#') \
    .login() \
    .set_do_follow(True, percentage=60, times=1) \
    .set_lower_follower_count(limit=50) \
    .like_by_tags(like_tags, amount=25) \
    .end()
```

So I've got the above basic options. When I run the script, it starts working and does its thing but it looks like it start going through and liking photos first rather than following. Wouldn't it go through and follow users first since that's first in the list of items?

**Comment by timgrossmann** [comment]
@deronsizemore Good question!

Well not exactly...
all the `.set_something` methods only define what should happen when the run `.like_by_something` is called.
So the actual liking/following and so on only starts with the `.like_by_something` calls.

So you are only defining options there. It's like this:

```
For every tag in like_tags I want to like 25 posts, 
I want to follow every posts owner with a 60% chance but only do that once. 
I also want to check whether the owner of the post has more than 50 follower

**Comment by deronsizemore** [comment]
Ah, thanks. That makes sense now.

>with a 60% chance

Can you explain that further? I'm sorry, I'm not sure I ever really understood what was meant by that percentage parameter and "with a 60% chance" seems even more confusing to me. I'm sure I'm just missing something obvious.

**Comment by timgrossmann** [comment]
@deronsizemore Well I hope to be able to, I don't really understand what you don't understand.

It's pretty simple, if you ever observed the behaviour of the script, you can see that it's going through the amount of images you provided.
For every image it likes, it will draw a "random" number and if that random number is smaller than your percentage, the account will be followed/commented.

60% means just that on average you follow ~6 accounts out of 10. Since it's random, it's not completely accurate all the time, but around that.

If that didn't clear things up, you have to explain what you don't understand.

**Comment by deronsizemore** [comment]
@timgrossmann Ah, ok. That makes sense. Sorry for my ignorance. I tend to overthink things. :)

**Comment by timgrossmann** [comment]
@deronsizemore No problem 😉
