### ISSUE TITLE
Clarification of documentation

### ISSUE THREAD

**Issue by RealMakAttak** [InstaPy/InstaPy#419]
Hello all and @timgrossmann ,

I am just wondering how InstaPy does it's counting - I tried looking over the documentation but couldn't find anything. If you would be so kind as to explain the result of the following settings it will answer all questions:

1.  bot.like_by_tags(['x', 'y'], amount=10)

does that mean 5 for x and 5 for y or 10 for x and 10 for y?

2. bot.set_upper_follower_count(limit=500)

if InstaPy goes on to a profile and finds that follower_count > 500 and therefore doesn't like it, does this count to the total amount of "likes", or is it only when something is liked that the total amount of likes made goes up?

Sorry these questions may be elementary.

**Comment by timgrossmann** [comment]
@RealMakAttak 

**For every tag it likes the given amount of pictures**... in your case 10 for x and 10 for y.

Well, right now it's "*take a look at 100 pics*" which means if 15 of these 100 pics are inappropriate or not to be like because of too many followers, then the script will only like 85 pics and stop then.

This will be part of InstaPy_V1 to make sure if you want to like 100 pics, the script will continue until you got 100 😉

**Comment by RealMakAttak** [comment]
@timgrossmann 

Thank you for your reply. The change from "take a look..." to "like x amount" will be much welcomed. 

Thanks again.
