### ISSUE TITLE
running instapy in AWS ec2 with my ip address

### ISSUE THREAD

**Issue by ghost** [InstaPy/InstaPy#4208]
Hello friends :)
How can I run the bot on EC2 AWS with my private IP address? 
when I run it regular instagram knows that it is from us and I worrying that they will ban me...
thanks.

**Comment by Herrox** [comment]
This is not possible easily. EC2 instance have their own IP address. Or you need to config a larger infrastructure with VPC, firewalling, routing, tunneling/Direct Connect...

In my opinion, there is no need to have such kind of configuration where only your public access Instagram because when using Instagram on your smartphone, your public IP is changing...

**Comment by ghost** [comment]
so its ok that they send me messages like "there is a new connection from (other country) to your account"? they won't ban me?
thanks.

**Comment by Herrox** [comment]
To be honest, I can't confirm they will not ban you. It will also depends on what you will do (likes, comments...). AWS have many regions, try to use the one closer to you. Otherwise, you will have to do some (advanced) routing & firewalling

**Comment by mheubaum** [comment]
I started my AWS in my country (I don't know whether its possible in yours too). So it has a german IP. I think this way would be better for you.

**Comment by andifds** [comment]
I currently use it on many servers from US (Mainly in California) but all my accounts are based on Chile. After a few tries, login codes or app authorizations there's no more problem to login. Also you don't get banned for logging in from another country, if you use the bot in excess probably you will get banned even if it's under your own home ip

**Comment by ghost** [comment]
thank you guys :)
