### ISSUE TITLE
can you help me on the below error please ?

### ISSUE THREAD

**Issue by roncam82** [InstaPy/InstaPy#4298]
## Current Behavior
![image](https://user-images.githubusercontent.com/46320963/55936197-e8301c80-5c35-11e9-9d67-18c3c58258b1.png)

**Comment by Minnen** [comment]
Your issue is the version compatibility among the binaries you are using.

Your chrome driver version according to your capture is **2.36** and your chrome version is **65** now accordint to chromedriver 2.36 release notes, which can be found [here](https://chromedriver.storage.googleapis.com/2.36/notes.txt), those two are compatible and you didnt provided info about other aspects like your Selenium version, so by process of elimination i have no other choice but to advice you to upgrade your Selenium to **v3.9** from [here](http://selenium-release.storage.googleapis.com/index.html?path=3.9/) but keep in mind that other thins might be triggering the incompatibility issue like your JDK installation.

Do a system a reboot before atempting to run your test again.

Hope this solves your issue.
