### ISSUE TITLE
Reducing Inauthentic Activity on Instagram

### ISSUE THREAD

**Issue by IKDH** [InstaPy/InstaPy#4326]
## Current Behavior

Hi,

Did anyone received this message from Instagram ? I have received this message 2 days ago.
![Capture](https://user-images.githubusercontent.com/30605776/56125178-9d394080-5f78-11e9-94d6-e340eb194829.PNG)

**Comment by kev-mas** [comment]
Where are you running Instapy? On a VPS or any type of hosting which does not share the same Location/IP which you usually have at home/office?

**Comment by IKDH** [comment]
On a VPS.

**Comment by mgconejero** [comment]
Same here in two different accounts. Both are running in AWS, but im not from the US... you are saying that is the problem @LunaticZorr ?

**Comment by lezlea** [comment]
I just started using proxies on my accounts in the same country I'm in (rather than AWS server IPs) and a few days later all accounts received this notification.  The proxies are from Blazing which was recommended on here.  I'm not sure if it's a coincidence as I've seen a lot of people see the notifications in the last week or so, or if the proxies aren't good!?
