### ISSUE TITLE
Unfollowing does not unfollow in headless

### ISSUE THREAD

**Issue by LeakDev** [InstaPy/InstaPy#4397]
## Expected Behavior

Had a script run that followed 58 users. My unfollow script should unfollow these exact people again.

## Current Behavior

InstaPy only unfollowed 32 people - I have to unfollow the rest manually in the app on my phone, which works just fine and is even faster than InstaPy as of now

Logs give the following output on session end:
|> UNFOLLOWED 58 users

## InstaPy configuration

I have headless enabled (since I run this when actively using the computer)

with smart_run(session):
    session.set_simulation(enabled=False)
    session.unfollow_users(amount=1000, InstapyFollowed=(True, "all"), style="RANDOM", unfollow_after=1, sleep_delay=5)

**Comment by rosinbum** [comment]
You are probably running into a shadow unfollow issue where IG tells the browser that the user is unfollow but it doesn't actually do it. You should use the quota limiter to reduce the number of server calls per hour and the number of unfollows per hour. 

A sleep delay of 5 (seconds) is not nearly long enough. Try something closer to 400-600. And unfollow after a few days not 1 second. 

Additionally setting `session.set_simulation(enabled=False)` increases the likely hood that instagram will ignore your unfollow request because it will recognize that this is a bot.

IG will never let you unfollow 1000 users in a 24 hour period so pick something more reasonable. Remember its best to start slow with low numbers and long delays

example
```
    session.set_quota_supervisor(enabled=True,
                                 sleep_after=["likes_h", "follows_h", "server_calls_h", "unfollows_h"],
                                 sleepyhead=True, stochastic_flow=True,
                                 notify_me=True,
                                 peak_likes=(80, 300),
                                 peak_comments=(21, 250),
                                 peak_follows=(40, 300),
                                 peak_unfollows=(40, 300),
                                 peak_server_calls=(500, None))


    # unfollow activity
    session.unfollow_users(amount=100, InstapyFollowed=(True, "nonfollowers"), style="LIFO",
                           unfollow_after=5 * 22 * 60 * 60, sleep_delay=500)
```

Finally there are some know issues related to chrome-driver and unfollowing. Try using firefox instead https://github.com/timgrossmann/InstaPy/blob/master/DOCUMENTATION.md#switching-to-firefox

**Comment by LeakDev** [comment]
I run the script at will which is why I have unfollow_after set to 1. The amount is also set to 1000 to catch all accounts I followed (since I don't run the unfollow daily) - I follow 100 to 150 people a day at most.
I don't think the sleep_delay of 5 seconds is problematic either, since I can unfollow 2-3 people a second if I were on my phone (which is what I have to resort to anyways as of right now).

Sadly, switching to Firefox did not fix this issue either. I started at 419 following, it reported 73 unfollowed, but I ended at 382 instead of the prognosed 346. I could still unfollow the remaining InstaPy-followed without any issues manually.

**Comment by someralex** [comment]
try:

headless_browser = False

**Comment by matteool** [comment]
The unfollow from web is limited to 10 unfollow every 10 minutes. Use sleep delay 601

**Comment by ortegafernando** [comment]
After some days without doing anything, yesterday I have restarted gain and it seems to work again. temporaly banned?

**Comment by LeakDev** [comment]
@matteool Indeed, setting sleep delay to 601 helped regardless of browser mode. Closing.
