### ISSUE TITLE
Add a GUI for the setup of the quickstart file

### ISSUE THREAD

**Issue by timgrossmann** [InstaPy/InstaPy#44]
#### Would be nice if you could setup the wanted configuration through a simple GUI instead of writing text into a textile.

- [x] build a basic GUI
- [x] *for the beginning* add some of the features of InstaPy to the GUI
- [x] create a "quickstart.py" file out of the given params of the GUI

**Comment by komad1na** [comment]
I am on it :+1: :)

**Comment by littleswany** [comment]
https://github.com/Nemixalone/GUI-tool-for-InstaPy-script

@timgrossmann or @Nemixalone Looks like this issue is sorted so can be closed?

**Comment by timgrossmann** [comment]
@littleswany Problem is, that GUI is only for windows users 😉 
Would be awesome if someone could build like a web GUI or something platform independent

**Comment by littleswany** [comment]
@timgrossmann With you on that, on the other repo I commented saying because I am on OSX I couldn't test.

I will look into doing something like a web GUI, would it downloading a .py file be something that could work, if so I can do it with relative ease.

**Comment by komad1na** [comment]
Or I could (try*) to switch to QT (C++) instead of C#.

*try - cause never done that in C++ but why not try it right, it's all about learning :)

Or web GUI however i'll try to contribute.

**Comment by timgrossmann** [comment]
@Nemixalone Do whatever you can!
It'll definitely will be useful!

**Comment by komad1na** [comment]
I will do my best.

**Comment by sdiepend** [comment]
@timgrossmann I'm trying to build a web gui using flask(I want to do more than just generate a quickstart.py file), but currently running into trouble. I import the InstaPy in a view class but when trying to instantiate an InstaPy object it says

> FileNotFoundError: [Errno 2] No such file or directory: './logs/logFile.txt'

Which is normal because relative from my view class there indeed isn't an ./logs/logFile.txt.

So I'm thinking that logging should move outside the repo to an appropriate system location. It would also probably be better to use the Logger module from the standard python library.

For persistent data in the JSON files, maybe something like discussed here:
https://stackoverflow.com/questions/1011337/relative-file-paths-in-python-packages
https://stackoverflow.com/questions/30660003/unable-to-import-text-file-with-python-module

I can try and have look at using Logger when I have time.

**Comment by timgrossmann** [comment]
@sdiepend Sounds great!

Yes, I think that's an important advancement of the script to improve the logging here... 
Sorry for the problems.
