### ISSUE TITLE
Invalid urllib requirement in docker image

### ISSUE THREAD

**Issue by ribtoks** [InstaPy/InstaPy#4421]
Default docker-compose fails to start instapy because of wrong versions of urllib and clarifai

```
requests 2.21.0 has requirement urllib3<1.25,>=1.21.1, but you'll have urllib3 1.25.2 which is incompatible.
clarifai 2.6.1 has requirement jsonschema<3,>=2.5, but you'll have jsonschema 3.0.1 which is incompatible.
```

## Expected Behavior
InstaPy starts
## Current Behavior
InstaPy fails to start
## InstaPy configuration
`docker-compose up`

```
Creating network "instapy_default" with the default driver
Creating instapy_web ... done
Attaching to instapy_web
web_1  |
web_1  |  ._.  ._.  ._.  ._.  ._.  ._.  ._.
web_1  | Workspace in use: "/code/InstaPy"
web_1  | /usr/local/lib/python3.7/site-packages/requests/__init__.py:91: RequestsDependencyWarning: urllib3 (1.25.2) or chardet (3.0.4) doesn't match a supported version!
web_1  |   RequestsDependencyWarning)
web_1  | Traceback (most recent call last):
web_1  |   File "/usr/local/lib/python3.7/site-packages/urllib3/connection.py", line 160, in _new_conn
web_1  |     (self._dns_host, self.port), self.timeout, **extra_kw)
web_1  |   File "/usr/local/lib/python3.7/site-packages/urllib3/util/connection.py", line 57, in create_connection
web_1  |     for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
web_1  |   File "/usr/local/lib/python3.7/socket.py", line 748, in getaddrinfo
web_1  |     for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
web_1  | socket.gaierror: [Errno -2] Name or service not known
web_1  |
.........
instapy_web exited with code 1
```

**Comment by notvexxed** [comment]
I'm getting the same/similar error using the Quickstart.

Running the install.bat file I get the following error:
`Downloading https://files.pythonhosted.org/packages/81/ca/295515dff932fc41cdcb7c80babbba7fe96643d16ce34211fff0ecd48528/googleapis-common-protos-1.5.10.tar.gz requests 2.21.0 has requirement urllib3<1.25,>=1.21.1, but you'll have urllib3 1.25.2 which is incompatible. clarifai 2.6.1 has requirement jsonschema<3,>=2.5, but you'll have jsonschema 3.0.1 which is incompatible.`

Thereafter, running the quickstart.py results in the following error:
`usr\Local\Programs\Python\Python37\lib\site-packages\requests__init__.py:91: RequestsDependencyWarning: urllib3 (1.25.2) or chardet (3.0.4) doesn't match a supported version! RequestsDependencyWarning)`

**Comment by Herrox** [comment]
I don't have any problem starting `InstaPy` even with this warning, but I don't use these libs nor the `InstaPy` functions using them.

What is your quickstart configuration?

**Comment by notvexxed** [comment]
> 
> 
> I don't have any problem starting `InstaPy` even with this warning, but I don't use these libs nor the `InstaPy` functions using them.
> 
> What is your quickstart configuration?

I managed to fix the error. I'm no expert so maybe my solution can be streamlined but this is how I did it:
In the quickstart folder containing the files 'Install' and 'Update', I created a new requirements.txt document which contains the code:
`urllib3==1.24.1`

On Command prompt I typed: (First use cd to get to where requirements.txt is saved before typing the code below)
`pip install -r requirements.txt`

This fixed the urllib error.

To fix the JSON error I simply typed:
`pip install jsonschema==2.6.0`

Now all the errors are cleared. I'm sure there's a better way of doing this but I'm a newbie to this so that's why it's not such a streamlined solution. I hope this helps OP.

**Comment by Herrox** [comment]
@notvexxed 
Yes all this packages are managed by `requirements.txt`. I saw the error awhile ago but didn't had any problem running instpay but it looks like you guys have so time to fix it has come :)
Feel free to create a PR, I haven't had enough time to do it for now.

**Comment by ribtoks** [comment]
Looks like nobody is using Docker since nobody else is complaining that it is still not working.

**Comment by Herrox** [comment]
@ribtoks There is a lot of people using docker, but like I said previously it's not a problem with Docker or related to Docker. This error come from packages that are dependencies for `Instapy`, which are managed by `requirements.txt` file.
You could find more details about this error in this issue : #4427 
Following @timgrossmann answer the problem seems more complicated to address than ust updating the package but maybe we are worng and you just have to propose a PR

**Comment by ribtoks** [comment]
@Herrox I didn't say the problem is **in Docker**. If you're using InstaPy without docker, you can easily patch `requirements.txt` in notepad. If you're using docker, you have no other choice but to consume dependencies from `pip install`

**Comment by Herrox** [comment]
I know, just feel free to create a Pull Request with the new version of the dependencies, and all the version - Docker or classic - will be patch in the next release.
