### ISSUE TITLE
Amount is not the desired amount

### ISSUE THREAD

**Issue by bjspi** [InstaPy/InstaPy#4459]
```
    accounts = ['list_of', 'accounts']
    session.set_relationship_bounds(enabled=True,
                                    min_followers=70,
                                    potency_ratio=-1.2,
                                    min_posts=10)
    session.follow_user_followers(random.sample(accounts, 1), amount=20, randomize=True)
```

## Expected Behavior
It should follow 20 users of one of the accounts given in the list above.
I know there are a lot of accounts which dont satisfy the potency_ratio=-1.2, but I would expect the bot to grab as many usernames and check their profiles until it has found enough profiles to have followed 20 users.

## Current Behavior
It grabs 20 users and check every of them whether potency_ratio is fullfilled.
So from 20 accounts, maybe 4 will fullfill it, hence in the end the bot has followed only 4 instead of 20 accounts. The same goes for liking pictures, e.g. when using delimit_liking() to skip pictures with more than X likes already.

## Possible Solution (optional)
Always when some condition is not fullfilled it should not be counted as followed.

## InstaPy configuration
Doesnt matter.

**Comment by mheubaum** [comment]
> Always when some condition is not fullfilled it should not be counted as followed.

I would like this feature too. Maybe the topic 'follower sources' should be reviewed.

**Comment by synchronizing** [comment]
I agree with this as well -- needed config.

**Comment by bjspi** [comment]
Amount currently is the amount of initially grabbed pictures, which are only afterwards "computed" whether they meet the pre-conditions :(

**Comment by bjspi** [comment]
@timgrossmann @uluQulu 
Any way of implementing this or any workaround?
I want to follow exactly 100 profiles with a certain potency_ratio but it's simply not possible because amount=100 is the initial amount of grabbed profiles which will only AFTERWARDS be scanned :(

**Comment by mick-net** [comment]
I have the same issue, but what I'm also wondering is if the quota supervisor checks the amount of processed links or the actual interactions? So if I do a follow by location with an amount of 20, and instapy marks 3 users ass valid users. Will the quota supervisor count this as 20 or as 3?

**Comment by uluQulu** [comment]
@vermaat 
QS is logically smart; And works as expected.

It records only the verified follows. Yes even if it finds the user a valid and clicks on follow button but then it can't verify that follow (out of certain reasons) and then it will not record that follow.

There are 20 users to be followed by location and it iterated over the users and in final - found only 3 users valid to be followed and it really followed those 3 users. 
That means:
- Only 3 follows has been recorded that QS will count on.
- Every server call spent while trying to follow all of the 20 users has all been recorded. And QS will count on them.
- Etc.

So, the logic is as is and is simple, ain't?

>**Hint**: QS works with action engines rather than feature blocks. To be explained, there are tons of features that do follow - e.g. _follow by locations_, _follow by tags_, _interact by user followers_ etc.
And there is a follow engine located in **unfollow_util.py** file which is a function called - `follow_user()`.
Every single feature that needs to send a follow action calls that generic follow engine.
And all of the actions have such generic engine.
So, QS simply stands just behind the door of those action engines and supervises easily per pre-defined quota 😎



Gratitudes 🙂
---

**Comment by uluQulu** [comment]
@bjspi @synchronizing @discreated @vermaat 
It's by design out of effectiveness and to avoid misbehaviours.
But e.g. I remember there are features like like by feed which relies on your desired logic - "amount must be fulfilled".

Why it is not effective to be defaulted in all features?
- Such as, it simply can stuck in endless loops very frequently in scenarios where the actual amount is less than requested amount.
- Lots of inappropriate cases might require feature last too long that consequently affects the workflow which can cause unwanted behavior and also spend tons of server calls the user may not like, at all.

But now I think to fulfill user's request like yours, there can be added a new generic or feature-wide parameter to define that case; E.g.:
```python
# feature-wide?
follow_user_followers(fulfill_amount=True)
# or generic
set_do_follow(fulfill_amount=True)

# or more generic
InstaPy(fulfill_amount=True)

# etc.
```
Feature-wide is more controllable, though. Far better option.
In any case, if implemented, there should be added some smart loop breakers to avoid excessive runs and wasting bunch of server calls.

@discreated 
If it is not followed, it will not be counted as followed.
It just runs in an iteration - e.g. 100 users taken and then tries to follow them one by one:
- It followed? Cool, record the successful entry to DB (and etc.), go next one (if any).
- It did not follow? Fine, go next one (if any).


Gratitudes 🙂
---
