### ISSUE TITLE
Quota exceeded with pod

### ISSUE THREAD

**Issue by maxxfly** [InstaPy/InstaPy#4463]
Hi...
I have an issue with the use of pod.
Currently, when I try to connect to the pod, I have the error: "Quota exceeded"

If I use the endpoint : ```https://us-central1-instapy-pods.cloudfunctions.net/getRecentPosts?topic=general```

I have the same issue...

I try to access a this endpoint through a VPN but I have the same issue...
Idem with a different topic for example *beauty*

**Comment by nicholaai** [comment]
facing a similar issue

```
INFO [2019-05-21 14:13:10] [acc]  Downloaded postids from Pod general:
ERROR [2019-05-21 14:13:10] [acc]  {"code":8,"metadata":{"_internal_repr":{}},"details":"Quota exceeded."}
INFO [2019-05-21 14:13:10] [acc]  Downloaded pod_post_ids : []
```

**Comment by CharlesCCC** [comment]
@ishandutta2007 Any help here ?

**Comment by ishandutta2007** [comment]
This is not an issue, this is by design, Quota exceeded simply means we have filled up the free tier limits on Google Cloud/Firebase.  It doesn't harm anyone, it fails gracefully without impacting rest of your script. Let the luckly 200-250 posts per day grab the eye balls. We didn't expect to get this large usage at the outset even. If there are enough users who want to pay for pod server maybe we can think of something or else it's just fine.

**Comment by maxxfly** [comment]
I am ready to pay for that. But I am afraid that the interest can be reduce because the count of pod's members will be reduced.
It is a complicate question. 

I wonder if heroku as free hosting could be a better hosting solution.

**Comment by CharlesCCC** [comment]
@maxxfly It is great that you willing to pay for it. 
@timgrossmann @ishandutta2007 Maybe worth to set-up some sort of payment mechanism through  here https://opencollective.com/instapy and then use the fund to spin up a more powerful instance to support more user ?  (free tier with limit quota could still running in parallel, paid version without limit of course)

**Comment by ishandutta2007** [comment]
Another idea was to host each topic in a separate server once we get sufficient traffic . Currently 95% of posts are uploaded under 'general' topic and a few in 'food' and 'sports'. The usage of general is high primarily because it's the default. So let the 'general' continue to be hosted at https://us-central1-instapy-pods.cloudfunctions.net and let's create separate servers for each of the other topics. We can do like this, each server should have help.instapy@gmail.com as one of the admins and also two other individual's mail as other admins who will be primary moderator for that topic and should be for responsible for all issues on those servers and also responsible to market that topic to get enough members in that niche.

I prefer this route in near term as it would force people to choose their niche than blindly keep using general and when each of those topics also gets filled up we may think of payments meachanism etc.

@timgrossmann whar do you say?

**Comment by ishandutta2007** [comment]
> I wonder if heroku as free hosting could be a better hosting solution.

By server I mean cloud functions + DB. Firebase's freetier DB limits of 10GiB/month bandwidth , 20K/day writes and 50K/day reads are the most generous that I know of.

In heroku Freetier DB , it has 10k rows(hopefully unlimited read/writes since it doesn' mention it anywhere). and hosting of dynos is free for 1000hrs/month(I dont know what it means, it doesn't talk about bandwidth anywhere, If you know any app on heroku freetier with substantial traffic ie atleast 1000+ daily active users you can tell me, i'll check)

**Comment by maxxfly** [comment]
About the idea to split every topic on a server, I think that the risk is everybody avoid the general topic but no other topic match with the instagram account "bizness". And every one request for a new topic so increase of topics and servers

**Comment by ishandutta2007** [comment]
> risk is everybody avoid the general

@maxxfly I will be glad is that happes,  the reaoson I say that it's never going to happens is number of people people using pods unknowingly is always going to be more that people who has thoughly programmed for it.

> And every one request for a new topic
Currently we allow only 6 topics are are going to allow on those in InstaPy client offically.

**Comment by AKwoKWH** [comment]
How about changing to Realtime Database, which there are No Quota for read and write.
It only have quota for data usage.

https://firebase.google.com/pricing
GB stored: 1G
GB downloaded: 10G per month
