### ISSUE TITLE
Do not  unfollow who has liked you feature request.

### ISSUE THREAD

**Issue by NewyorkDev** [InstaPy/InstaPy#448]
Should be an option to not unfollow people who have liked your pictures also known as ghosts

**Comment by jeffreylm** [comment]
Yes, I think this is a good option to have. Also to not to unfollow your active users, because at the end of the day if you can have an account with users that are for the majority active commenting, liking and sharing. Instgram algorithm will no doubt notice your accounts ratio. I can't imagine it won't. This can lead to new nice things from instagram. 

Say if you could get the sccript to look at all your post and get all the accounts that has ever commented on your post, then look at the frequency of all the users commenting, then look at the frequesncy of all the likes they have given. And maybe look at the how often, and assign a weight to there account. That can be used as a means to decide who is more valueable than the other users.

What would also be handy if you are able to tell the script which activity bears more weight with you. So the argument could look like this for a like bias : (Like, Comment, frequencyOfInteraction)
And a comment bias would then naturally look like this: (Comment, FrequencyOfInteractio, Like)
And the order being the bias level.


So there definiately needs some sort of intelligence in the unfollow when it comes to your high value followers.

**Comment by converge** [comment]
It's a great feature, let's work on it.

**Comment by converge** [comment]
the feature is alive #781
