### ISSUE TITLE
i help uff

### ISSUE THREAD

**Issue by eugeniasimona1981** [InstaPy/InstaPy#4528]
## InstaPy configuration

a me servirebbe un quickstart.py simple..
ogni giorno segue 1 or two tags
like, follow, comments, unfollow... time 5 seconds or più 

tipo:
session.follow_by_tags(["salento2019", "brina"], amount=50)
session.like_by_tags(["salento2019", "brina"], amount=50)
session.comments_by_tags(["salento2019", "brina"], amount=50)
session.unfollow_by_tags(["salento2019", "brina"], amount=50)

ufff... excuse me, mastico pyrhon solo da poco...

**Comment by FranklinClinton** [comment]
Hi there! Please try to post in english, because most people out there speak english. Also, please fill out the Headlines from the template. What is the expected behavior, what is the current behavior? How does you script look like? 
The community is very good, but nobody will help you if you do not provide enough information.
I hope you understand
