### ISSUE TITLE
Failed to establish a new connection: [Errno 61]

### ISSUE THREAD

**Issue by rubinho101** [InstaPy/InstaPy#4529]
## Current Behavior
After two days I keep getting the following error for each quickstart.py. I tried the mentioned solutions, but none fixed my issue.

`File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/urllib3/util/retry.py", line 399, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=50174): Max retries exceeded with url: /session/x/execute (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104d255d0>: Failed to establish a new connection: [Errno 61] Connection refused',))`

## InstaPy configuration
MacOS 10.11.6 
Python 2.7
Chromium 2.46

**Comment by filiperivelli** [comment]
Same issue here. I think is something with my firewall. I'm using Lubuntu 18.04 64bits.

`HTTPConnectionPool(host='127.0.0.1', port=38389): Max retries exceeded with url: /session/ab1b7515-9454-41bb-8cec-ba7df6060e4a/execute/sync (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4bd177de20>: Failed to establish a new connection: [Errno 111] Connection refused'))`
