### ISSUE TITLE
downgrade instapy

### ISSUE THREAD

**Issue by theRouter** [InstaPy/InstaPy#4534]
Hi, i have problem with login with proxy after update to 0.5.0
i try many solutions but it didn't worked.
how can solve this problem or downgrade instapy ??
please help me

**Comment by fintzd** [comment]
Hey there! What's the exact issue you are facing? 

Getting blocked could come from many reasons:
- Could be that the bot runs from a different location (e.g.: IP that is far from your usual login location) and that triggers the block
- Could be that you are making too many actions in a day or in an hour
- Could be that you are running the bot from an IP where many accounts are running from
- Could be that you set the bot to run 24/7, which isn't human-like so that triggers red-flags too

I've been running the bot for many weeks and no issues happened with it, I keep the settings low, and the location close to the actual location. I also put sleeping times and limit the amount of hourly actions. 

Be human, be safe, and let me know what the settings are if you want some more information.

**Comment by afoxa** [comment]
> Hey there! What's the exact issue you are facing?
> 
> Getting blocked could come from many reasons:
> 
> * Could be that the bot runs from a different location (e.g.: IP that is far from your usual login location) and that triggers the block
> * Could be that you are making too many actions in a day or in an hour
> * Could be that you are running the bot from an IP where many accounts are running from
> * Could be that you set the bot to run 24/7, which isn't human-like so that triggers red-flags too
> 
> I've been running the bot for many weeks and no issues happened with it, I keep the settings low, and the location close to the actual location. I also put sleeping times and limit the amount of hourly actions.
> 
> Be human, be safe, and let me know what the settings are if you want some more information.

Hi! Just wondering which scripts you use? I had been using it fine for about a month and the past few days instagram has blocked me etc.
