### ISSUE TITLE
Send IOS/Android user agent

### ISSUE THREAD

**Issue by ghost** [InstaPy/InstaPy#4545]
## Expected Behavior
Ability to customize user agent sent with requests

## Current Behavior
Default Chrome on Linux user agent is sent

## Possible Solution (optional)
1) Add additional feature to customize user agent
2) Have pre-selected/approved user agents that make the requests appear to come from a mobile IOS/Android device instead of a Linux workstation

**Comment by Herrox** [comment]
My answer I post seconds ago on the Discord channel:

I guess forging the User Agent is a first step, but I'm sure there is other data pass in the `User-Agent` header, like version of IG app, OS used and many more. This is for example the `User-Agent` FROM Instagram when a user is visiting a website with link in bio `Mozilla/5.0 (iPhone; CPU iPhone OS 12_1_2 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/16C101 
Instagram 79.0.0.18.100 (iPhone10,1; iOS 12_1_2; en_US; en-US; scale=2.34; gamut=wide; 750x1331; 140490268)`. So as you can see it contains : 
* Phone model
* OS version
* IG app version
* Language
* Screen resolution
* And many others

I dont exactly know how the IG app is working, but it looks to be on HTTP so I'm pretty sure the User-Agent header contains a lot of unknown data. And as it should be HTTPS, not sure we could reverse engineer it...
So forging the user agent may be good, but we need to make sure it contains **all the data** as if the user come from the app because otherwise it will still be useless and easily detected. There is also no user using IG from a mobile web browser...
As forging user agent header (same for referer and so on) is a very very common thing and as it can easily forged, this header is not consider relevant anymore by IT pro. And using an incomplete or wrong one could be the same as no one or even worst : today the `user-agent` header may not be the best one (and the "good" one) but at least the data are 100% real and not faked.
IG banning's algorithm is based on thousands of parameters so forging the UA will not prevent to not get banned or detected, especially if we forged a incomplete one that may appears even more fake

**Comment by sionking** [comment]
Even canvas detector can detect a GPU of PC....

**Comment by Herrox** [comment]
@sionking No doubt about that and not sure what you want to mean ...

**Comment by AKwoKWH** [comment]
Hi @sionking 
I was using instabot which they have a pretty good list of devices
Not sure this is useful or not, but the bot do pretend to be a real device when login to instagram
https://github.com/instagrambot/instabot/blob/master/instabot/api/devices.py

One thing to be make sure is that we need a full completed user agents
Using a good user agents can prevent being identified as bot, 
However, a bad user agents with incomplete info will definitely a red flag to instagram and you will be block mush easilier

**Comment by JoeFertig** [comment]
Sorry but that is not true. This won’t save us.

AKwoKWH <notifications@github.com> schrieb am So. 23. Juni 2019 um 19:19:
