### ISSUE TITLE
Need help with XPath error while running Instapy Mobile Emulation - Fighting blocks

### ISSUE THREAD

**Issue by Tachenz** [InstaPy/InstaPy#4667]
It keeps getting buried in the other topic. To try and fight Instapy detection, I am testing mobile emulation mode. The problem is it will of course give an xpath error - and I don’t know how to fix it. Can someone please help?

Added this to broswer.py:
mobile_emulation = { "deviceName": "BlackBerry Z30" }
chrome_options.add_experimental_option("mobileEmulation", mobile_emulation)

Instagram gives a message "Add instagram to your home screen" - so it is promising, they think I am on the mobile! :)

(as @uluQulu suggested once upon a time)
Trying that at very slow speed with @sionking chromedriver75 version

The error while getting user followers:

"C:\Users\inna\AppData\Local\Programs\Python\Python36\Lib\site-packages\i
nstapy\instapy.py", line 2858, in interact_user_followers
self.logfolder)
File "C:\Users\inna\AppData\Local\Programs\Python\Python36\Lib\site-packages\i
nstapy\unfollow_util.py", line 1079, in get_given_user_followers
logger, logfolder)
File "C:\Users\inna\AppData\Local\Programs\Python\Python36\Lib\site-packages\i
nstapy\unfollow_util.py", line 807, in get_users_through_dialog
dialog = browser.find_element_by_xpath(dialog_address)
File "C:\Users\inna\AppData\Local\Programs\Python\Python36\Lib\site-packages\s
elenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
return self.find_element(by=By.XPATH, value=xpath)
File "C:\Users\inna\AppData\Local\Programs\Python\Python36\Lib\site-packages\s
elenium\webdriver\remote\webdriver.py", line 978, in find_element
'value': value})['value']
File "C:\Users\inna\AppData\Local\Programs\Python\Python36\Lib\site-packages\s
elenium\webdriver\remote\webdriver.py", line 321, in execute
self.error_handler.check_response(response)
File "C:\Users\inna\AppData\Local\Programs\Python\Python36\Lib\site-packages\s
elenium\webdriver\remote\errorhandler.py", line 242, in check_response
raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Una
ble to locate element: {"method":"xpath","selector":"//body/div[3]/div/div[2]"}
(Session info: chrome=75.0.3770.100)
(Driver info: chromedriver=2.44.609538 (b655c5a60b0b544917107a59d4153d4bf78e1b
90),platform=Windows NT 6.3.9600 x86_64)"

**Comment by SkylimiTY** [comment]
Hey,

from looking at the code and TRACEBACK it seems that the script fails at the point where it tries to log what it did and tries to search for the logfolder and thus the error in XPATH. I belive the issue here is coming from the path Instapy saves all of its running logs. @uluQulu @timgrossmann 

A possible solution would be to test out how those paths can be modified when using the emulator.

Looking forward to some insights and or ideas.

**Comment by Tachenz** [comment]
Thank you! I wish I knew Python enough to debug this :(

**Comment by uluQulu** [comment]
Hey @SkylimiTY 
Logging is clean - no issues with it; Problem above is with XPath.

@Tachenz, I've read from emails that you're onto mobile emulation last days.
A few words,
I've no idea on how real is your detections and how far can ME save that problem.
ME isn't a native app. It's just a web interface for mobile phones and modern browsers can emulate it.
I mean, IG does not work for mobile version for computers. They just support web interface for mobile phones.

It can have some benefits like the photo upload button.. Etc.
But my naïve thought is running on a computer- desktop version and the mobile (emulated) version of the website has the same level of **detection**. That's why switching to mobile emulation fully is not any effective option [in the long run].

Meanwhile, while trying it, you are going to face tons of XPath conflicts since it is pretty normal cos the page layouts change massively.
Maybe you can find the XPath of certain feature(s) for the mobile version and try testing it in full resolution and in final realize if mobile emulation helps any or not and let us know maybe.


If there is a problem (detections) with web interface (desktop or mobile - doesn't matter in general) and that is gonna be a problem with InstaPy.
What can be done?
- New methods can be worked out to prevent detection. It could help **maybe**.

In worst case: I am not sure how real is the situation you've outlined above, so I'll skip the worst case ideas for now 👇🏼

Have a good time 🙂
---

**Comment by uluQulu** [comment]
BTW @Tachenz 
As you can use InstaPy, your python level is unquestionably better enough 🚀 to debug a source code. 

If you want to learn the way to find the XPath of a web element like a boss, let me know to tutor a few minutes.

The thing is:
- [x] Your _capacity_ must be good enough to at least understand how it works. Does not depend on you.
- [x]  Your _will_ to learn how it works. Depends on you.
- [x] A good _tutor_. Depends on me 😂

Your gain will be at least being able to customize InstaPy (that you use for a long time) as never before.
Also helping others for good, maybe 🍪


No worries ☕
---

**Comment by Tachenz** [comment]
@uluQulu  Thank you! Look, this whole "mobile emulation" thing popped up as I am observing a specific phenomena for the last week or so. Namely:
- When I run instapy on chrome/firefox on my laptop. from under the home Wifi - it gets like banned, even if the speed of liking is 1 like per 20 minutes. (within an hour).
- If I then simultaneously use safari on my iphone to log into the Instagram and like photos (from under the same home Wifi) - i don't have this block. And can like 10-20 photos in a spree. 

So I am just trying to figure out if this might be a solution. Also when I start the mobile emulation on Instapy, - instagram gives a pop up dialogue "Add instagram to your home screen". Another hint that it "thinks" we are on the mobile. Of course it could be all for nothing.

I hear you that Xpath error would be numerous. As for the learning - if there is a tutorial I could read through, or a practical example how to hunt down ONE Xpath error - I am sure I can imitate it in future by finding those Xpath errors myself. I have VERY basic knowledge of the python and will probably just waste your time if you try to teach me, BUT I am good at reverse engineering things :)

**Comment by Tachenz** [comment]
That said - I am up for tutoring for sure :)

**Comment by uluQulu** [comment]
@Tachenz 

Try observing the same quickstart on:
- different account & same IP address (_try using a fresh account that has not exceeded quota recently_)
- same account & different IP address (_can use a clean proxy/VPN or a friend's/neighbour's connection_)
- also, does worth switching between web browsers - Firefox to Chrome or vice verse..
- etc.

And see if it happens.

Also, you should know that IG behaves each device differently, as it can soft block your activity on some device whilst others would work like nothing. It's a bit annoying block policy but is true.

BTW on pop-up dialog.. IG ain't stupid but sometimes they are careless xD
I mean the level of desktop detection is the same with mobile emulation since both runs in the same webdriver and web browser. But in your scenario (if is too real) - it can be possible that desktop is crossed but mobile is yet fine? 😑 Well, rumours rumours ..

BTW that pop-up saying "Add to home screen" also pops up in desktop version but we have previously dealt it. I put a explicit wait that waits until that pop-up dialog to pop up and then close it immidiately. It pops up in less than 3 seconds and closing it is almost invisibly fast. And that only happens while logging in - without a cookie or invalid cookie sessions.
So, it is not something new.

---

About the tutorial, everything is in the web for you to search. But learning it from an experienced person saves you too much time. I have also learnt many neat tips from senior programmers at IRC that you can hardly find by searching on the web 😆

Anyways, it's just finding the XPath of a web element. You're a long-term user of InstaPy, so it'd be worthwhile to help you learn it 😄
When you have time these days, hit me up on email and we could arrange a quick session and practice that little bit.



Have a good time ☕
---

**Comment by Tachenz** [comment]
Deal! Emailed you

**Comment by Tachenz** [comment]
So after a week’s break (7 full days of absolutely no Instapy usage) and at the speed of 1 like per 3 (THREE) hours. Instapy got banned after 12 likes.

As always, I can like as much as I want from my phone browser and app, under the same wifi.
If that is not the red flag, I don’t know what is :)

**Comment by amatadev98** [comment]
> So after a week’s break (7 full days of absolutely no Instapy usage) and at the speed of 1 like per 3 (THREE) hours. Instapy got banned after 12 likes.
> 
> As always, I can like as much as I want from my phone browser and app, under the same wifi.
> If that is not the red flag, I don’t know what is :)

Did you try to login with web browser yourself and test actions manually to see if you get block again?
I think instagram doesn't trust new logins , so whether you use bot or login to browser manually and do actions , you get block again.

**Comment by Tachenz** [comment]
@MHzCode quite on contrary - every time I re-run instapy (deleting cookie) it lets me run for some time (likes and follows).

Are you using Instapy? not blocked? May I ask what settings, what speed, what session duration and how many sessions a day are you using?

**Comment by amatadev98** [comment]
> @MHzCode quite on contrary - every time I re-run instapy (deleting cookie) it lets me run for some time (likes and follows).
> 
> Are you using Instapy? not blocked? May I ask what settings, what speed, what session duration and how many sessions a day are you using?

I'm not using instapy but I'm using web and mobile api (so there is no browser or mobile emulation, just api calls)
We don't know exactly why this problem occurs. It can be one of these, or all of them:
1. Instagram client (browser, mobile) sends information about gestures, actions, mouse movements and... and AI decides to block you or not. (for example logging_client_events api) 
2. Instagram detects action patterns (timeouts between actions)
3. New instagram update is broken. Even users that don't use bots experience action blocks for no reason. 

Im asking people to see if they use browser and do actions (150 follow, 80 like) manually (for more than 3 days) they experience block or no.

I'm experiencing two type of blocks (more of second one) :
1. Action block that blocks action on all sessions, re login doesn't work. 
2. Action block on specific session that will not be lifted even after a week. (like, follow, comment get block on that session but unfollow has no problem) , re login works. 


150 follows, 80 likes per day. Session get blocked after three days (block type 2).

**Comment by Tachenz** [comment]
I see. Yeah, mine is way faster. I get blocked after 9 likes (and I’ve randomised delays to the extreme at this point - e.g. between 1 and 2 hours per like).
Relog helps for another 10 likes.
