### ISSUE TITLE
Chrome support has been removed

### ISSUE THREAD

**Issue by redsector72** [InstaPy/InstaPy#4834]
It seems Chrome support has been removed from Master.

**Comment by Dimon1011** [comment]
Download firefox Instapy 0.6.1 only runs on FF

**Comment by redsector72** [comment]
@timgrossmann @uluQulu 
This is not ok. 
There is no reason for removing Selenium support.

**Comment by Zettt** [comment]
As far as I'm aware, Selenium hasn't been removed. It's just that the main browser has been changed.

**Comment by leo1in88** [comment]
> Download firefox Instapy 0.6.1 only runs on FF

How can i do that? im a newbie here.

**Comment by Zettt** [comment]
You go to the website of Firefox and download it. Don't forget to install.

**Comment by Flaunkerton2395** [comment]
Do we have to do anything else to get Instapy to use Firefox instead?

**Comment by TravisH84** [comment]
Why remove chrome / chromium support?

Many of the embedded devices have issues with firefox, and crashing loops so for some devices it is impossible to use firefox :(. My Raspberry pi is a good example, I had it working well, but the latest updates have stopped it from working, and since Firefox builds crash on rPi3, it seems InstaPy is no longer usable on Raspberry Pi :(.

What was the logic behind removing chrome / chromium support?
Can this be re-considered in future builds as personally i think it was a short sighted move.

**Comment by mwargan** [comment]
I second this, what was the logic to remove Chrome @timgrossmann? My whole model of running this script on Pi's as a service has basically collapsed since the update :P :/.

**Comment by erensunerr** [comment]
I agree with this. @timgrossmann please consider adding chromium support on the future releases. Why did you remove chromium support?
