### ISSUE TITLE
0.6.1 Error, wont start

### ISSUE THREAD

**Issue by bhaldeep** [InstaPy/InstaPy#4835]
## Expected Behavior
Instapy Runs Smoothly
## Current Behavior
 starting instapy with quickstart
================================

 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.
Workspace in use: "C:/Users/....../InstaPy"
Traceback (most recent call last):
  File "../quickstart.py", line 11, in <module>
    multi_logs=True)
  File "C:\Users\......l\AppData\Local\Programs\Python\Python37-32\lib\site
-packages\instapy\instapy.py", line 318, in __init__
    self.logger,
  File "C:\Users\......\AppData\Local\Programs\Python\Python37-32\lib\site
-packages\instapy\browser.py", line 114, in set_selenium_local_session
    options=firefox_options,
  File "C:\Users\......\AppData\Local\Programs\Python\Python37-32\lib\site
-packages\selenium\webdriver\firefox\webdriver.py", line 174, in __init__
    keep_alive=True)
  File "C:\Users\......\AppData\Local\Programs\Python\Python37-32\lib\site
-packages\selenium\webdriver\remote\webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "C:\Users......\AppData\Local\Programs\Python\Python37-32\lib\site
-packages\selenium\webdriver\remote\webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "C:\Users\......\AppData\Local\Programs\Python\Python37-32\lib\site
-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\......\AppData\Local\Programs\Python\Python37-32\lib\site
-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_respons
e
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: Unable to find a
 matching set of capabilities

Press any key to continue . . .
## Possible Solution (optional)

I think there is an issue with the init file thats causing this error

**Comment by Dimon1011** [comment]
Are you running on firefox?

**Comment by acer67** [comment]
im getting this same issue running on chrome

**Comment by Dimon1011** [comment]
Download Firefox amd update inspay to 0.6.1

**Comment by Dimon1011** [comment]
Thats what i did to fix my errors

**Comment by acer67** [comment]
I have downloaded Firefox and updated instapy but the issue still remains. How do you get it to run on firefox instead of on chrome?

**Comment by Dimon1011** [comment]
The new update removes chrome completely I believe. If you had firefox vefore make sure you uodate that what i would do.

**Comment by mdx4rs** [comment]
Firefox is installed, instapy has been updated - error remains.

also did a reinstall of python, firefox and instapy. Using windows10

**Comment by Tachenz** [comment]
Re updated all this morning. Error remains, had the same one trying to run Dev as well

**Comment by dillendillen** [comment]
Have the same problem, InstaPy didn't work than updated it to 0.6.1 with the included update file.
After that it boots up but closes after ::

 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.
Workspace in use: "C:/Users/Administrator/InstaPy"

OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2019-08-13 11:11:35] [dylantemmerman]  Session started!
oooooooooooooooooooooooooooooooooooooooooooooooooooooo
INFO [2019-08-13 11:11:35] [dylantemmerman]  -- Connection Checklist [1/3] (Internet Connection Status)
INFO [2019-08-13 11:11:35] [dylantemmerman]  - Internet Connection Status: ok
INFO [2019-08-13 11:11:35] [dylantemmerman]  - Current IP is "*********************************" and it's from "Belgium/BE"
INFO [2019-08-13 11:11:35] [dylantemmerman]  -- Connection Checklist [2/3] (Instagram Server Status)
INFO [2019-08-13 11:11:39] [dylantemmerman]  - Instagram WebSite Status: Currently Up
INFO [2019-08-13 11:11:39] [dylantemmerman]  - Instagram Response Time: 115.907 ms
INFO [2019-08-13 11:11:40] [dylantemmerman]  - Instagram Reponse Code: 200
INFO [2019-08-13 11:11:40] [dylantemmerman]  - Instagram Server Status: ok
INFO [2019-08-13 11:11:40] [dylantemmerman]  -- Connection Checklist [3/3] (Hide Selenium Extension)
INFO [2019-08-13 11:11:40] [dylantemmerman]  - window.navigator.webdriver response: False
INFO [2019-08-13 11:11:40] [dylantemmerman]  - Hide Selenium Extension: ok

....................................................................
INFO [2019-08-13 11:11:52] [dylantemmerman]  Logged in successfully!
''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
INFO [2019-08-13 11:11:52] [dylantemmerman]  Saving account progress...

Also FireFox Installed.

**Comment by e1x4** [comment]
the same for me, windows 10, instapy 0.6.1 and I have firefox 68 installed.

**Comment by Dimon1011** [comment]
If the script is runinng and then stops it means you have to modify the script check the docs and see what have changed in the new update i had the same issue with the peak argument had to change it and then it worked all fine.

**Comment by acer67** [comment]
FIX that worked for me.

Uninstall chrome and firefox and delete any residual files + empty recycle bin
Uninstall python and delete any residual files + empty recycle bin
Uninstall instapy and delete all instapy files + empty recycle bin

reinstall latest firefox
reinstall python and pip for all users
upgrade pip to latest version
reinstall instapy using: 'pip install --user instapy' in cmd prompt
update instapy

after i did all this everything seemed to finally work

**Comment by dillendillen** [comment]
> 
> 
> If the script is runinng and then stops it means you have to modify the script check the docs and see what have changed in the new update i had the same issue with the peak argument had to change it and then it worked all fine.

How do you know what changed in the new update? I mean its a pretty big script , Can I see a doc somewhere of what changed in update 0.6.1


Also tried to reinstall, upgrade everything but doesn't work.

**Comment by e1x4** [comment]
I tried in another pc, installed python, instapy, and nothing. There was just firefox installed, no chrome.

**Comment by Dimon1011** [comment]
https://github.com/timgrossmann/InstaPy/blob/master/DOCUMENTATION.md

**Comment by dillendillen** [comment]
> 
> 
> https://github.com/timgrossmann/InstaPy/blob/master/DOCUMENTATION.md

Everything seems the same as it is in my script...

**Comment by Dimon1011** [comment]
hey @everyone !

After 230 commits, 39 files changed, 6.593 lines addition, 5.352 lines removed, version `0.6.0` is here 🤘 🤘 🤘

The most important changes are:
* Now we're using Firefox only
* A Firefox Extension was developed to hide automated browser footprints
* We're running in mobile mode, that means that in next releases we will be able to create posts and send direct messages.

We have A LOT of bug fixes, xpath fixes, new implementations, fewer server calls and much more, check our Changelog for more detailed information.

Some feature has its signature updated, here they are:
```
- signature changes:
  - set_action_delays(random_range) -> (random_range_from, random_range_to)
  - set_delemit_liking(max, min) ->(max_likes, min_likes)
  - set_delemit_commenting(max, min) ->(max_comments, min_comments)
  - unfollow_users(customList, instapyfollowed) -> (custom_list_enabled, custom_list, custom_list_param, instapy_followed_enabled, instapy_followed_param)
  - set*quota_supervisor(peak*_) ->(peak\_\_\_hourly, peak_\*\_daily)
```

As always, updating can be done with a simple `pip install instapy -U`

Thank you so much for all the community support! <:InstaPy:548955743253037056> <:InstaPy:548955743253037056> <:InstaPy:548955743253037056>

**Comment by bhaldeep** [comment]
> Are you running on firefox?

downloaded firefox and reinstalled and updated instapy, chrome is still installed on my PC if that matters.

**Comment by mdx4rs** [comment]
I completely removed anything... python / firefox / chrome / any file related to instapy and started from scratch.

python
firefox
script
installed 

![grafik](https://user-images.githubusercontent.com/54057639/62954114-1c3b6a00-bdef-11e9-955f-93cd9234db21.png)

fresh install on a blank system is not working either

**Comment by Tachenz** [comment]
I pretty much killed off everythjng of the system. Clean install Instapy, latest version firefox. Firefox starts and I get the same bloody error:
Webdriverexception Message: newSession 

Maybe old quickstart file needs to be changed now?

**Comment by dillendillen** [comment]
> 
> 
> I pretty much killed off everythjng of the system. Clean install Instapy, latest version firefox. Firefox starts and I get the same bloody error:
> Webdriverexception Message: newSession
> 
> Maybe old quickstart file needs to be changed now?

I even tried making a new quickstart file that only likes pictures of certain hashtags. but the script keep closing after the login. 

Tried this because of @Dimon1011 comment :
 "If the script is runinng and then stops it means you have to modify the script check the docs and see what have changed in the new update i had the same issue with the peak argument had to change it and then it worked all fine."

**Comment by mdx4rs** [comment]
Update: I downloaded geckodriver manually and placed it in python root directory and also in my instapy folder, now it works.

**Comment by mikediachenko** [comment]
Had the same issue, but seems fix it by install FireFox and  geckodriver. Seems InstaPY is running, but after thinking for some time I'm getting `|> No any statistics to show`. Any ideas?

**Comment by bhaldeep** [comment]
> Update: I downloaded geckodriver manually and placed it in python root directory and also in my instapy folder, now it works.

where did you download geckodriver from? and where did you place it? also did you download and place it before you ran the first time?

**Comment by mdx4rs** [comment]
> 
> 
> > Update: I downloaded geckodriver manually and placed it in python root directory and also in my instapy folder, now it works.
> 
> where did you download geckodriver from? and where did you place it? also did you download and place it before you ran the first time?

Download from here

https://github.com/mozilla/geckodriver/releases

I did not place it anywhere after upgrading to 0.6.1 - it never worked even with a fresh install on a new machine. 

I copied it to AppData\Local\Programs\Python\Python37-32 and to my instapy-master folder

**Comment by bhaldeep** [comment]
> > > Update: I downloaded geckodriver manually and placed it in python root directory and also in my instapy folder, now it works.
> > 
> > 
> > where did you download geckodriver from? and where did you place it? also did you download and place it before you ran the first time?
> 
> Download from here
> 
> https://github.com/mozilla/geckodriver/releases
> 
> I did not place it anywhere after upgrading to 0.6.1 - it never worked even with a fresh install on a new machine.
> 
> I copied it to AppData\Local\Programs\Python\Python37-32 and to my instapy-master folder

I just tried what you did and this happpened:

starting instapy with quickstart
================================

 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.
Workspace in use: "C:/Users/......../InstaPy"
Traceback (most recent call last):
  File "../quickstart.py", line 11, in <module>
    multi_logs=False)
  File "C:\Users\........\AppData\Local\Programs\Python\Python37-32\lib\site
-packages\instapy\instapy.py", line 318, in __init__
    self.logger,
  File "C:\Users\........\AppData\Local\Programs\Python\Python37-32\lib\site
-packages\instapy\browser.py", line 114, in set_selenium_local_session
    options=firefox_options,
  File "C:\Users\........\AppData\Local\Programs\Python\Python37-32\lib\site
-packages\selenium\webdriver\firefox\webdriver.py", line 174, in __init__
    keep_alive=True)
  File "C:\Users\........\AppData\Local\Programs\Python\Python37-32\lib\site
-packages\selenium\webdriver\remote\webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "C:\Users\........\AppData\Local\Programs\Python\Python37-32\lib\site
-packages\selenium\webdriver\remote\webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "C:\Users\........\AppData\Local\Programs\Python\Python37-32\lib\site
-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\........\AppData\Local\Programs\Python\Python37-32\lib\site
-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_respons
e
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: Unable to find a
 matching set of capabilities

Press any key to continue . . .

**Comment by Tachenz** [comment]
When I manually place the latest geckodriver into Python and Instapy folders I get this error:

selenium.common.exceptions.SessionNotCreatedException: Message: Unable to find a
matching set of capabilities

**Comment by e1x4** [comment]
try this fix https://github.com/timgrossmann/InstaPy/pull/4856
for me it works, but there is only action blocked

**Comment by ghost** [comment]
I downloaded **geckodriver** manually (from here: https://github.com/mozilla/geckodriver/releases) and placed it to the folder: AppData\Local\Programs\Python\Python37-32 and to my instapy-master folder.
Now it works!
I'm running on Windows 10

**Comment by papillon-unix** [comment]
Can anyone tell me how to install properly geckodriver on raspberry ?

`Message: 'chromedriver' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home`

**Comment by Eduardovalenca** [comment]
Traceback (most recent call last):File "/home/eduardo valencia/.local/lib/python3.8/site-packages/instapy/util.py", line 976, in click_elementelement.click()File "/home/eduardovalenca/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webelement.py", line 80, in clickself._execute(Command.CLICK_ELEMENT)File "/home/eduardovalenca/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webelement.py", line 633, in _executereturn self._parent.execute(command, params)File "/home/eduardovalenca/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in executeself.error_handler.check_response(response)File "/home/eduardovalenca/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_responseraise exception_class(message, screen, stacktrace)selenium.common.exceptions.ElementClickInterceptedException: Message: Element <span class=""> is not clickable at point (28,725) because another element <a class="gKAyB " href="/"> obscures itDuring handling of the above exception, another exception occurred:Traceback (most recent call last):File "/home/eduardovalenca/Downloads/Scripts/plano-basico.py", line 40, in <module>session.like_by_feed(amount=100, randomize=False, unfollow=False, interact=False)File "/home/eduardovalenca/.local/lib/python3.8/site-packages/instapy/instapy.py", line 3835, in like_by_feedfor i in self.like_by_feed_generator(**kwargs):File "/home/eduardovalenca/.local/lib/python3.8/site-packages/instapy/instapy.py", line 3965, in like_by_feed_generatorlike_state, msg = like_image(File "/home/eduardovalenca/.local/lib/python3.8/site-packages/instapy/like_util.py", line 758, in like_imageclick_element(browser, like_elem[0])File "/home/eduardovalenca/.local/lib/python3.8/site-packages/instapy/util.py", line 987, in click_elementbrowser.execute_script(File "/home/eduardovalenca/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 634, in execute_scriptreturn self.execute(command, {File "/home/eduardovalenca/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in executeself.error_handler.check_response(response)File "/home/eduardovalenca/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_responseraise exception_class(message, screen, stacktrace)selenium.common.exceptions.JavascriptException: Message: TypeError: document.getElementsByClassName(...)[0] is undefined

Mine keeps giving this problem, it runs wheel runs and then stops suddenly, has anyone been there?

**Comment by Eduardovalenca** [comment]
`Traceback (most recent call last):File "/home/eduardo valencia/.local/lib/python3.8/site-packages/instapy/util.py", line 976, in click_elementelement.click()File "/home/eduardovalenca/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webelement.py", line 80, in clickself._execute(Command.CLICK_ELEMENT)File "/home/eduardovalenca/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webelement.py", line 633, in _executereturn self._parent.execute(command, params)File "/home/eduardovalenca/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in executeself.error_handler.check_response(response)File "/home/eduardovalenca/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_responseraise exception_class(message, screen, stacktrace)selenium.common.exceptions.ElementClickInterceptedException: Message: Element <span class=""> is not clickable at point (28,725) because another element <a class="gKAyB " href="/"> obscures itDuring handling of the above exception, another exception occurred:Traceback (most recent call last):File "/home/eduardovalenca/Downloads/Scripts/plano-basico.py", line 40, in <module>session.like_by_feed(amount=100, randomize=False, unfollow=False, interact=False)File "/home/eduardovalenca/.local/lib/python3.8/site-packages/instapy/instapy.py", line 3835, in like_by_feedfor i in self.like_by_feed_generator(**kwargs):File "/home/eduardovalenca/.local/lib/python3.8/site-packages/instapy/instapy.py", line 3965, in like_by_feed_generatorlike_state, msg = like_image(File "/home/eduardovalenca/.local/lib/python3.8/site-packages/instapy/like_util.py", line 758, in like_imageclick_element(browser, like_elem[0])File "/home/eduardovalenca/.local/lib/python3.8/site-packages/instapy/util.py", line 987, in click_elementbrowser.execute_script(File "/home/eduardovalenca/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 634, in execute_scriptreturn self.execute(command, {File "/home/eduardovalenca/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in executeself.error_handler.check_response(response)File "/home/eduardovalenca/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_responseraise exception_class(message, screen, stacktrace)selenium.common.exceptions.JavascriptException: Message: TypeError: document.getElementsByClassName(...)[0] is undefined`

Mine keeps giving this problem, it runs wheel runs and then stops suddenly, has anyone been there?
