### ISSUE TITLE
Some news ?

### ISSUE THREAD

**Issue by koni06** [InstaPy/InstaPy#4930]
## Expected Behavior
Instapy working
## Current Behavior
Don't know was sleeping for one month
## Possible Solution (optional)
New version ? 
## InstaPy configuration
Hi everyone, 
One month i haven't open instapy, and i would like to know if now some of you could run your script correctly ? Thx

**Comment by Tachenz** [comment]
Nah, gets banned after few follows, almost immediately :(

**Comment by yfedorovsky** [comment]
Currently nothing works, even Jarvee gets banned intermittently. Instagram improved their bot detection logic over the past few weeks.

**Comment by riccardovalente** [comment]
Well so you're saying, but it's still works for me. I had a brief block (after 3 months) about 2 weeks ago, but I've been running ok otherwise.

**Comment by marcoantonio123456** [comment]
I was using captivate by Novasoft and they have shut down too. Do you guys have suggestions to run multiple accounts under different VPNs?

**Comment by GreatMalboro** [comment]
Im waiting for an update, I have confidence in the creators. Ive been down for I think 2 weeks. I think the most important part coming up is "Not acting like a bot" when using it but thats easier said than done.

**Comment by jm-willy** [comment]
@yfedorovsky Yes, probably at Instagram they have downloaded InstaPy to train their AI: https://github.com/timgrossmann/InstaPy/issues/4891. Unless InstaPy is improved will become obsolete in less than a few months

**Comment by koni06** [comment]
@jm-willy ye thats why im afraid..

**Comment by dsmh** [comment]
Can bet Instagram is reading all the issues of this repository. +1 if you think the same

**Comment by GreatMalboro** [comment]
Well I dont think its that deep. Its open source yea. Is Instapy currently down? yea. But im under the impression that any thing can be exploited one way or another. Even if all bots are mimced lets say, I think someone will come up with a way to out smart their systems. To be honest, python isnt a very powerful language so that may also play a part. Whose to say those who are asking for money with their use of automation are NOT using more powerful languages or systems in order to remain undetected? Or maybe thats why they keep theirs more private than others. You could still be right no matter what about someone reading the repository.

**Comment by mikediachenko** [comment]
Unfollow works like a charm :)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by vladdd2703** [comment]
> Unfollow works like a charm :)
> 
> Sent with [GitHawk](http://githawk.com)

can you please post your script as mine do not want to start now after all the updates?

thanks
