### ISSUE TITLE
Is the bot still working for someone ?

### ISSUE THREAD

**Issue by Edhim** [InstaPy/InstaPy#4945]
I am getting blocked at the first like / comment 

wondering if it still working for someone.
Thanks

**Comment by xuhig** [comment]
blocked too....

**Comment by Flaunkerton2395** [comment]
I'm getting blocked too unless I run headless_browser = False and opening up random tabs in the session.

**Comment by GreatMalboro** [comment]
Can you explain what you mean opening up random tabs? Like go into a bit of detail?

**Comment by Flaunkerton2395** [comment]
add 'headless_browser=false' to your parameters in your script and then when it opens, just open another tab and go to random websites.

**Comment by vx8** [comment]
I'm not banned but I'm using a 2months old instapy version, not sure if it's random or not.. tho.

**Comment by alexsmedile** [comment]
> I'm not banned but I'm using a 2months old instapy version, not sure if it's random or not.. tho.

Can you please specify what version you're using? Because I had no problem till I updated it.

**Comment by vx8** [comment]
> > I'm not banned but I'm using a 2months old instapy version, not sure if it's random or not.. tho.
> 
> Can you please specify what version you're using? Because I had no problem till I updated it.

I reverted using this command and the bot is working for me

git checkout git rev-list -n 1 --first-parent --before="2019-06-27 00:00" master

**Comment by posittron** [comment]
> I'm not banned but I'm using a 2months old instapy version, not sure if it's random or not.. tho.
> 
> Can you please specify what version you're using? Because I had no problem till I updated it.
> 
> I reverted using this command and the bot is working for me
> git checkout git rev-list -n 1 --first-parent --before="2019-06-27 00:00" master`

You've got me excited about this but can you double check that command cause when I enter it nothing happens It just moves to next line and a arrow shows

**Comment by vx8** [comment]
There is an extra ‘ at the end of the command I pasted. It’s fixed now. I forgot to mention I’m on macOS

**Comment by posittron** [comment]
What would it be if it was on windows?

**Comment by vx8** [comment]
No idea sorry 😞

**Comment by posittron** [comment]
damn shit. okay

**Comment by mikediachenko** [comment]
For me bot is working fine now. Using on macOS and Linux. But currently I’m using it only for unfollowing and photo liking.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by kevXZY** [comment]
bot is working for me but i've got a notification from instagram to change my password and that the next time they're not going to let me like and follow again...

**Comment by jonap339** [comment]
I received the same notification 3 times and all my clients too. Instagram blocked 3 accounts of the 8 I'm handling

**Comment by kevXZY** [comment]
> I received the same notification 3 times and all my clients too. Instagram blocked 3 accounts of the 8 I'm handling

Is the block temporary ? how much does it last ?

**Comment by jonap339** [comment]
I hope it's temporary

**Comment by ejscheepers** [comment]
Has there been any progress on this issue? I just started using InstaPy and now this happens.

**Comment by NooriP** [comment]
Same

**Comment by lezlea** [comment]
Yes a few days ago all my accounts received temp blocks on very low settings on likes/follows/unfollows, then I read this issue and decided to pause for a few days.  I was using the latest version, mobile proxies etc.  I did notice a few days ago problems with cookies saving. I will try reverting back to the previous version :)

**Comment by GreatMalboro** [comment]
So none of you are running windows but you have the the code running correctly? Can you tell me what you did?  Besides whas mentioned above?

**Comment by hijak** [comment]
set action delay to 20 sec i am having more luck with this

the bots are too rapid on there desktop site and hit rate limiting.

**Comment by lezlea** [comment]
I think it's different for everyone and every account... 
- I've tried action delays at 30 seconds, 45, 60, 90, 120 etc. etc. all being the minimum.
- I've tried random action delays between 96 - 210%, or action delays with less of a difference
- I've tried doing 5 actions an hour, every hour for 8 hours. I've tried doing 20 actions an hour for 2 hours (more in bulk actions).  
- I've tried mixing follows with likes and liking comments (on low numbers). I've tried just focusing on follows.
- I've tried running overnight (when the mobile app def isn't open at the same time), I've tried running when it's the 'normal' waking hours
- I've tried keeping the same session for 4 hours, and I've tried doing quick short sessions every hour.

On my accounts that are having issues with temp block none of the above seems to make a difference - even on a well warmed up account, mobile proxy, generally I can do the first 5 actions then hit a temp action block.  Sometimes it will run ok for a day then BAM, another temp block.  Can't seem to get around it!

On my accounts that are running well - changing the above doesn't make a difference, they still run well!  On the accounts running well they were running at 45-70 sec action delay, up to 22 follows an hour (randomised) and max 120 follows a day over 8 hours (with some unfollows too).  But I saw an issue on Sunday last week and have been paused since so I can't say that's the same for this week.... since it keeps changing!

**Comment by e1x4** [comment]
I have action blocked, about following, just in instapy, in my ig app it's all ok.

**Comment by mpaolor** [comment]
> I have action blocked, about following, just in instapy, in my ig app it's all ok.

same here but also liking is blocked. it gets blocked after the first like!

**Comment by Edhim** [comment]
@mikediachenko  can you share with us your version please ?

**Comment by Edhim** [comment]
@mikediachenko @vx8 can you share with us your version please ?
