### ISSUE TITLE
Not logged in >Unable to login to Instagram!   You will find more information in the logs above.

### ISSUE THREAD

**Issue by dedeehzinhuuh** [InstaPy/InstaPy#4958]
## Expected Behavior

Ele vai até a pagina de Login, a partir dali não faz as ações, a pagina fecha e da essa mensagem de log

## Current Behavior

INFO [2019-08-27   15:32:14] [user]  Session ended!
--
INFO [2019-08-27 23:29:17] [user]  Session started!
INFO [2019-08-27 23:29:17] [user]  -- Connection Checklist [1/3] (Internet   Connection Status)
INFO [2019-08-27 23:29:17] [user]  - Internet Connection Status: ok
INFO [2019-08-27 23:29:17] [user]  - Current IP is "MyIP"   and it's from "Brazil/BR"
INFO [2019-08-27 23:29:17] [user]  -- Connection Checklist [2/3] (Instagram   Server Status)
INFO [2019-08-27 23:29:24] [user]  - Instagram WebSite Status: Currently   Up
INFO [2019-08-27 23:29:24] [user]  - Instagram Response Time: 40.874 ms
INFO [2019-08-27 23:29:24] [user]  - Instagram Reponse Code: 200
INFO [2019-08-27 23:29:24] [user]  - Instagram Server Status: ok
INFO [2019-08-27 23:29:24] [user]  -- Connection Checklist [3/3] (Hide   Selenium Extension)
INFO [2019-08-27 23:29:24] [user]  - window.navigator.webdriver response:   False
INFO [2019-08-27 23:29:24] [user]  - Hide Selenium Extension: ok
CRITICAL [2019-08-27 23:29:40]   [user]  Unable to login to Instagram!   You will find more information in the logs above.
INFO [2019-08-27 23:29:44] [user]  Sessional Live Report:
 
 
 
[Session lasted 39.91 seconds]
INFO [2019-08-27 23:29:44] [user]  Session ended!

## Possible Solution (optional)
* I deleted instapy folder
* I deleted and installed Python again
* I Deleted and installed instapy
* Update instapy

## InstaPy configuration

I don't know programming language, I have little knowledge.

**Comment by DenisKot** [comment]
Same for me :(

**Comment by NooriP** [comment]
Same here!

**Comment by krenar-hoxha** [comment]
Same problem

**Comment by bvanhou** [comment]
Its most likely due to a validation/verification issue when logging in, I have found a workaround for this and it works really well. Granted I added cloud operations to it, in order for it to work. I am going to post the workaround in the near future, however since it requires cloud knowledge and a messaging service I might offer it people for a few bucks (like 5) a month, so I can cover the costs.

Summation of the Solution:
  - Basically the solutions for verification that I am using so I don't have to watch the service like a hawk and let it run automatically on a cron job. Is for the verification code you get via text. 
          1. You obtain the verification code from Instagram 
          2. Copy the message (aka the verification code).
          3. Text that to a number I have connected to the cloud and boom the Instapy has it to reference when logging into your account. (with some code modifications)

Let me know if you would be interested in using this. It would take less than a few minutes to connect everything to my cloud.

hit me up on here

**Comment by dedeehzinhuuh** [comment]
alguma solução?

**Comment by dedeehzinhuuh** [comment]
> O mesmo aqui!

resolveu ai?

**Comment by mpaolor** [comment]
same here

**Comment by Jostino** [comment]
same here

**Comment by Jostino** [comment]
I suggest to look here:
https://github.com/timgrossmann/InstaPy/issues/5035#issuecomment-529238015
