### ISSUE TITLE
Best settings

### ISSUE THREAD

**Issue by roncam82** [InstaPy/InstaPy#5008]
By now can you suggest the best settings to use to not getting banned ?

Thanks

**Comment by kaleidoskopio** [comment]
By now, the fact is that for every case is different : )
Depending on the followers you have, the number of posts, your usual interaction, etc. 
I'd recommend you start low and then increase the numbers. 
(If banned, it won't be for ever, so you'd know the limmit for your own case).

**Comment by tjuzen** [comment]
Hi! 
My account is 1K followers. Im botting since few months with these settings and never had issue.
I would love to hear from others users their limits, to know how far we can bot! :) 

session.set_quota_supervisor(enabled=True, sleep_after=["likes_h", "follows_h", "unfollows_h", "server_calls_h"], sleepyhead=True, stochastic_flow=True, notify_me=True,
                              peak_likes=(49, 585),
                                peak_follows=(39, None),
                                 peak_unfollows=(32, 505),
                                  peak_server_calls=(random.randint(475, 525), None))
