### ISSUE TITLE
Can I Pyinstall the last version of Instapy ?

### ISSUE THREAD

**Issue by lopjf** [InstaPy/InstaPy#5245]
Hello everyone,

I used to convert .py to .exe of Instapy 0.5.8 with Pyinstaller.

But, since yesterday, I got a serious issue using 0.5.8. So I need to upgrade to a more modern version of Instapy. 
It works like charm in .py but I do need to make a standalone executable from it. And unfortunately, for some mysterious reasons. I just can't make it run in .exe with pyinstaller. 
The soft open, it opens firefox, and then, nothing more, it stays stuck in the firefox browser page.

Does anyone know how to make a .exe from it please ?

Thank you,
Lo

**Comment by hamitaksln** [comment]
The problem occures because of pyinstaller. When you build the script, in "browser.py" 
```python
ext_path = os.path.abspath(os.path.dirname(__file__) + sep + "firefox_extension")
```
we have ext_path like that. It works when you run it as a .py but when you build it, I think it runs in Temp folder and try to find it in that folder. So when it doesn't find, an error raise. I've solve with changing "browser.py" like that:
```python
def create_firefox_extension():
    ext_path = os.path.abspath(os.path.dirname(__file__) + sep + "firefox_extension")
    # safe into assets folder
    zip_file = use_assets() + sep + "extension.xpi"
    files = ["manifest.json", "content.js", "arrive.js"]
    with zipfile.ZipFile(zip_file, "w", zipfile.ZIP_DEFLATED, False) as zipf:
        for file in files:
            try:
                zipf.write(ext_path + sep + file, file)
            except :
                new_ext_path = os.getcwd()+sep+"firefox_extension"
                zipf.write(new_ext_path + sep + file, file)

    return zip_file
```
[firefox_extension][1]
After making these changes, I've coppied the firefox_extension to .exe folder and it runs without any problem. 


  [1]: https://i.stack.imgur.com/i6cuy.png
