### ISSUE TITLE
[Feature request] Bypass soft ban

### ISSUE THREAD

**Issue by Jorman** [InstaPy/InstaPy#5311]
As you already know, I don't know how IG can understand that is a bot, maybe because the device is different from the one that we use by default and so on, so the known problem is:

![IG-ERROR](https://user-images.githubusercontent.com/5203988/73501699-02a2d480-43c7-11ea-9c74-256080ed86c1.PNG)

This "soft ban" produce a specific error on InstaPy and I think/hope that this error produce also a specific html text, so the idea is to have one option like `detect_soft_ban=True` so when InstaPy see this, enter a paused mode, in order to wait some time, because if a real human read 'wait some minutes ...' wait some minutes .... so why don't try to wait some random time?

Make sense to you?

J

**Comment by Cordycodes** [comment]
I think this is related to an error that says "Hide Selenium Extension: Error".
Can you check your logs and see if this happened to you?
I think Instagram AI is detecting Selenium and that's why the soft bans are happening and the profile is not accessible for a while in the desktop browser. I'm having the same issue.

**Comment by Jorman** [comment]
Yes, I'm under Windows 10 and I've this error about selenium

Do you know some more about this error?

**Comment by Cordycodes** [comment]
No I just suspect this is what is causing the soft ban.. I'm not sure how to fix it.
I just reckon that this is how Instagram is detecting the use of a bot.
