### ISSUE TITLE
Action immediately gets blocked

### ISSUE THREAD

**Issue by G00dieB0y** [InstaPy/InstaPy#5338]
## Expected Behavior 
Normally the bot should follow some unsers.

## Current Behavior
Already at the first user it follows the message "Action Blocked" pops up.  I am already doing randomisation but it doesn't work. any solution for this behav?

(even if i use the quickstart-templates)

**Comment by dchoruzy** [comment]
I'm having the same problem

**Comment by ghost** [comment]
mee too

**Comment by azmankristjan** [comment]
Same problem here

**Comment by dchoruzy** [comment]
is this going to be fixed?

**Comment by Julianxo** [comment]
I guess your ip is blocked because you did to much requests in a short time.
Try to delete cache and cookies like mentioned here. https://github.com/timgrossmann/InstaPy/issues/4676

And don't forget to reduce your api calls once it starts working again. 
Limit your api calls with the Quota Supervisor which is documented here.
https://github.com/timgrossmann/InstaPy/blob/master/DOCUMENTATION.md#quota-supervisor

The most important should be this line which you have to add to your "quickstart.py":
`session.set_quota_supervisor(enabled=True, peak_server_calls_daily=490, sleep_after=["server_calls_h"], sleepyhead=True)`
Set peak_server_calls_daily to a value and try if you get blocked again. I cannot recommend a value yet but my bot works fine with a value of 1810.

Hope I could help.

**Comment by azmankristjan** [comment]
@Julianxo  Does Follow/ Unfollow work for you without getting action blocked?? I get 200k impressions per week but I get Action blocked immediately when I try to follow new people with Instapy
