### ISSUE TITLE
python: can't open file 'quickstart.py': [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by bhzdios** [InstaPy/InstaPy#5515]

**Comment by jennettageorge** [comment]
please insure that you have cd'd into the directory containing your `quickstart.py` file?

**Comment by coryrobbins** [comment]
Receiving the same issue with quickstart.py in the directory.

**Comment by DanC6312** [comment]
Same issue, any update on this?

**Comment by Dnied18** [comment]
Same issue

**Comment by AbdelazizGuendez** [comment]
Hello,
I got the same issue and I finally solved it.

I was on Windows 10 and the main issue is :
1-You need to download geckodriver.exe for Firefox
2-You need to open quickstart.py and modify the path for geckodriver.exe 

Be careful to write the path correctly, I struggled because I put only one \ to separate files and it only worked once I used \\
For example:
WRONG: C:\folder1\folder2\folder3\geckodriver.exe
RIGHT: C:\\folder1\\folder2\\folder3\\geckodriver.exe
