### ISSUE TITLE
Run Instapy on https://www.pythonanywhere.com

### ISSUE THREAD

**Issue by pikki1** [InstaPy/InstaPy#5564]
Hi!
I´m trying to run instapay on https://www.pythonanywhere.com but I always have the same error:  invalid syntax

Could you tell me how to fix it?
It could be due to the fact that my Python version which is installed on my pc is 3.8.3 and the max version on python anywhere is 3.7?

Thanks a lot in advanced!

**Comment by stelmakhdigital** [comment]
Put the error logs here.
According to the idea, he will not work there, since there are dependencies (for example, a geckodriver. www.pythonanywhere.com/batteries_included - it is not here.)
In addition, for 5 $/month, you can rent a normal server on Digital Ocean (here is my $ 100 promotional code for 3 months - https://m.do.co/c/9b21226ae42d).

**Comment by pikki1** [comment]
Hi.
Thanks a lot for your help!!
Here you can check them:

https://i.postimg.cc/50VT26JV/2.png

https://i.postimg.cc/wvQPygxs/3.png

https://i.postimg.cc/J07FjvtY/Error.png

Thanks a lot again!!

**Comment by pikki1** [comment]
> Put the error logs here.
> According to the idea, he will not work there, since there are dependencies (for example, a geckodriver. [www.pythonanywhere.com/batteries_included](http://www.pythonanywhere.com/batteries_included) - it is not here.)
> In addition, for 5 $/month, you can rent a normal server on Digital Ocean (here is my $ 100 promotional code for 3 months - https://m.do.co/c/9b21226ae42d).

Hi.
Thanks a lot for your help!!
Here you can check them:

https://i.postimg.cc/50VT26JV/2.png

https://i.postimg.cc/wvQPygxs/3.png

https://i.postimg.cc/J07FjvtY/Error.png

Thanks a lot again!!
