### ISSUE TITLE
How to get the list of already followed users from docker

### ISSUE THREAD

**Issue by svensonx** [InstaPy/InstaPy#577]
Hi,

I'm not very experienced with docker, but it seemed to me, that it was a quick way to test InstaPy.
Now I wanna switch to my Raspberry, but i'm not sure, how i can transfer the users i already followed with instapy. Can anybody give me a little hint please.

Thanks in advance!

**Comment by tobyf93** [comment]
Assuming you are currently using `docker-compose up -d --build` to run your docker containers, you will find that the log files don't persist.  This is because every docker container has a writable layer that only lives as long as the container does.  Everything is lost if you decide to rebuild your containers.

This is solved by using volumes within your containers and i've mentioned this in issue #686.  Waiting to get the go ahead to put the fix in place :)

**Comment by timgrossmann** [comment]
#686
