### ISSUE TITLE
Unable to find a matching set  of capabilities

### ISSUE THREAD

**Issue by erfanasbari** [InstaPy/InstaPy#5776]
Hello. When I use quick Start Script I run into a problem.
I get an error that says: 
```
selenium.common.exceptions.SessionNotCreatedException: Message: Unable to find a matching set 
of capabilities
```
and the script stops.
i am using the last version of selenium And last version of InstaPy

**Comment by sskender** [comment]
This is a problem with Selenium. Installing gecko driver manually worked for me.
https://github.com/mozilla/geckodriver

**Comment by roberterzen** [comment]
Hi,
@InterSstellar Have you solved this? I have the same. My script runs fine on my Windows 10 installation but not when run on CentOS 7. In both cases I use Python 3.7.
The link provided by @sskender was of no big help. So I reinstalled Selenium as proposed on [this link](https://www.usessionbuddy.com/post/How-To-Install-Selenium-FireFox-On-Centos/) but the problem is still there.
Thanks.

**Comment by roberterzen** [comment]
Check this out - I found a solution for my context.
https://github.com/timgrossmann/InstaPy/issues/5779#issuecomment-702411953
