### ISSUE TITLE
TypeError: document.getElementsByClassName(...)[0] is undefined

### ISSUE THREAD

**Issue by blackchayenne** [InstaPy/InstaPy#5797]
Hello everyone,

I have a problem started today, yesterday i was using instapy with no mistake and today when i started instapy after some likings it gives me following message "TypeError: document.getElementsByClassName(...)[0] is undefined" what should i do? please i am waiting for your support.

**Comment by Lxand3r** [comment]
@timgrossmann hi I'm having the same issue I've included the full log of the it only happens when im running interact with comment as true. 

I found this article that talk but I can't seem to understand what todo with this...
https://bugzilla.mozilla.org/show_bug.cgi?id=1453779

I also read this but there was no solution on there 
[](https://github.com/mozilla/geckodriver/issues/1269) 

pi@raspberrypi:~/instapy $ python3 H.py
InstaPy Version: 0.6.8
 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.
Workspace in use: "/home/pi/InstaPy"
OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2020-09-29 19:05:10] [hotbutnotdogs]  Session started!
oooooooooooooooooooooooooooooooooooooooooooooooooooooo
INFO [2020-09-29 19:05:10] [hotbutnotdogs]  -- Connection Checklist [2/3] (Instagram Server Status)
INFO [2020-09-29 19:05:26] [hotbutnotdogs]  - Instagram WebSite Status: Currently Up
INFO [2020-09-29 19:05:27] [hotbutnotdogs]  - Instagram Response Time: 117.985 ms
INFO [2020-09-29 19:05:28] [hotbutnotdogs]  - Instagram Reponse Code: 200
INFO [2020-09-29 19:05:28] [hotbutnotdogs]  - Instagram Server Status: ok
INFO [2020-09-29 19:05:28] [hotbutnotdogs]  -- Connection Checklist [3/3] (Hide Selenium Extension)
INFO [2020-09-29 19:05:28] [hotbutnotdogs]  - window.navigator.webdriver response: False
INFO [2020-09-29 19:05:28] [hotbutnotdogs]  - Hide Selenium Extension: ok
Issue with cookie for user hotbutnotdogs. Creating new cookie...
INFO [2020-09-29 19:06:16] [hotbutnotdogs]  Timed out with failure while explicitly waiting until title contains 'Login' $

...................................................................
INFO [2020-09-29 19:06:46] [hotbutnotdogs]  Logged in successfully!
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
INFO [2020-09-29 19:06:46] [hotbutnotdogs]  Saving account progress...
INFO [2020-09-29 19:07:09] [hotbutnotdogs]  User 'yalennyalfaro' [1/3]
['stubborn19x', 'ponchito_s_way', 'mr.king____kaay', 'a_jakeyy', 'scarf_icee', 'el_doul01', 'el.plomo_00', 'janeyymayy__'$


INFO [2020-09-29 19:07:26] [hotbutnotdogs]  User 'stubborn19x' [1/23]
INFO [2020-09-29 19:07:58] [hotbutnotdogs]  Skipping user 'stubborn19x' due to the interaction percentage of 78
INFO [2020-09-29 19:07:58] [hotbutnotdogs]  User 'ponchito_s_way' [2/23]
INFO [2020-09-29 19:08:04] [hotbutnotdogs]  ponchito_s_way is private account, by default skip

INFO [2020-09-29 19:08:04] [hotbutnotdogs]  User 'mr.king____kaay' [3/23]
INFO [2020-09-29 19:08:36] [hotbutnotdogs]  Interaction [1/23]  |  Total Interaction: 1
___________________________________________________________________________
INFO [2020-09-29 19:08:36] [hotbutnotdogs]  Starting to interact by users..
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
INFO [2020-09-29 19:08:36] [hotbutnotdogs]  Username [1/1]
INFO [2020-09-29 19:08:36] [hotbutnotdogs]  --> b'mr.king____kaay'
INFO [2020-09-29 19:08:36] [hotbutnotdogs]  username actions: following=True commenting=True liking=True story=False
INFO [2020-09-29 19:08:36] [hotbutnotdogs]  Getting mr.king____kaay image list...
ERROR [2020-09-29 19:08:40] [hotbutnotdogs]  link_elems error local variable 'post_href' referenced before assignment
INFO [2020-09-29 19:08:45] [hotbutnotdogs]  Post [1/5]
INFO [2020-09-29 19:08:45] [hotbutnotdogs]  https://www.instagram.com/p/BjnkT9Xh9vl/
INFO [2020-09-29 19:08:53] [hotbutnotdogs]  Image from: b'mr.king____kaay'
INFO [2020-09-29 19:08:53] [hotbutnotdogs]  Link: b'https://www.instagram.com/p/BjnkT9Xh9vl/'
INFO [2020-09-29 19:08:53] [hotbutnotdogs]  Description: b'the goal has not changed. Only God can protect me'
INFO [2020-09-29 19:08:53] [hotbutnotdogs]  Location: b'New Brunswick'

INFO [2020-09-29 19:09:00] [hotbutnotdogs]  Sessional Live Report:
        |> No any statistics to show

On session start was FOLLOWING 107 users & had 370 FOLLOWERS
[Session lasted 4.16 minutes]
OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2020-09-29 19:09:00] [hotbutnotdogs]  Session ended!
oooooooooooooooooooooooooooooooooooooooooooooooooooooooooo



Traceback (most recent call last):
  File "/home/pi/instapy/instapy/util.py", line 946, in click_element
    element.click()
  File "/home/pi/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "/home/pi/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "/home/pi/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/pi/.local/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_respon$
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementClickInterceptedException: Message: Element <span class=""> is not clickable at point ($


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "H.py", line 34, in <module>
    session.interact_user_followers(['yalennyalfaro','rachellruaro','25.6.97'], amount=23, randomize=True)
  File "/home/pi/instapy/instapy/instapy.py", line 3202, in interact_user_followers
    self.user_interact_media,
  File "/home/pi/instapy/instapy/instapy.py", line 2557, in interact_by_users
    total_liked_img,
  File "/home/pi/instapy/instapy/like_util.py", line 757, in like_image
    click_element(browser, like_elem[0])
  File "/home/pi/instapy/instapy/util.py", line 960, in click_element
    + "')[0].scrollIntoView({ inline: 'center' });"
  File "/home/pi/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 636, in execute_script
    'args': converted_args})['value']
  File "/home/pi/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/pi/.local/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_respon$
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.JavascriptException: Message: TypeError: document.getElementsByClassName(...)[0] is undefined

**Comment by melnikovic** [comment]
This is still an issue.
