### ISSUE TITLE
Issue when using pyinstaller to turn into .exe file - FileNotFoundError: [WinError 3]

### ISSUE THREAD

**Issue by z-senjin** [InstaPy/InstaPy#5814]
When I use pyinstaller to turn my bot into an .exe file i get this error when I run it... any ideas?

FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\Users\\xxx\\AppData\\Local\\Temp\\xxx\\instapy\\firefox_extension\\manifest.json'
[6092] Failed to execute script bot

Let me know what additional information you need! Stuck on this one. It runs just fine from my IDE but when I change it into an .exe file it fails.

**Comment by hamitaksln** [comment]
The problem occures because of pyinstaller. When you build the script, in "browser.py" 
```python
ext_path = os.path.abspath(os.path.dirname(__file__) + sep + "firefox_extension")
```
we have ext_path like that. It works when you run it as a .py but when you build it, I think it runs in Temp folder and try to find it in that folder. So when it doesn't find, an error raise. I've solve with changing "browser.py" like that:
```python
def create_firefox_extension():
    ext_path = os.path.abspath(os.path.dirname(__file__) + sep + "firefox_extension")
    # safe into assets folder
    zip_file = use_assets() + sep + "extension.xpi"
    files = ["manifest.json", "content.js", "arrive.js"]
    with zipfile.ZipFile(zip_file, "w", zipfile.ZIP_DEFLATED, False) as zipf:
        for file in files:
            try:
                zipf.write(ext_path + sep + file, file)
            except :
                new_ext_path = os.getcwd()+sep+"firefox_extension"
                zipf.write(new_ext_path + sep + file, file)

    return zip_file
```
[firefox_extension][1]
After making these changes, I've coppied the firefox_extension to .exe folder and it runs without any problem. 


  [1]: https://i.stack.imgur.com/i6cuy.png
