### ISSUE TITLE
Can't follow likers

### ISSUE THREAD

**Issue by tyeeeeeep** [InstaPy/InstaPy#5924]
Within session.follow_likers(), the link to the correct photo is returned but the liked counter button cannot be found.

I thought this meant my xpath was incorrect so I changed it to "liked_counter_button": "//a[contains(@href,'liked_by/')]", but I'm still getting the same error.

My version of instapy is up-to-date. Is there something I'm missing? Is my xpath incorrect? Thanks for the help

**Comment by elulcao** [comment]
Same issue mentioned in #5858

**Comment by elulcao** [comment]
Regarding this xpath,
there is another issue for videos, at the moment the number of views in a video
does not behave like the number of likes in a photo. Clicking on the number of 
views only shows the same number in a floating window.
In logs we should see something like `Couldn't find liked counter button. May be a video.`
this is normal and nothing to be fixed by now.

I will push some changes here, to inform the changes.
