### ISSUE TITLE
Error while running "Follow the likers of photos of users"

### ISSUE THREAD

**Issue by virtualKhubaib** [InstaPy/InstaPy#5964]
## Expected Behavior
it should follow the Amount of of likers of a post specified.
## Current Behavior
it says, "Liked button now found, might be a video" and skips the picture
## InstaPy configuration
  session.follow_likers(['alkaramstudio' , 'khaadi'], photos_grab_amount = 2, follow_likers_per_photo = 15, randomize=True, sleep_delay=10, interact=False)

**Comment by elulcao** [comment]
This is not an error, this is working as expected. The bot will skip some post that are not photos, maybe a video or a post with videos and photos.
Actually you will se that some times the bot skip some other post intentionally to behave like a human, 
in real life you are not liking all the photos displayed in the feed in a row, some must be ignored or skipped
because you don't like them.

On the other hand, if a video is found the bot will try to click the total of viewers in order to extract the users and the interact with the. However, the button for viewers/likers in a video behave different than the button in a photo. In a video the button just display a float windows with the same number of viewers, but no the list of followers and that's why the post is skipped; the bot cannot extract info from that floating window. 

It could be another way to check if the bot can extract the info for the users to be interacted if a post that is not a photo has been found. New flags, and configurations for specific media will be created and verified to see if interactions goes well.

**Comment by elulcao** [comment]
I will try to handle that message, flooding the log seems to be confuse under some circumstances.
