### ISSUE TITLE
Cookie file for user Loaded ....  Issue with cookie for user - IT IS FALSE: COOKIE IS GOOD

### ISSUE THREAD

**Issue by Tolmino** [InstaPy/InstaPy#5993]
## Expected Behavior

use same cookie until instapy's users decide to create a new one

## Current Behavior

Discarging an old cookie activate instagram's bot detection
You have modified instapy to delete old cookie and create a new one, but this think active instagram's bot detection

## Possible Solution (optional)

To use my old cookie: 
every time instagram delete my old cookie i'm stopping instapy, i'm putting my old cookie (that i have saved), and trying to relogin, and after 2 or 3 time i can login with my old cookie.
If the cookie is good, why we are creating a new one at every login ?

**Comment by elulcao** [comment]
there are some considerations for the cookie, 
date expiration, `sameSite` crosscheck, IP connection (the one assigned by the ISP), etc.
I suspect that your old cookie won't work after some time, because to the expiration date.
As my understanding, InstaPy creates a session in an FF browser that emulates being executed on an iPhone, which is valid since some of us prefer to check IG from the browser instead of the APP that is installed from the appStore. Having to recreate the cookie from the browser seems like a task that a real user can do, anyone can delete the browser's history. However, deleting an app's history requires more work than a normal user would normally be willing to.
worst case scenario, If you want to avoid the IG ban at the iPhone level, you have to format the iPhone to have a new identifier. Otherwise, to clear the history of a browser it will be enough to clear all the history.

**Comment by Tolmino** [comment]
Hi, you are right.
...the only think is that: in the last week IG asked me 2 time to change password for security reasons.... and for 4 times i have had a security check with images (where i must click cars, or idrant, or bridges...) and with security code on my phone by sms ....

and this because in last week i have had 7 new cookies.
and that problem i have from commit that cancel it.

so now i'm using old cookie copying it in right place every time instapy delete it.

there is a way to check if old cookie is good and to try to reuse it?
because i can use it.... and often it is good (and in 3/4 time i try it works)

thanks again

**Comment by elulcao** [comment]
I'm facing a similar problem. IG detects unusual activity from Instapy, and then images cannot be liked or comments cannot be done. If I check IG from my phone 📱 there is a pop up window notifying that actions will be limited due to security reasons. 
What I will do is just wait more time that 24hrs to check if my acct is out of risk.

**Comment by Tolmino** [comment]
there is a way to detect if cookie is still good, and re-try to re-login with old one, before discard it ?

**Comment by elulcao** [comment]
Actually the code is intended to load the old cookie,
if something is wrong the cookie is deleted from the machine
and then a new one is created. 

Other InstaPy users reported in different threads that 
removing the old cookie helped to remove the IG's ban 
for liking photos. 
Could you share what is the main intention of reusing 
an old cookie across the time?, maybe there is something
I'm not aware. I would like to see if there is something else
to do to generalize the Logic in the code.

Thanks.

**Comment by Tolmino** [comment]
i have found the time issue that delete my cookie every time
i have done a pull request that fix it
https://github.com/timgrossmann/InstaPy/pull/6041
