### ISSUE TITLE
Can't follow private accounts, even with "session.set_skip_users(skip_private=False, ..."

### ISSUE THREAD

**Issue by lucasandguitars** [InstaPy/InstaPy#6096]
Can someone help me out on this? Thanks again

## Expected Behavior
Follow both public and private profiles

## Current Behavior
Instapy skips private users and shows up the message "This user is private and we are not following"

## InstaPy configuration
session.set_skip_users(skip_private=False,
                       private_percentage=0,
                       ...
session.set_do_follow(enabled=True, percentage=100)

**Comment by lucasandguitars** [comment]
Nothing? :(

**Comment by lucasandguitars** [comment]
Another cry for help... should be simple to solve

**Comment by lucasandguitars** [comment]
@elulcao ? 😬

**Comment by elulcao** [comment]
> @elulcao ? 😬

Hello 
I couldn’t review this issue, but I will check it and share my views. Thanks for the patience

**Comment by elulcao** [comment]
Here the problem is not only the `skip_private=False,` flag,
the conditional is more elaborated than a simple if-else statement,
actually there is needed only one `True` to display the message.

1. If `is_private_profile` returns `None`, usually an exception
2. The acct is private and  not following them
3. They blocked the Instapy user.

You need to verify that you don't met previous conditions.

```python
if (
        is_private is None
        or (is_private is True and following_status not in ["Following", True])
        or (following_status == "Blocked")
    ):
```

`session.set_do_follow(enabled=True, percentage=100)` is intended for interactions.
Im not sure if you configuration has more interactions to activate the `follow_user(...)`
The interactions will call `get_links_for_username()` and the checks I mentioned above.

```python
session.set_skip_users(skip_private=False,
private_percentage=0,
... <== Here you should append more interactions.
session.set_do_follow(enabled=True, percentage=100)
```

Finally, first declare all `session.set_*` configurations, then all the actions.

**Comment by lucasandguitars** [comment]
@elulcao you're the man... Your help is much aprecciated, I would even like to pay for it if possible... Going to test it tonight and get back to you. Many thanks!

**Comment by elulcao** [comment]
> @elulcao you're the man... Your help is much aprecciated, I would even like to pay for it if possible... Going to test it tonight and get back to you. Many thanks!

Hello @lucasandguitars 
Happy to help, the best reward for me is knowing that your problem has been solved.
