### ISSUE TITLE
comment_liked_photo 

### ISSUE THREAD

**Issue by sydrwx** [InstaPy/InstaPy#6247]
Hello! I have seen that function "comment_liked_photo to set_do_comment to be able to comment twice a photo that is already liked; deactivated by default" have been added in release [0.6.13] - 2020-12-30. Does it work properly? In my case, if photo is already liked, the program does nothing, just notifies "Already liked". I also noticed that function session.set_do_like does not affect anything.
My code is:

```
from instapy import InstaPy
from instapy.util import smart_run


# login credentials
insta_username = '123'
insta_password = '123'

# get an InstaPy session!
# set headless_browser=True to run InstaPy in the background
session = InstaPy(username=insta_username,
                  password=insta_password,
                  headless_browser=False)

with smart_run(session):
    """ Activity flow """
    #define interaction settings
    #session.set_do_like(enabled=True, percentage=94)
    session.set_do_comment(enabled=True, percentage=100)
    session.set_comments(["test", "123"])

    
    #start the feature
    session.interact_by_URL(urls=["123"], randomize=False, interact=True)
```

**Comment by fintzd** [comment]
Hey @yd47 ! 

Just to break down this in two parts:
- the question "Does it work properly?"
- the fact that "session.set_do_like does not affect anything."

So as per the first bit, the most simple answer I could give you is that it should. If the code has been committed to the master repo etc that should basically mean that it works. There are just so many people contributing to this repo that it would really be unlikely that an introduced function like this one would not work (of course there can be errors and bugs, but as to  whether a function that is available would do something or not is clearly not something I would think of finding in here).

As per the second bit, I'm not sure whether you pasted the actual script that you are running. If yes, then it is simply not affecting the actions because it is commented out (see below).

Just change this:

```python3
with smart_run(session):
    """ Activity flow """
    #define interaction settings
    #session.set_do_like(enabled=True, percentage=94)
    session.set_do_comment(enabled=True, percentage=100)
    session.set_comments(["test", "123"])
```

To this:

```python3
with smart_run(session):
    """ Activity flow """
    #define interaction settings
    session.set_do_like(enabled=True, percentage=94)
    session.set_do_comment(enabled=True, percentage=100)
    session.set_comments(["test", "123"])
```

Let me know if there is something that I missed or misunderstood in your questions. If not, and if this answers your questions, then please mark the issue as closed.

Cheers!

**Comment by yd47** [comment]
Hello @fintzd !

Yes, it's my actual script. I've tried with commented and commented out:
#session.set_do_like(enabled=True, percentage=94)

If "like" has been placed, script doesn't do anything. In log:

```
INFO [2021-07-01 18:01:14] [markbond273]  Sessional Live Report:
        |> LIKED 0 images  |  ALREADY LIKED: 1
        |> COMMENTED on 0 images
        |> FOLLOWED 0 users  |  ALREADY FOLLOWED: 0
        |> UNFOLLOWED 0 users
        |> LIKED 0 comments
        |> REPLIED to 0 comments
        |> INAPPROPRIATE images: 0
        |> NOT VALID users: 0
        |> WATCHED 0 story(ies)  |  WATCHED 0 reel(s)
```

**Comment by fintzd** [comment]
Hey @yd47 ! 

As I saw in the pasted script, I see that you're not running in headless mode. Is there any indication on what could be the issue based on what you see happening in the browser? 

What I mean is, do you see it skipping on photos that could actually be liked? Is there enough material that it can check, or does the connection drop randomly etc?

Cheers!

**Comment by yd47** [comment]
>  Is there any indication on what could be the issue based on what you see happening in the browser?
Hmm, it looks like everything is ok. There is only one difference - script is working a little bit longer, if "like" has been placed already.
 
> What I mean is, do you see it skipping on photos that could actually be liked? 
Nope

> Is there enough material that it can check, or does the connection drop randomly etc?
I put just one url in block below:

`   #start the feature
    session.interact_by_URL(urls=["123"], randomize=False, interact=True)`

Regards

**Comment by yd47** [comment]
there is no solution
