### ISSUE TITLE
Instapy Discussions

### ISSUE THREAD

**Issue by laboratoriodosfundos** [InstaPy/InstaPy#6253]
Are there any discussion forums about using Instapy?
Anywhere we can discuss best practices and what's been going on?

**Comment by lrnvrryth** [comment]
There's a [discord ](https://discord.gg/FDETsht)channel

**Comment by fintzd** [comment]
Hey @laboratoriodosfundos !

As here @lrnvrryth mentioned right above, there is the [discord](https://discord.gg/FDETsht) channel. 

Apart from that, if you want to check out some ideas of implementation, and best practices so that your account does not get instantly actions blocked because of some too large settings in terms of actions taken (even though the code was refined to a great amount since I first used this project with randomized pauses in the actions taken etc), you can also check out:
- the [instapy](https://instapy.org/) website, where the documentation has a ton of details and tips on the setup to use for each functionality
- take a look at the tutorial on [udemy](https://www.udemy.com/course/the-complete-guide-to-bot-creation/)
- take a look at the "how it works" tutorial on [freecodecamp](https://www.freecodecamp.org/news/my-open-source-instagram-bot-got-me-2-500-real-followers-for-5-in-server-costs-e40491358340/)

Cheers!

**Comment by laboratoriodosfundos** [comment]
> There's a [discord ](https://discord.gg/FDETsht)channel

Thanks for the help I will connect in discord.

**Comment by fintzd** [comment]
> > There's a [discord ](https://discord.gg/FDETsht)channel
> 
> Thanks for the help I will connect in discord.

If that's all good, don't forget to close the issue @laboratoriodosfundos ! :) Thanks!
