### ISSUE TITLE
Interact with users interacting with specific users/posts

### ISSUE THREAD

**Issue by fran6will** [InstaPy/InstaPy#632]
Hey guys! I would have liked to code my idea by myself but I have zero Python skills... 

I thought it would be nice to be able to interact with users interacting with specific users/posts. 

 Something like : 

```
#Interact with the people interacting with a given user
session.interact_user_interacting(['natgeo'], amount=10, random=True)

#Interact with the people interacting on tags
session.interact_user_interacting(['#poultry', #superheroes], amount=10, random=True)

```
It could be a way to attract more active users.. What do you think?
@timgrossmann

**Comment by pixelcatcher** [comment]
and I would like to interact with users who engage with a certain post

**Comment by converge** [comment]
There is no interaction for a long time, please reopen it if you still need some help.

**Comment by HighTideHuts** [comment]
@timgrossmann  Have you had any thoughts to incorporate this? 

```
#general-settings
    session.set_user_interact(amount=3, randomize=True, percentage=100, media='Photo')

#activity
    #Interact with the people interacting on tags
    session.interact_user_hashtagging(['#travel, #earth], amount=10, random=True)
```

Interacting bases on hashtags is very powerful because it allows you to engage a few times for each user. At the moment, if you want to target hashtags you have to compromise using interact, which means you can only like each user that posts in that hashtag 1 time. I have found that the likelihood of getting a follow from a user goes up significantly if you like multiple of their photo's. 

At the moment the closest thing is `interact_user_followers` which let you choose for example @.beautifuldestinations and interact with their followers. The problem with that is  a lot of the time you are interacting with inactive accounts or accounts that view the travel content but do not post it. 

Lets assume I'm in the travel niche and I am interacting with followers of @.beautifuldestinations. Lets say @.randomaccount is one of their followers, so the bot would interact with them. However, @.randomaccount probably doesn't **post** travel pics, he just likes to **view** them. His feed is probably filled with motorbike posts or something irreverent. 

This means I might end up engaging with people that are interested in my travel content, but I won't be interacting with travel content myself which isn't ideal for the long term success of my account. It's much better if I engage in people that view **and** post in the travel category. This can only be achieved by interacting with users that post in hashtags.

Hope this all makes sense. Please let me know your thoughts.
