### ISSUE TITLE
ImportError: cannot import name 'UNICODE_EMOJI' from 'emoji.unicode_codes'

### ISSUE THREAD

**Issue by shakeelkoper** [InstaPy/InstaPy#6635]
## Current Behavior
on Running a simple Script like
from instapy import InstaPy
InstaPy(username=<username>, password=<password>).login()
getting  ImportError: cannot import name 'UNICODE_EMOJI' from 'emoji.unicode_codes'

**Comment by mavilar** [comment]
I'm having this same issue and it looks like it's related to the lastest version of the `emoji` library. As a temporal solution I have installed this library by manually specifying version `<2.0.0`, and now it works.

**Comment by Huhnicorn** [comment]
Solution:
pip uninstall emoji
pip install emoji==1.7

**Comment by mavilar** [comment]
@metapodcod, I didn't solve that issue you're referring to. I was only talking about this one: the `ImportError` exception.

**Comment by AkariOficial** [comment]
> 

THANKS A LOT!!!!

**Comment by lavrynenko** [comment]
Good afternoon.
Available:
1. InstaPy: version 0.6.16
2. Emoji: version 1.7

I am getting an error:
ImportError: cannot import name 'UNICODE_EMOJI' from 'emoji.unicode_codes' (C:\Users\oleks\PycharmProjects\PhotoGiessen\venv\lib\site-packages\emoji\unicode_codes\__init__.py)
Please tell me how to get rid of this error?

Thank's!

**Comment by official-antique** [comment]
Fixed in [3c35e2a](https://github.com/InstaPy2/InstaPy2/commit/3c35e2a51bf6b4808a17c7fd284e8b59a84858aa) but it still won't work. You could try my project [InstaPy2](https://github.com/InstaPy2/InstaPy2) which has almost all of the same functionality and then some.

**Comment by Lavrynenko** [comment]
Tried your solution. 
code: 
from instapy2 import InstaPy2
session = InstaPy2(username='username', password='password')

I get the following response:
Traceback (most recent call last):
  File "C:\Users\oleks\PycharmProjects\Photo\photo_test.py", line 1, in <module>
    from instapy2 import InstaPy2
  File "C:\Users\oleks\PycharmProjects\Photo\venv\lib\site-packages\instapy2\__init__.py", line 1, in <module>
    from .configuration import Configuration
  File "C:\Users\oleks\PycharmProjects\Photo\venv\lib\site-packages\instapy2\configuration.py", line 2, in <module>
    from .utilities import *
  File "C:\Users\oleks\PycharmProjects\Photo\venv\lib\site-packages\instapy2\utilities\__init__.py", line 1, in <module>
    from .comments import CommentsUtility
  File "C:\Users\oleks\PycharmProjects\Photo\venv\lib\site-packages\instapy2\utilities\comments.py", line 1, in <module>
    from . import UtilityBase
ImportError: cannot import name 'UtilityBase' from partially initialized module 'instapy2.utilities' (most likely due to a circular import) (C:\Users\oleks\PycharmProjects\Photo\venv\lib\site-packages\instapy2\utilities\__init__.py)


Banging my head against the wall :)
