### ISSUE TITLE
Constant "Already liked"

### ISSUE THREAD

**Issue by ediooo** [InstaPy/InstaPy#687]
Hi,
I am using 
session.like_by_tags([
 with amount 1 and about 20 tags.

After running the script 2-3 times everything seems to be "already liked". (What i says in the console) 

Is it only liking the "most popular" tag so its always picking the same ones?
Or is there anything i can do like the other images? I know for sure there are many more "unliked" ones for each tag i am using...

Thanks!

**Comment by ediooo** [comment]
Or to be more precise: Can the choice of the image to be liked of a certain hastag be more randomized somehow?

**Comment by timgrossmann** [comment]
@ediooo Amount 1 means the script will only look at the first post of given tag...
The most popular posts are pinned on top, so it's always the same post that's why you get Already liked.

Please read the Readme for information about how the features work

You can simply just put a lot of them after each other.

```python
session.like_by_tags([dogs], amount=500)
session.like_by_tags([cats], amount=100)
```

**Comment by ediooo** [comment]
@timgrossmann Thanks - but what should i do if i want to use a long list (30 hashtags) and then only like 1 or 2 images per hashtag?

**Comment by ediooo** [comment]
this is more a suggested feature than an issue, but having a "sort" option/parameter for the liking would make a lot of sense, like: random, or most popular, or newest. If it has to stick with the most popular than it should at least proceed with the "second popular" instead of trying to like the same image forever and failing since it is already liked....

**Comment by octohedron** [comment]
@timgrossmann Sorry to ping you but is it normal for the amount parameter to be completely ignored? I can put any amount and it will only go up to 25-35.
i.e.
`session.like_by_tags([dogs], amount=500)` will only like / comment 27 and move on to the next tag.

Didn't want to open a new issue since it's kind of related.
