### ISSUE TITLE
Follow user followers bug

### ISSUE THREAD

**Issue by dominicwhyte** [InstaPy/InstaPy#697]
Anybody facing this as well? Restarting the script doesn't seem to fix the issue. Thanks!

Message: no such element: Unable to locate element: {"method":"xpath","selector":"//li[2]/a/span"}
  (Session info: chrome=61.0.3163.79)
  (Driver info: chromedriver=2.29.461571 (8a88bbe0775e2a23afda0ceaf2ef7ee74e822cc5),platform=Linux 4.4.0-96-generic x86_64)

**Comment by oldspankie** [comment]
Yea, same thing, on both Windows & Linux, with & without nogui.  If you remove/comment out .set_do_follow, it won't crash at all, but that almost defeats the purpose.  You'll still get follows from others due to likes (seeing about ~10 a day since removing '.set_do_follow'), but not follow anyone.

Since I commented that part out, followers gained is higher than otherwise, due to the script not crashing so early all the time.

It used to work fine, then started getting hairy a couple weeks back - this change was without any new commits pulled.  I'm guessing the Instagram gui has changed just enough to throw it off kilter, or maybe something else with chrome.  Haven't tried seeing if there's a newer chromedriver or anything, or if even a simple replace would fix.

**Comment by converge** [comment]
@dominicwhyte @oldspankie is think this is fixed, am I correct ?
