### ISSUE TITLE
Login problem on Windows (abort)

### ISSUE THREAD

**Issue by Venni27** [InstaPy/InstaPy#709]
Hello,

after starting the script, the Chrome browser starts up and I the credentials are filled in the form.
Then the login is successful. I can see my IG page.
But then the script aborts with the following:
**Wrong login data!
Session ended
-------------**
Any suggestions?

Frank

**Comment by timgrossmann** [comment]
@Venni27 If you'd searched the other issues you probably would've found a dozen of the same questions...

If you're sure your data is right, then you have to login to Instagram yourself once since it thinks you've been hacked or something like that... Just click "Ok" at the pop up and you're ready to go

**Comment by Venni27** [comment]
@timgrossmann I have already tried this. As entioned, I am sure that the credentials are right, cause I can see the page for a few seconds. When I login manually, there is no hint to been hacked or something else. Sorry for disturbng if I am simly doing something wrong, but at the moment I could not find any false config.
Your hint with the other problems helped, cause Ihave only searched in the open issus. It is not possible to let the script do the logon. After the script puts the credentias in, I have to manually push the login button.
Thanks for your help ;-)
