### ISSUE TITLE
Question: What does sleep_reduce means?

### ISSUE THREAD

**Issue by remorses** [InstaPy/InstaPy#764]
I haven't understood what you mean in readme when you write "set_time_reduce: reducing sleep time to a percentage."
What sleep time?

**Comment by converge** [comment]
hey @remorses, take a look at docs: 

https://github.com/timgrossmann/InstaPy

**Comment by pilotdude** [comment]
In a variety of places the script pauses or sleeps so that it appears more natural to Instagram. If you want this pause to be shorter then you can tell the code to sleep for a percentage of the default time. For example if I wanted the default sleep time to be only 80% of what it is normally then I would put session.set_sleep_reduce(80). The sleep time is built in to help avoid getting your account blocked though so be careful when messing with it. 

Check out instapy\timeutil.py if you want to see how the sleep time is calculated.
