### ISSUE TITLE
(Feature Poll) Interest in using MySQL Database with InstaPY?

### ISSUE THREAD

**Issue by randysinnott** [InstaPy/InstaPy#850]
I've been modifying my local repo so that it reads most variables out of a MySQL database instead of from the config file.  I am beginning to insert some additional code that logs results to the same database instead of into a flat log file.

The major advantage I'm looking to leverage is that other applications can more easily make changes to the hashtags, amounts to be liked, followed, unfollowed, etc.  The vision behind this is that changes can be easily made thru any variety of interfaces, via DB changes, instead of hand editing config files.

There are some pros and cons to this approach, but I figured I'd poll the community to see if there is interest in me working to commit these features to the main repo, or to just maintain it as my own private branch.

**Comment by pilotdude** [comment]
I have been fiddling with adding in some DB functionality but more for optimizing how the program runs and collecting analytics data. I've been using SQLite instead of MySQL because it's already pre-installed on most systems. 

My thinking has been to use DB functionality to do things like record the number of followers a user has and what posts have been already liked so that in the future when InstaPy comes across a post by that user it doesn't have to check their profile to see how many followers they have. (Assuming their follower count was updated recently)

**Comment by randysinnott** [comment]
Interesting.  I have hooked in the run statistics for analytics purposes as well :).  In particular, I have modified the follow/unfollow to stay within a "target range" of number of people to follow.  And I guess the choice of DB is a bit moot as multiple adapters could be written for your of Relational DB.

I really do like that idea of optimizing the post checking mechanism for better performance as well.

**Comment by gedankenstrom** [comment]
I like the idea.. more performance and statistic to show.

**Comment by ssthormess** [comment]
This would be great: with this we could work on a Web GUI to handle our accounts, the schedule and action variables (campaigns?) for these accounts, operation logs, account statistics, etc. Anyone else interested?

**Comment by tarikbelattar** [comment]
Hi guys this can be an amazing evolution for instapy. We can access data easily. Did this project still active?

Thanks,
