### ISSUE TITLE
Immoral Project

### ISSUE THREAD

**Issue by jokull** [InstaPy/InstaPy#9]
Likes and engagement are digital currency and you are devaluing them. You should add a disclaimer that users are risking being banned from the platform.

**Comment by timgrossmann** [comment]
@jokull Yes you're right, Likes and engagement is a digital currency... **But it's a really corrupt and nasty one**. People with a lot of money can just buy them online, buy them easily! Or be part of services, there are dozens of it, and pay for exactly the same thing you can get here... **Except mines for Free**.

Also, I think that everyone should get the chance to become a so called "Influencer"... whatever this even means. 

Some photographers I saw on Instagram had insane photos but no-one saw them because it's really hard to find new people on Instagram. 
Other accounts with really bad content or just another half naked girl had tons of followers... which therefore, of course, lead to quite some money.

**Why don't give everyone the same opportunity to get social fame and maybe get the next big influencer?**

> By the way, I love Iceland... Been there last summer, great country!

**Comment by timgrossmann** [comment]
I already added a bold notification about the banning party :wink:

> It's easy to use and the built in delays prevent your account from getting banned. (Just make sure you don't like 1000s of post/day)

**Comment by jokull** [comment]
We’ll agree to disagree :) Thanks for a thoughtful response.

**Comment by jelen07** [comment]
@jokull If likes and engagement are digital currency it is absolutely necessary to devalue them.
